kamranahmedse/developer-roadmap

- README.md
- project-files/devops-map.json
Typically I'd put multiple changes like this in multiple PRs but since an image needs to be generated, one PR made sense.
Added CircleCI to the CI section in place in TeamCity. CircleCI is the second most used CI with GitHub ([according to their recent study](https://github.com/blog/2463-github-welcomes-all-ci-tools)).
Added [Packer](https://www.packer.io/) to the Automation section which is a hugely popular tool and works well with many of the services listed elsewhere in the DevOps section.
SaltStack is one word not two so I removed the space.
Added MTR to the network tools command. For those that don't know, it's almost ping and traceroute combined.
Fixes #161 and #280 which have been requesting CircleCI.
> Add CircleCI, Packer, remove TeamCity, fix SaltStack.

- readme.md
Because the tech industry isn't for males only.
> Emoji for both genders

- src/backend-map.json
Backend Roadmap
Grammar errors
> Fix some grammar in "Learn a Language"

- src/backend-map.json
- [**] Backend Roadmap
- [** ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [**] I have read the [contribution docs](../contributing.md) before opening this PR.
corrected a typo in Backend map from Gitlab to GitLab
> corrected a typo in Backend map from Gitlab to GitLab

- CONTRIBUTING.md
> there's a grammatical error!

- translations/spanish/src/frontend-map.json
> [SP Translation] Typo fixed line 11283

- readme.md
> fix: link to golang road map.

- content/roadmaps/100-frontend/content/114-css-frameworks/114-js-first/100-tailwind-css.md
- [✔️] Frontend Roadmap
- [ ✔️] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ✔️] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ✔️] I have read the [contribution docs](../contributing) before opening this PR.
> Add interactive content for tailwind-css

- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/readme.md
> add react.js resources

- content/roadmaps/100-frontend/content/105-repo-hosting-services/100-github.md
- [x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
> feat: added github learning resources

- content/roadmaps/100-frontend/content/102-css/readme.md
- public/project/frontend.json
- [✅] Frontend Roadmap
- [✅] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [✅] This is not a duplicate issue. I have searched and there is no existing issue with this.
- [✅] I understand that these roadmaps are highly opinionated. The purpose is not to include everything out there in these roadmaps but to have everything that is most relevant today compared to the other options listed.
- [✅] I have read the [contribution docs](../contributing) before opening this PR.
Wes Bos is a renowned Front end engineer, his Flexbox tutorial helped a lot of people including myself understand it and be comfortable using it, I think front end newcomers will benefit greatly from this resource
> Added CSS Flexbox learning resource

- content/roadmaps/100-frontend/content/102-css/readme.md
- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/readme.md
added CSS resources:
- Learn CSS from w3schools
- Learn HTML and CSS by Shay Howe
- freeCodeCamp Responsive Web Design Course
> add CSS resources

- content/roadmaps/100-frontend/content/101-html/104-accessibility.md
Added accessibility content for the frontend roadmap.
> Added Accessibility content

- content/roadmaps/100-frontend/content/110-build-tools/101-module-bundlers/100-webpack.md
> Add content to "Webpack"

- content/roadmaps/100-frontend/content/102-css/readme.md
- [✅] Frontend Roadmap
- [✅] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [✅] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [✅] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [✅] I have read the [contribution docs](../contributing) before opening this PR.
What The Flexbox! Is one of the well-known CSS Flexbox free tutorials out there that have helped me and thousands of developers worldwide to understand flexbox. This video series will be handy to any newcomers to the world of Front End development
> Added [course] Flexbox learning resource

- content/roadmaps/100-frontend/content/122-desktop-applications/100-electron.md
Updated the Electron section in the front end road map
I have updated the electron section to include its general "definition" and what it can be used for.
> Updated the Electron section

- content/roadmaps/100-frontend/content/109-css-preprocessors/readme.md
Added  CSS Preprocessors Resources and Content.
> Added CSS Preprocessor Resources and Content

- content/roadmaps/100-frontend/content/115-testing-your-apps/readme.md
I added context for the 'Testing your apps' section. Hoping it meets the quality standards of roadmap.sh. I've benefited so much from the resource, and would like to give back.
> Suggest content to 'Testing your apps' component

- content/roadmaps/100-frontend/content/115-testing-your-apps/100-jest.md
- [x ] Frontend Roadmap
- [x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ x] I have read the [contribution docs](../contributing) before opening this PR.
Added official Jest website link
> Add official Jest website

- content/roadmaps/101-backend/content/103-learn-a-language/100-go.md
- added a one liner explaining what Go does
- added the Go resources listed on the go.dev website
> Update 100-go.md : add few details

- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/readme.md
Added a new video [React Course - Beginner's Tutorial for React JavaScript Library [2022]](https://www.youtube.com/watch?v=bMknfKXIFA8) by Bob Ziroll, which was posted on FreeCodeCamp's channel on Jan 10, 2022
> Added a new course

- content/roadmaps/101-backend/content/102-os-general-knowledge/readme.md
I would like to add these resources since they have helped me to understand this topic.
PS: This is my first pull request
> Add Os and General KnowKnowledge content at backend roadmap

- content/roadmaps/100-frontend/content/119-graphql/readme.md
Course is available in Youtube by freeCodeCamp and is really beginners friendly, Link - https://www.youtube.com/watch?v=ed8SzALpx1Q
> GraphQL free Course for Beginners added from freeCodeCamp

- content/roadmaps/100-frontend/content/100-internet/102-browsers-and-how-they-work.md
✌️Added a youtube video as a watchable resource I found very useful and enough. I think knowing that much about how the browsers work is enough for the Front-end journey. The video covered all the important topics from User-Interface to Rendering Engine.
> 🎯Added a resource - (YouTube Video)

- content/roadmaps/100-frontend/content/119-graphql/101-relay-modern.md
> Added Description and Resources for Relay Modern

- content/roadmaps/100-frontend/content/119-graphql/100-apollo.md
> Apollo Description and Content added

- content/roadmaps/100-frontend/content/111-pick-a-framework/102-vue-js/readme.md
> Added Resources for Vue.js

- content/roadmaps/101-backend/content/103-learn-a-language/105-javascript.md
Added description and links in JavaScript (learn a language) in backend roadmap.
> added content in JavaScript (learn a language) in backend roadmap

- content/roadmaps/101-backend/content/114-design-and-development-principles/106-dry.md
Add a description and resources for DRY software development/design principle
> DRY description and resources

- content/roadmaps/101-backend/content/114-design-and-development-principles/105-yagni.md
Adds description and resources for YAGNI software development/design principle
> YAGNI description and resources

- content/roadmaps/101-backend/content/114-design-and-development-principles/104-kiss.md
Adds a description and resources for KISS software development/design principle
> KISS description and resources

- content/roadmaps/101-backend/content/109-apis/100-rest.md
The backend diagram makes reference to Roy Fielding's dissertation. I thought it would be helpful to have a direct link to his paper for convenience. Please let me know if any adjustments would be helpful, or if I've follow the wrong contribution process! Thanks for creating this wonderful resource.
> Add link to Roy Fielding's paper

- content/roadmaps/100-frontend/content/110-build-tools/100-task-runners/100-npm-scripts.md
> Resources added for NPM Scripts

- content/roadmaps/101-backend/content/114-design-and-development-principles/103-solid.md
Add a description and resources for the SOLID design principles
> Description and resources for SOLID

- content/roadmaps/101-backend/content/114-design-and-development-principles/102-test-driven-development.md
Add description and resources for TDD
> Add content for Test Driven Development

- content/roadmaps/101-backend/content/123-scalability/103-horizontal-vertial-scaling.md
- Add description and resources for vertical and horizontal scaling
- Fix typo
> Add content for Scaling

- content/roadmaps/101-backend/content/105-repo-hosting-services/readme.md
Add description and resources for repo hosting services
> Add content for Repo Hosting Services

- content/roadmaps/101-backend/content/104-version-control-systems/readme.md
Add a description and resources for version control systems
> Add content for Version Control Systems

- content/roadmaps/100-frontend/content/121-mobile-applications/100-react-native.md
> React Native resources added

- content/roadmaps/100-frontend/content/117-progressive-web-apps/readme.md
> Progressive Web Apps resources added

- content/roadmaps/101-backend/content/112-testing/readme.md
Add a description and resources for testing
> Add content for Testing

- content/roadmaps/101-backend/content/112-testing/100-integration-testing.md
Add a description and resources for Integration Testing
> Add content for Integration Testing

- content/roadmaps/101-backend/content/112-testing/101-unit-testing.md
Add a description and resources for Unit Testing
> Add content for Unit Testing

- content/roadmaps/101-backend/content/112-testing/102-functional-testing.md
Add a description and resources for Functional Testing
> Add content for Functional Testing

- content/roadmaps/101-backend/content/118-containerization/100-docker.md
Add a description and resources for Docker. However, Docker is a big topic and could probably use some more information.
> Add content for Docker

- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/102-recoil.md
> Resources added for Recoil.js

- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/101-mobx.md
> Resources added for MobX

- content/roadmaps/101-backend/content/106-relational-databases/readme.md
> Add Relational Databases Content

- content/roadmaps/101-backend/content/107-nosql-databases/readme.md
> Update NoSQL readme.md

- content/roadmaps/100-frontend/content/116-type-checkers/101-flow.md
> Resources added for Flow

- content/roadmaps/100-frontend/content/112-modern-css/101-css-modules.md
Also I think you guys should change CSS Modules to Alternative Option as is not used much anymore.
I just added content to Css  modules and also pls change CSS Modules to Alternative Option as is not used anymore.
> Add content to Css modules

- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/101-ngrx.md
> Resources added for NgRx

- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/100-rxjs.md
> Resources added for RxJS

- content/roadmaps/100-frontend/content/110-build-tools/102-linters-formatters/101-eslint.md
> change badge text

- content/roadmaps/101-backend/content/102-os-general-knowledge/106-interprocess-communication.md
Add a video from Neso Academy resource for basic knowledge for Interprocess Communication page
> Added Resources for Interprocess Communication

- content/roadmaps/100-frontend/content/121-mobile-applications/103-ionic.md
> Added Resources for Ionic Framework

- content/roadmaps/100-frontend/content/120-static-site-generators/readme.md
> Resources added for static site generators

- content/roadmaps/100-frontend/content/123-web-assembly.md
> Resources added for Web Assembly

- content/roadmaps/100-frontend/content/121-mobile-applications/101-nativescript.md
> Resources added for NativeScript framework

- content/roadmaps/100-frontend/content/100-internet/101-what-is-http.md
- content/roadmaps/101-backend/content/100-internet/101-what-is-http.md
I've recently read this 3-part series on HTTP, mostly focused on HTTP/3 and QUIC, but the first part covers basic concepts about HTTP and how it evolved to HTTP/3 (which is really HTTP/2-over-QUIC) and I find it might be a great reading resource on the topic.
I'm not recommending the 2nd and 3rd parts as they're linked through the 1st one and they diverge a little from the topic of HTTP (going into performance improvements and deployment of QUIC)
> Added Resources for HTTP

- content/roadmaps/101-backend/content/109-apis/104-hateoas.md
Added one of my favourite talks about RESTful API Development but specifically the time frame where they discuss HATEOAS, also added an introduction
> Updated HATEOAS

- content/roadmaps/100-frontend/content/114-css-frameworks/114-js-first/102-material-ui.md
> Added Resources for Material UI

- content/roadmaps/100-frontend/content/112-modern-css/103-emotion.md
> Added Resources for Emotion css

- content/roadmaps/100-frontend/content/112-modern-css/102-styled-jsx.md
> Added resources for Styled jsx

- content/roadmaps/100-frontend/content/102-css/readme.md
Added resource - web.dev Learn CSS topic
> Update 102-css topic

- content/roadmaps/100-frontend/content/117-progressive-web-apps/readme.md
Added one more course for PWA from web.dev (by Google). This one is in progress (But already has sufficient content for learning), so link would be actual while it's completing at least
> Update 117-progressive-web-apps topic

- content/roadmaps/100-frontend/content/112-modern-css/100-styled-components.md
> Resources added for Styled Components

- content/roadmaps/101-backend/content/115-architectural-patterns/104-serverless.md
Add description and resources for serverless
> Add content for Serverless

- content/roadmaps/101-backend/content/115-architectural-patterns/101-microservices.md
Add description and resources for Microservices pattern
> Add content for Microservices

- content/roadmaps/101-backend/content/115-architectural-patterns/100-monolithic-apps.md
Add description and resources for monolithic pattern
> Add content for Monolithic applications

- content/roadmaps/100-frontend/content/109-css-preprocessors/102-less.md
> Added Resources for Less

- content/roadmaps/100-frontend/content/122-desktop-applications/101-carlo.md
> Added content for Carlo

- content/roadmaps/100-frontend/content/110-build-tools/102-linters-formatters/102-standardjs.md
> Added content in Standardjs

- content/roadmaps/100-frontend/content/110-build-tools/101-module-bundlers/103-parcel.md
> Added resources for Parcel

- content/roadmaps/100-frontend/content/122-desktop-applications/102-proton-native.md
> Added resources for Proton Native

- content/roadmaps/100-frontend/content/120-static-site-generators/103-vuepress.md
> Resources added for VuePress

- content/roadmaps/101-backend/content/105-repo-hosting-services/100-github.md
The GitHub Flow course is an interactive course that shows you how to use Git in a professional setting. It includes a bot that will initiate a code review, request changes, etc., and provides a lot of resources within to become better at using Git/GitHub.
> [100-github] - Added course to list.

- content/roadmaps/100-frontend/content/115-testing-your-apps/105-mocha.md
> Added Resources for Mocha

- content/roadmaps/101-backend/content/108-more-about-databases/108-cap-theorem.md
- content/roadmaps/101-backend/content/109-apis/104-hateoas.md
Attached some useful resources and a description of CAP Theorem
> CAP Theorem Resources

- content/roadmaps/100-frontend/content/115-testing-your-apps/106-chai.md
> Resources added for Chai js

- content/roadmaps/100-frontend/content/115-testing-your-apps/107-ava.md
> Resources added for Ava

- content/roadmaps/100-frontend/content/120-static-site-generators/105-hugo.md
> Resources added for Hugo

- content/roadmaps/100-frontend/content/115-testing-your-apps/108-jasmine.md
> Resources added for Jasmine

- content/roadmaps/101-backend/content/119-graphql/100-apollo.md
> Resources added for Apollo

- content/roadmaps/101-backend/content/119-graphql/readme.md
> Resources added for GraphQL

- content/roadmaps/101-backend/content/109-apis/105-open-api-spec.md
Updates the OpenApi  Details Page
> Adds Basic details for the Open API Spec

- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/readme.md
- [] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
Added concise, easy to understand Angular definition and link to official docs.
> Add Angular definition and official docs link

- content/roadmaps/101-backend/content/111-web-security-knowledge/105-content-security-policy.md
> Resources added for Content Security policy

- content/roadmaps/101-backend/content/111-web-security-knowledge/108-owasp.md
> Resources added for OWASP

- content/roadmaps/101-backend/content/119-graphql/101-relay-modern.md
> Resources added for Relay Modern

- content/roadmaps/101-backend/content/107-nosql-databases/100-document-databases.md
Add MongoDB official website, documentation & courses links. Their courses consist of a structure progression to tackle MongoDB all the way from basic set-up to creating a web application depending on the languages (Java, Javascript, Python & .NET) to learning about data modelling for MongoDB. 
I have added a link to an online MongoDB sandbox as well.
> Add MongoDB content

- content/roadmaps/101-backend/content/108-more-about-databases/103-n-plus-one-problem.md
> n+1 problem article link

- content/roadmaps/101-backend/content/102-os-general-knowledge/102-process-management.md
This adds resource links to the Process Management topic as well as a brief summary
> Added Process Management definition and resources

- content/roadmaps/100-frontend/content/101-html/105-seo-basics.md
Added resources for Basics of SEO in Frontend Roadmap.
> Added resources for Basics of SEO in Frontend Development Roadmap

- public/project/devops.json
> Update devops.json - fix typo

- content/guides/threads-and-concurrency.md
- [I dropped a note on the 'help wanted' issue] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
As per my comment on the help wanted issue, I'm using the opportunity to contribute to your awesome project to brush up/gain some knowledge as well as get some practical experience forking/contributing on projects. 
The summary is a little over the limit but I feel it's in style with the rest of the content on the roadmaps. Let me know if you think it needs updating/correcting at all. 
Thanks!
> Add content - threads and concurrency

- content/roadmaps/101-backend/content/122-web-servers/100-nginx.md
> Resources added for Nginx

- content/roadmaps/101-backend/content/102-os-general-knowledge/103-threads-and-concurrency.md
This adds resource links to the Threads and Concurrency topic as well as a summary
> Added Threads and Concurrency definition and resources

- content/roadmaps/101-backend/content/102-os-general-knowledge/105-memory-management.md
Fixing memory management resource type
> Fix memory management resource type

- content/roadmaps/100-frontend/content/115-testing-your-apps/103-enzyme.md
> Add Enzyme content on Front End roadmap

- content/roadmaps/101-backend/content/122-web-servers/102-caddy.md
> Resources added for CaddyServer

- content/roadmaps/101-backend/content/122-web-servers/103-ms-iis.md
> Resources added for MS IIS

- content/roadmaps/101-backend/content/111-web-security-knowledge/readme.md
> Resources added for Web Security Knowledge

- content/roadmaps/100-frontend/content/121-mobile-applications/103-ionic.md
> fix: remove colorScheme attribute at Ionic video tutorial

- content/roadmaps/101-backend/content/118-containerization/readme.md
> Resource add -> Containerization vs Virtualization

- content/roadmaps/100-frontend/content/121-mobile-applications/100-react-native.md
> fix: remove colorScheme attribute at React Native video tutorial

- content/roadmaps/100-frontend/content/100-internet/100-how-does-the-internet-work.md
As the article that describes how the internet works, Vox also have a very intersing video about the topic. It's a great production that covers the whole process among sending and receiving a picture between mobile phones.
> Add the Vox video "How  Does the Internet Works?"

- content/roadmaps/100-frontend/content/100-internet/103-dns-and-how-it-works.md
If you host your name servers within your own domain name (e.g. ns1.google.com for google.com), a simple DNS setup without glue records will not work. Likewise, if you add glue records when it's unnecessary and the IP addresses of your name servers changes, you could accidentally take your website offline.
For this reason, I think it's useful to learn when they are essential and when they are dangerous, as well as how they work.
> Add explanation of glue records in DNS

- content/roadmaps/101-backend/content/117-message-brokers/100-rabbitmq.md
- content/roadmaps/101-backend/content/117-message-brokers/101-kafka.md
- content/roadmaps/101-backend/content/117-message-brokers/readme.md
Added description for apache kafka and rabbitmq pages. I used materials (documents to read and video to watch) from their respective websites (which in my opinion are widely respected and valid). 
There was no issue for missing docs on message brokers
> updated message-borkers pages

- content/roadmaps/100-frontend/content/118-server-side-rendering/100-react-js/101-after-js.md
> Update 101-after-js.md added introduction and links

- content/roadmaps/101-backend/content/109-apis/101-json-apis.md
> Resources added for JSON api

- content/roadmaps/100-frontend/content/118-server-side-rendering/101-angular/readme.md
I just copied the content from Angular section
> Add angular content

- content/roadmaps/100-frontend/content/118-server-side-rendering/100-react-js/readme.md
I just copied the content from React section
> Add react content

- content/roadmaps/100-frontend/content/118-server-side-rendering/102-vue-js/readme.md
I just copied the content from another Vue section
> Add vue content

- content/roadmaps/100-frontend/content/111-pick-a-framework/102-vue-js/readme.md
I just removed extra empty line
> Remove extra empty line

- content/roadmaps/101-backend/content/111-web-security-knowledge/101-sha-family.md
I just added the content for the SHA family in the backend roadmap.
> Add SHA family content for the back-end roadmap

- content/roadmaps/100-frontend/content/114-css-frameworks/114-css-first/100-bootstrap.md
I have added the official bootstrap documentation as a resource.
> Added Bootstrap Documentation

- content/roadmaps/100-frontend/content/110-build-tools/102-linters-formatters/readme.md
> Resources added for Linters formatters

- content/roadmaps/100-frontend/content/117-progressive-web-apps/101-performance.md
I have added a description and several resources that I have used myself and found useful in learning the topic of PWA performance analysis. 
-1st link is from google web.dev and provides several articles on what is speed, how does it matter and how one can measure and optimize the performance of PWAs. 
-2nd link gives detailed explanation on what is PRPL pattern and how it works. 
-3rd resource is from google web.dev and teaches how to implement PRPL pattern to instantly load PWAs
-4th resource is from google web.dev and gives a detailed account about RAIL model and its implementation
-5th resource is from freecodecamp and gives an introduction to Chrome Lighthouse
-6th resource is from PWA training module of Google Developers (Web)
-7th resource is a 5 minute tutorial on how to use …
> Add content to PWA peformance node

- content/roadmaps/101-backend/content/111-web-security-knowledge/107-ssl-tls.md
I just added the content for the SSL/TLS protocols in the backend roadmap.
> Add SSL/TLS content for back-end roadmap

- content/roadmaps/101-backend/content/111-web-security-knowledge/104-scrypt.md
I just added the content for the scrypt algorithm in the backend roadmap.
> Add scrypt content for back-end roadmap

- content/roadmaps/100-frontend/content/117-progressive-web-apps/readme.md
I am suggesting the addition of PWA tutorials from MDN Web Docs. Apart from basic introduction to PWAs, it has numerous helpful How-to's such as using client-side storage with IndexedDB and Web Storage API, making mobile-first and installable PWAs, enabling "add to home screen", using notifications and push API etc.
> Add PWA resource

- content/roadmaps/101-backend/content/120-graph-databases/100-neo4j.md
> Resources added for Neo4j

- content/roadmaps/101-backend/content/111-web-security-knowledge/100-md5.md
small fix to grammar: it's -> its
> corrected grammar: it's -> its

- content/roadmaps/100-frontend/content/100-internet/103-dns-and-how-it-works.md
https://messwithdns.net is a DNS server playground made by Julia Evans (of the tech [wizardzines](https://wizardzines.com/) fame).
It went along with a series of zines, however, stands on its own as well. It contains a DNS-server-in-your-browser. Where every visitor gets their own DNS server at a dynamic subdomain and they can create DNS entries, view request logs, etc. There's also a guided little tutorial in the sidebar.
IMO its a **fantastic** resource for simply experimenting with and seeing what a DNS server is and what they do! Such a great learning resource!
> Add 'messwithdns.com' julia evans DNS playground

- content/roadmaps/101-backend/content/116-search-engines/101-solr.md
> Resources added for Solr

- content/videos.json
Fixes the following wrong description:
> Fix wrong content description for Freeze and Seal in JavaScript

- content/roadmaps/101-backend/content/106-relational-databases/104-oracle.md
> Resources added for oracle

- content/roadmaps/101-backend/content/111-web-security-knowledge/100-md5.md
> Change md5 wiki link to english wiki

- content/roadmaps/101-backend/content/115-architectural-patterns/103-cqrs.md
> Add resouce for cqrs and event sourcing

- content/roadmaps/101-backend/content/100-internet/101-what-is-http.md
> fix Journey to HTTP/2 link

- content/roadmaps/100-frontend/content/100-internet/103-dns-and-how-it-works.md
DNS Records for Newbies - How To Manage Website Records - https://www.youtube.com/watch?v=YV5tkQYcvfg
> Add 'DNS Records for Newbies'

- components/opensource-banner.tsx
updated as 6th most starred repository.
> updated as 6th most starred repo

- content/roadmaps/101-backend/content/109-apis/103-grpc.md
I thought that some high-level definition of this would be nice.
> Update gRPC deffinition

- content/roadmaps/100-frontend/content/103-javascript/102-learn-fetch-api-ajax-xhr.md
RapidAPI gives an in-depth explanation of fetch API. what it is, How to use it to process API responses, HTTP Methods with Fetch API and How can errors be handled. Suited For Beginners and the content is packed with real-time examples.
> Added a New resource to Fetch API

- content/roadmaps/101-backend/content/103-learn-a-language/103-php.md
I wanted to add this complete PHP tutorial because it goes deep into important, different concepts and involves new PHP 8.0 features.
> Add new PHP resource (video tutorial)

- content/roadmaps/100-frontend/content/100-internet/100-how-does-the-internet-work.md
Back a few months ago when I was learning frontend web development this article helped me understand with it's use of simple explanations and digestible easy to understand, and I think it's a good fit for it's excellent unpacking of such an important concept
> Added MDN article How does the internet work MDN article

- content/roadmaps/100-frontend/content/116-type-checkers/readme.md
i added a small description for the type checkers since it wasn't there before and the page was empty
> adding description to the type checkers

- content/roadmaps/101-backend/content/110-caching/101-server-side/100-redis.md
- I added a brief description of Redis.
- I added the official website
> Add Resources for Redis

- content/roadmaps/100-frontend/content/118-server-side-rendering/readme.md
upd: Server side rendering doc
> doc: Server side rendering

- content/roadmaps/101-backend/content/102-os-general-knowledge/107-io-management.md
- [*] Backend Roadmap
- [ *] I have read the [contribution docs](../contributing) before opening this PR.
Currently there are no resources for IO management. While I studing I've found some resources useful. So I've added them in this PR.
> Resources added for IO management

- content/roadmaps/101-backend/content/108-more-about-databases/104-database-normalization.md
> Add Database normalization description and ref

- public/project/intro.json
Just fixed spelling of 'initd'
> initd spelling

- content/roadmaps/101-backend/content/110-caching/101-server-side/readme.md
> Resources added for Server side

- content/roadmaps/100-frontend/content/101-html/105-seo-basics.md
The article talks about the SEO best practices and the importance of Clean Code, Site Architecture, Correct Title Tag, Meta Description, Optimized URLs, Meta Robot Tags, Structured Data, internal linking, Page Loading Speed, Website Responsiveness, and Security. which all of these play a crucial part from an SEO perspective for a developer.
> 8 Must Know SEO Best Practices For Developers

- content/roadmaps/100-frontend/content/121-mobile-applications/100-react-native.md
I wasn't comfortable following the react native documentation when I was starting out as a web developer (even after learning javascript). this free react native course from udemy was my go-to guide to dive deep into react native basics. After playing with the basic knowledge you will acquire from this course then you'll be able to dive deep into react native documentation. This course structure follows a learn-by-build format. so you'll not be bored yet you'll be excited to build your first react native app ever.
> A Concrete Guide to React Native basics

- content/roadmaps/101-backend/content/122-web-servers/readme.md
wrote a simple intro about webservers with help from the mdn docs and included a link there also with a youtube video which is pretty good
> Web servers intro, got most help from the mdn docs

- content/roadmaps/100-frontend/content/118-server-side-rendering/101-angular/100-universal.md
Adding description for angular universal.
> Update 100-universal.md - angular universal description

- content/roadmaps/101-backend/content/109-apis/106-authentication/105-openid.md
> Resources added for Open ID

- content/roadmaps/100-frontend/content/100-internet/101-what-is-http.md
The file has been updated by adding a reading point to the free content.
> Added a reading point

- content/roadmaps/101-backend/content/111-web-security-knowledge/108-owasp.md
Correction to the original https://github.com/kamranahmedse/developer-roadmap/pull/1174
> OWASP Security Risks: update link to official Github org

- .github/workflows/deploy.yml
I have not discussed this in issues yet, but it's just a simple typo fix in the Github workflow file.
> Fixed typo in Github workflow

- content/roadmaps/101-backend/content/118-containerization/100-docker.md
Since roadmap.sh tries to filter out non-essential stuff, I thought a short animated summary of Docker would be a good addition to the 2-hour masterclass that's already listed.
> Add animated summary of Docker

- content/roadmaps/101-backend/content/109-apis/100-rest.md
> add learn restfull api tutorial

- content/roadmaps/101-backend/content/109-apis/readme.md
Add API brief description in Backend Roadmap
> Add API brief description

- content/roadmaps/100-frontend/content/103-javascript/102-learn-fetch-api-ajax-xhr.md
Talks about the **JavaScript Fetch API** and **how to use it to make asynchronous HTTP requests**. This post goes through **Sending a Request to Handling the status codes of the Response**. **Extremely beginner-friendly, easy-to-understand examples**.
> A Concrete Guide to JavaScript Fetch API

- content/roadmaps/100-frontend/content/113-web-components/101-custom-elements.md
Add Custom elements guide from MDN web docs
> feat: add custom elements resource

- content/roadmaps/100-frontend/content/113-web-components/102-shadow-dom.md
Add Shadow DOM guide from MDN web docs
> feat: add shadow dom resource

- content/roadmaps/100-frontend/content/103-javascript/102-learn-fetch-api-ajax-xhr.md
Fixed typo and corrected sentence.
> Fix : typo

- content/roadmaps/100-frontend/content/101-html/102-forms-and-validations.md
Add new resource for learning form by [web.dev](https://web.dev/)
> feat: add web.dev learning form course

- content/roadmaps/100-frontend/content/113-web-components/100-html-templates.md
Add HTML templates guide from MDN web docs
> feat: add HTML templates resource

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/120-awk.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/121-sed.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/122-grep.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/123-sort.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/126-cat.md
Text Manipulation Tools:
awk - content with syntax and reference links
> Devops Content Update

- content/roadmaps/102-devops/content/102-managing-servers/readme.md
Added content for Managing Servers.
> Add content for managing servers

- content/roadmaps/101-backend/content/103-learn-a-language/105-javascript.md
Hi there! This book has helped me greatly with learning javascript. It is so pleasant to read but highly detailed, eloquently written as the title suggests. The book includes exercises for every chapter, with solutions, multiple projects, and has everything available with its own code sandbox. I have the paperback copy, but I love having all of the extra features with the online version. It is 100% free.
> Add eloquent js to javascript language node.

- content/roadmaps/102-devops/content/103-networking-protocols/readme.md
Add content for networking protocols.
> Add content for networking protocols

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/127-echo.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/132-egrep.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/133-fgrep.md
Text Manipulation Tools:
echo command
> Devops Map - Content

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/128-fmt.md
Text Manipulation Tools:
fmt content
> Devops Map Content - Text Manipulation Tools

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/100-consul.md
> Add content for consul

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/101-istio.md
> Add content for istio

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/readme.md
> Add content for service mesh

- content/roadmaps/102-devops/content/103-networking-protocols/103-https.md
> Devops Map content - https

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/102-envoy.md
> Add content for envoy

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/103-linkerd.md
> Add content for linkerd

- components/icons/tree.svg
- components/md-renderer/mdx-components/dedicated-roadmap.tsx
- components/md-renderer/mdx-components/index.tsx
- components/roadmap/content-drawer.tsx
- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/readme.md
- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/readme.md
- content/roadmaps/100-frontend/content/111-pick-a-framework/102-vue-js/readme.md
- content/roadmaps/101-backend/content/103-learn-a-language/100-go.md
- content/roadmaps/101-backend/content/103-learn-a-language/102-java.md
- content/roadmaps/101-backend/content/103-learn-a-language/106-python.md
We don't have the roadmap nodes linking to each other. This PR makes it easy to link roadmaps to each other.
> Add dedicated roadmap alert on the roadmap nodes

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/101-smtp.md
> Add content for smtp

- content/roadmaps/102-devops/content/105-infrastructure-as-code/102-configuration-management/readme.md
Add content for configuration management page.
> Add content for configuration management

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/107-iostat.md
> Add content for iostat

- content/roadmaps/109-java/content/102-java-build-tools/101-maven.md
Added some materials to Maven node in Java interactive roadmap.
> (Java Interactive roadmap) Add some Maven materials

- content/roadmaps/109-java/content/103-java-web-frameworks/100-sprint.md
Added official site docs and some useful guides about Spring
> (Java interactive roadmap) Add some resources to Spring node

- content/roadmaps/106-javascript/content/100-javascript-introduction/100-what-is-javascript.md
basic JavaScript description on "What is javascript ?" page.
> JavaScript description

- content/roadmaps/110-java/content/107-testing-java-apps/104-junit.md
Added some resources about JUnit testing.
> (Java Interactive roadmap) Add some JUnit resources

- content/roadmaps/103-react/content/102-react-ecosystem/100-routers/100-react-router.md
I found this tutorial helpful for react router v6, thought it's worth sharing!
> Updated Watch link for React Router v6

- content/roadmaps/101-backend/content/109-apis/106-authentication/readme.md
Add content into Backend-developer-roadmap -> Learn about APIs -> Authentication
> Add Content into Backend-Developer-Roadmap

- content/roadmaps/110-java/content/100-java-fundamentals/readme.md
Hello! Added several books to the fundamental java roadmap resources. All books have been read by me personally. The list was compiled together with practicing java developers. These books are complete and comprehensive for learning the basic concepts of the language. Thanks a lot!
> Add books to Java Roadmap Fundamentals

- content/guides/proxy-servers.md
> Found Grammatical Errors

- content/pages/about.md
> Found Grammatical Error

- readme.md
Updated the URL for node.js roadmap on Readme file. 
PS: This is my very first open source contribution.
> update the URL for node js roadmap on readme file

- content/roadmaps/106-javascript/content/103-javascript-type-casting/readme.md
> 2 more resource added

- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/readme.md
- Update JavaScript expressions and operators
> Update  108-javascript-expressions-and-operators

- contributing/readme.md
> Update Grammar Mistake

- content/roadmaps/106-javascript/content/102-javascript-datatypes/101-object/readme.md
Objects in javascript brief definition + free resources links (mdn, w3school, javascript.info, geekforgeeks).
> Object definition + free resources

- content/roadmaps/106-javascript/content/100-javascript-introduction/readme.md
Recommended because it's a very thorough and excellently written free, full-length textbook on JS. It's one of the resources that I most frequently saw mentioned when I was looking up how to learn JS, and it's the one that has helped me the most.
> Add Eloquent JavaScript book to JS roadmap

- content/roadmaps/100-frontend/content/103-javascript/readme.md
Recommended because it's a very thorough and excellently written free, full-length textbook on JS. It's one of the resources that I most frequently saw mentioned when I was looking up how to learn JS, and it's the one that has helped me the most.
> Add Eloquent JavaScript book to front end roadmap

- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/100-assignment-operators.md
Short intro + free reading resources
> Assignment operator + free Resources

- content/roadmaps/108-python/content/105-python-package-managers/readme.md
niche package managers added as a mentions
> adds poetry, and pipx

- content/roadmaps/106-javascript/content/112-javascript-asynchronous-javascript/104-promises/readme.md
I just added a description of JavaScript promises in addition to a couple of links where the concept is detailed comprehensively.
> Description of JavaScript Promises in JavaScript Roadmap

- content/roadmaps/100-frontend/content/101-html/readme.md
This is my first open-source contribution. I hope I did everything right and I look forward to contributing more. Thank you!
> Added a course to HTML main node

- content/roadmaps/108-python/content/106-python-frameworks/100-synchronous/101-flask.md
Based on https://github.com/kamranahmedse/developer-roadmap/issues/985
> Added Official Tutorial for Flask

- content/roadmaps/100-frontend/content/110-build-tools/100-task-runners/readme.md
Recommendations of taks runners (npm scripts & gulp)
> Recommendations of taks runners

- readme.md
Added contributors graph to the README.md at footer
> Add Contributors Graph

- content/roadmaps/109-golang/content/108-go-testing-your-apps.md
Put a little description and some free content.
> Add content: Go testing your apps

- content/roadmaps/110-java/content/100-java-fundamentals/100-basic-syntax.md
Basic Syntax - Proposed a G2G blog post as read and an intro to java syntax youtube video as watch.
> Added resources for the Java fundamantals

- content/roadmaps/110-java/content/100-java-fundamentals/108-exception-handling.md
Including a brief summary of the node and some interesting links to read and watch
> Added Resources for the Java Fundamentals

- content/roadmaps/106-javascript/content/115-javascript-modules/readme.md
Added resouces of javascript.info it covers complete picture of modules like what is module and how to use import, export and dynamic imports.
> Add modules resources

- content/roadmaps/112-blockchain/content/105-blockchain-security/101-tools/readme.md
> Fix typo in 101-tools/readme.md

- content/roadmaps/100-frontend/content/101-html/100-learn-the-basics.md
- content/roadmaps/100-frontend/content/101-html/readme.md
- content/roadmaps/100-frontend/content/103-javascript/104-concepts.md
I found something wrong with the color tag. So I fixed it. @kamranahmedse
> Fixed the Tag Color

- content/roadmaps/110-java/content/103-java-web-frameworks/101-spring-boot.md
> add spring boot content

- content/roadmaps/103-react/content/102-react-ecosystem/101-ssr/100-next-js.md
I found one best playlist that covers almost all the topics of Nextjs in a very short time, so sharing it here!
> Added Course playlist

- content/roadmaps/101-backend/content/109-apis/103-grpc.md
- content/roadmaps/101-backend/content/109-apis/105-open-api-spec.md
- content/roadmaps/101-backend/content/109-apis/106-authentication/103-token-authentication.md
- content/roadmaps/101-backend/content/109-apis/106-authentication/104-jwt.md
- content/roadmaps/101-backend/content/110-caching/101-server-side/101-memcached.md
- content/roadmaps/101-backend/content/111-web-security-knowledge/102-bcrypt.md
- content/roadmaps/101-backend/content/114-design-and-development-principles/101-domain-driven-design.md
- content/roadmaps/101-backend/content/114-design-and-development-principles/103-solid.md
- content/roadmaps/101-backend/content/115-architectural-patterns/102-soa.md
- content/roadmaps/101-backend/content/115-architectural-patterns/103-cqrs.md
- content/roadmaps/101-backend/content/119-graphql/100-apollo.md
- content/roadmaps/101-backend/content/119-graphql/readme.md
- content/roadmaps/101-backend/content/123-scalability/103-horizontal-vertial-scaling.md
There are some errors in color implementation in tags, so I fixed them. @kamranahmedse
> Backend Color Codes Fixed

- content/roadmaps/101-backend/content/100-internet/readme.md
- content/roadmaps/101-backend/content/101-basic-frontend/101-css.md
- content/roadmaps/101-backend/content/102-os-general-knowledge/100-terminal-usage.md
- content/roadmaps/101-backend/content/102-os-general-knowledge/101-how-oss-work-in-general.md
- content/roadmaps/101-backend/content/102-os-general-knowledge/104-basic-terminal-commands.md
- content/roadmaps/101-backend/content/103-learn-a-language/102-java.md
- content/roadmaps/101-backend/content/103-learn-a-language/103-csharp.md
- content/roadmaps/101-backend/content/103-learn-a-language/105-javascript.md
- content/roadmaps/101-backend/content/103-learn-a-language/106-python.md
- content/roadmaps/101-backend/content/103-learn-a-language/107-ruby.md
- content/roadmaps/101-backend/content/104-version-control-systems/100-basic-usage-of-git.md
- content/roadmaps/101-backend/content/104-version-control-systems/readme.md
- content/roadmaps/101-backend/content/105-repo-hosting-services/102-bitbucket.md
- content/roadmaps/101-backend/content/106-relational-databases/100-postgresql.md
- content/roadmaps/101-backend/content/106-relational-databases/101-mysql.md
- content/roadmaps/101-backend/content/106-relational-databases/102-mariadb.md
- content/roadmaps/101-backend/content/106-relational-databases/103-mssql.md
- content/roadmaps/101-backend/content/106-relational-databases/104-oracle.md
- content/roadmaps/101-backend/content/106-relational-databases/readme.md
- content/roadmaps/101-backend/content/107-nosql-databases/100-document-databases.md
- content/roadmaps/101-backend/content/108-more-about-databases/101-acid.md
- content/roadmaps/101-backend/content/108-more-about-databases/103-n-plus-one-problem.md
- content/roadmaps/101-backend/content/108-more-about-databases/108-cap-theorem.md
There is some typos and codes error. I fixed this. @kamranahmedse
> Backend Typos Fixed

- content/roadmaps/100-frontend/content/121-mobile-applications/100-react-native.md
@kamranahmedse There is a duplicate link of youtube present in the file. So, I removed it.
Here is the issue link raised. 
https://github.com/kamranahmedse/developer-roadmap/issues/1620
Please kindly close this issue.
> Duplicate Tutorial Link

- content/roadmaps/102-devops/content/105-infrastructure-as-code/101-containers.md
This YouTube playlist about containers is mindblowing. It starts off with basics and then dives into more advanced topics.
> Added  a new resource to DevOps

- content/roadmaps/100-frontend/content/110-build-tools/102-linters-formatters/100-prettier.md
- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/100-rxjs.md
There are some typos in the Frontend (Pick A Framework [Angular] Section) so I fixed this. @kamranahmedse
> Frontend pick a framework angular

- content/roadmaps/107-nodejs/content/100-nodejs-introduction/102-history-of-nodejs.md
> 102 history of node js

- content/roadmaps/107-nodejs/content/100-nodejs-introduction/100-what-is-nodejs.md
i did write comprehensive introduction related node js and attach link some of official sites and youtube for understand nodejs.
> comprehensive introduction of node js in (100 what is nodejs)

- content/roadmaps/100-frontend/content/114-css-frameworks/114-css-first/101-bulma.md
There are some typos in Frontend (CSS Frameworks [CSS First] Section) so I fixed this. @kamranahmedse
> Frontend CSS Frameworks CSS First Typos-Fixed

- content/roadmaps/100-frontend/content/113-web-components/readme.md
There are some typos in Frontend (Web Frameworks Section) so I fixed this. @kamranahmedse
> Frontend Web Framework Typos-Fixed

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/103-pop3s.md
- Add a description for pop3s
- Add a read link as more reference material
> (Docs) 103-pop3s: Adding A Content

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/102-imaps.md
- Add a description for **imaps**
- Add some links as a resources
> (Docs) 102-imaps: Adding A Content

- content/roadmaps/100-frontend/content/109-css-preprocessors/100-sass.md
- content/roadmaps/100-frontend/content/109-css-preprocessors/101-postcss.md
- content/roadmaps/100-frontend/content/109-css-preprocessors/102-less.md
There are some typos in Frontend (CSS Preprocessors Section) so I fixed this. @kamranahmedse
> Frontend CSS-Preprocessors Typos-Fixed

- content/roadmaps/100-frontend/content/107-package-managers/100-npm.md
- content/roadmaps/100-frontend/content/107-package-managers/readme.md
There are some typos in Frontend (Package Managers Section) so I fixed this. @kamranahmedse
> Frontend Package-Managers Typos-Fixed

- content/roadmaps/100-frontend/content/105-repo-hosting-services/101-gitlab.md
- content/roadmaps/100-frontend/content/105-repo-hosting-services/102-bitbucket.md
- content/roadmaps/100-frontend/content/105-repo-hosting-services/readme.md
There are some typos in Frontend (Repo Hosting Services Section) so I fixed this. @kamranahmedse
> Frontend Repo-Hosting-Services Typos-Fixed

- content/roadmaps/102-devops/content/100-language/100-python.md
- content/roadmaps/102-devops/content/100-language/101-ruby.md
- content/roadmaps/102-devops/content/100-language/102-javascript.md
- content/roadmaps/102-devops/content/100-language/103-go.md
There are some typos in DevOps (Language Section) so I fixed this. @kamranahmedse
> Devops Language Typos Fixed

- content/roadmaps/100-frontend/content/100-internet/100-how-does-the-internet-work.md
- content/roadmaps/100-frontend/content/100-internet/103-dns-and-how-it-works.md
- content/roadmaps/100-frontend/content/100-internet/readme.md
There are some typos in Frontend (Internet Section) so I fixed this. @kamranahmedse
> Frontend Internet Typos Fixed

- content/roadmaps/107-nodejs/content/111-nodejs-testing/100-jest.md
Add Jest description and official documentation
> feat: add jest content

- content/roadmaps/107-nodejs/content/110-nodejs-databases/101-document/100-mongoose.md
Add mongoose description and official website documentation
> feat: add mongoose content

- content/roadmaps/110-java/content/100-java-fundamentals/105-oop.md
- content/roadmaps/110-java/content/100-java-fundamentals/106-packages.md
- content/roadmaps/110-java/content/101-java-advanced-topics/106-how-jvm-works.md
- content/roadmaps/110-java/content/101-java-advanced-topics/108-basics-of-threads.md
issue #1529
I've added contents to OOPs, Packages, JVM, Threads in Java Roadmap.
> Added Contents to OOPs, Packages, JVM, Threads in Java Roadmap #1529

- content/roadmaps/107-nodejs/content/105-nodejs-working-with-files/102-process-cwd.md
short defination of process-cwd added in nodejs roadmap
> 102-process-cwd added in nodejs

- content/roadmaps/107-nodejs/content/105-nodejs-working-with-files/101-path-module.md
101 path module short description and functions
> 101 path module

- content/roadmaps/100-frontend/content/101-html/104-accessibility.md
- content/roadmaps/100-frontend/content/101-html/readme.md
- content/roadmaps/100-frontend/content/117-progressive-web-apps/101-performance.md
- content/roadmaps/100-frontend/content/118-server-side-rendering/100-react-js/readme.md
- content/roadmaps/100-frontend/content/118-server-side-rendering/102-vue-js/readme.md
- content/roadmaps/100-frontend/content/120-static-site-generators/107-eleventy.md
- content/roadmaps/101-backend/content/100-internet/100-how-does-the-internet-work.md
- content/roadmaps/101-backend/content/101-basic-frontend/100-html.md
- content/roadmaps/101-backend/content/102-os-general-knowledge/108-posix-basics.md
- content/roadmaps/101-backend/content/105-repo-hosting-services/100-github.md
- content/roadmaps/101-backend/content/107-nosql-databases/100-document-databases.md
- content/roadmaps/101-backend/content/109-apis/100-rest.md
- content/roadmaps/101-backend/content/109-apis/101-json-apis.md
- content/roadmaps/101-backend/content/109-apis/102-soap.md
- content/roadmaps/101-backend/content/110-caching/101-server-side/101-memcached.md
There are some typos in Frontend and Backend so I fixed this. @kamranahmedse. Now I have raised one PR. Let me know if it is okay now.
> Frontend Backend Typos Fixed

- content/roadmaps/106-javascript/content/112-javascript-asynchronous-javascript/101-set-timeout.md
> javascript roadmap - add content to javascript  asynchronous setTimeout

- content/roadmaps/106-javascript/content/104-javascript-data-structures/100-indexed-collections/100-arrays.md
Add in description content for JavaScript arrays.
> Add content to JavaScript data structures subsection 100-arrays

- content/roadmaps/112-blockchain/content/103-smart-contracts/100-programming-languages/100-solidity.md
Its a 32-hour course by Patrick Collins on freecodecamp's youtube channel
> Add video tutorial for solidity

- content/roadmaps/102-devops/content/100-language/100-python.md
- content/roadmaps/102-devops/content/100-language/102-javascript.md
- content/roadmaps/102-devops/content/100-language/103-go.md
- content/roadmaps/102-devops/content/101-os-concepts/105-sockets.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/101-centos.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/103-suse-linux.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/104-rhel.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/105-fedora.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/106-debian.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/107-free-bsd.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/108-open-bsd.md
- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/109-net-bsd.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/100-screen-multiplexer.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/101-tmux-multiplexer.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/102-ps.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/102-top.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/103-htop.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/104-atop.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/105-lsof.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/106-nmon.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/107-iostat.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/121-sed.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/122-grep.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/123-sort.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/124-cut.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/125-uniq.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/126-cat.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/129-tr.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/130-nl.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/131-wc.md
There are some typos in DevOps so I fixed this. @kamranahmedse
> Devops Typos Fixed

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/104-dmarc.md
- Add a description for dmarc
- Add some links as a resources
> (Docs) 104-dmarc: Adding a content

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/111-mtr.md
- Add a description for mtr
- Add some links as a resources
> (Docs) 111-mtr: Adding a content

- content/roadmaps/106-javascript/content/100-javascript-introduction/101-history-of-javascript.md
- content/roadmaps/106-javascript/content/100-javascript-introduction/103-how-to-run-javascript.md
- content/roadmaps/106-javascript/content/101-javascript-variables/100-variable-declarations/readme.md
- content/roadmaps/106-javascript/content/101-javascript-variables/101-hoisting.md
- content/roadmaps/106-javascript/content/101-javascript-variables/readme.md
- content/roadmaps/106-javascript/content/102-javascript-datatypes/101-object/100-prototype.md
- content/roadmaps/106-javascript/content/104-javascript-data-structures/100-indexed-collections/100-arrays.md
- content/roadmaps/106-javascript/content/106-javascript-loops-iterations/103-for-statement.md
- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/102-arithmetic-operators.md
- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/103-bitwise-operators.md
- content/roadmaps/106-javascript/content/109-javascript-functions/105-scope-and-function-stack/100-recursion.md
- content/roadmaps/106-javascript/content/109-javascript-functions/105-scope-and-function-stack/101-lexical-scoping.md
- content/roadmaps/106-javascript/content/109-javascript-functions/105-scope-and-function-stack/102-closures.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/readme.md
- content/roadmaps/106-javascript/content/112-javascript-asynchronous-javascript/104-promises/readme.md
- content/roadmaps/106-javascript/content/114-javascript-iterators-and-generators.md
* Added Arithmetic & Bitwise Operators in JS roadmap - https://github.com/kamranahmedse/developer-roadmap/issues/1838
* Rectified typos in existing markdown files
> Adding Arithmetic & Bitwise operators - JS roadmap

- content/roadmaps/114-software-architect/content/104-programming-languages/105-dotnet-framework.md
Add Dotnet Description and documentation reference.
> 105  Add Dotnet Description

- content/roadmaps/113-qa/content/100-qa-basics/102-testing-approaches/101-gray-box-testing.md
Gray Box Testing description and link added.
> Updated Gray Box Testing

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/105-editors.md
Added basic description and references for Vim / Nano / PowerShell / Emacs
> Added content to 105-editors.md

- content/roadmaps/107-nodejs/content/104-nodejs-async-programming/107-set-immediate.md
Added docs for Node.js asyn programming: setImmediate
> Node.js 107: setImmediate function

- content/roadmaps/101-backend/content/101-basic-frontend/102-javascript.md
- content/roadmaps/114-software-architect/content/104-programming-languages/101-python.md
- content/roadmaps/114-software-architect/content/104-programming-languages/102-ruby.md
- content/roadmaps/114-software-architect/content/104-programming-languages/103-go.md
- content/roadmaps/114-software-architect/content/104-programming-languages/104-javascript-typescript.md
- content/roadmaps/114-software-architect/content/104-programming-languages/105-dotnet-framework.md
Hello, first pull requests here,
Changes i've made:
- Added Python resources;
- Added Ruby resources;
- Added Go resources;
- Added JavaScript/TypeScript resources;
- Fixed some typos in the .NET node and also added  the official website to the resources;
- Added the JavaScript dedicated roadmap on the node of JavaScript from backend roadmap.
I have a question too, it's best to make multiple commit's or put everything into a single commit? i will take it into mind for the next pull request.
Thanks.
> Add programming languages resources to architect roadmap

- content/roadmaps/101-backend/content/118-containerization/101-rkt.md
- content/roadmaps/101-backend/content/118-containerization/102-lxc.md
Updated Details in developer-roadmap/tree/master/content/roadmaps/101-backend/content/118-containerization/101-rkt.md and developer-roadmap/tree/master/content/roadmaps/101-backend/content/118-containerization/102-lxc.md
> Added details about RKT and LXC

- content/roadmaps/114-software-architect/content/101-architect-responsibilities.md
- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/104-acid-cap-theorem.md
- content/roadmaps/114-software-architect/content/110-apis-and-integrations/100-grpc.md
- content/roadmaps/114-software-architect/content/115-operations-knowledge/104-service-mesh.md
Added Service Mesh, ACID Cap Theorem, gRPC & updated Architect Responsibilities
> Added Service Mesh & ACID Cap Theorem 

- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/100-is-loosely-equal.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/101-is-strictly-equal.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/102-same-value-zero.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/103-same-value.md
Added content in equality algorithms to the JavaScript roadmap.
> Add content in equality algorithms to JavaScript roadmap

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/116-tcpdump.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/142-ufw.md
This PR adds resources for some more CLI tools mentioned in the DevOps roadmap.
I'd like this to be one of my Hacktoberfest PRs
Links to #1885
> Add missing Devops CLI utilities resources

- content/roadmaps/104-angular/content/106-forms/100-reactive-forms.md
- content/roadmaps/104-angular/content/106-forms/101-template-driven-forms.md
- content/roadmaps/104-angular/content/106-forms/readme.md
I have added content on the topic of FORMS in ANGULAR ROADMAP. This content is part of the issue raised by @kamranahmedse having the link below.
https://github.com/kamranahmedse/developer-roadmap/issues/1847
@kamranahmedse Please review this PR (Pull Request) and label this PR as "HACTOBERFEST-ACCEPTED".
> Add content to Angular Roadmap - Forms

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/106-compiling-apps.md
- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/137-uname.md
Add Content For DevOps Roadmap for 106-compiling-apps.md
> Added basic description for GCC,Make etc

- content/roadmaps/106-javascript/content/106-javascript-loops-iterations/102-break-continue/readme.md
- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/105-bigint-operators.md
- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/107-conditional-operators.md
Issue #1838 
Added content to:
- Conditional Operators
- BigInt Operators
- Break / Continue Statements
> Add descriptions to JavaScript Conditional Operators, BigInt Operators, and Break Continue statements

- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/100-default-params.md
- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/101-rest-params.md
- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/readme.md
If this is merged I will be sure to do more.
> Added MDN Docs links to rest and default parameters readme file following the guidelines

- content/roadmaps/106-javascript/content/103-javascript-type-casting/101-explicit-type-casting.md
With the reference of the issue https://github.com/kamranahmedse/developer-roadmap/issues/1838. I've added the following contents in the Javascript Roadmap
@kamranahmedse
Contents for : Explicit type casting
> Updated 101-explicit-type-casting.md

- content/roadmaps/104-angular/content/102-angular-basics/100-angularjs-vs-angular.md
- content/roadmaps/104-angular/content/102-angular-basics/101-angular-components.md
- content/roadmaps/104-angular/content/102-angular-basics/102-angular-templates.md
- content/roadmaps/104-angular/content/102-angular-basics/103-angular-modules.md
I have added content on the topic of UNDERSTANDING BASICS in ANGULAR ROADMAP. This content is part of the issue raised by @kamranahmedse having the link below.
https://github.com/kamranahmedse/developer-roadmap/issues/1847
@kamranahmedse Please review this PR (Pull Request) and label this PR as "HACTOBERFEST-ACCEPTED".
> Add content to Angular Roadmap - Understanding Basics

- content/roadmaps/107-nodejs/content/102-nodejs-npm/101-global-install-vs-local-install.md
> Contribute to NodeJS documentation

- content/roadmaps/113-qa/content/103-qa-automated-testing/102-backend-automation/104-rest-assured.md
Add content for REST-assured for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: REST-assured

- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/100-is-loosely-equal.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/101-is-strictly-equal.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/102-same-value-zero.md
- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/103-same-value.md
- content/roadmaps/110-java/content/102-java-build-tools/102-ant.md
- content/roadmaps/110-java/content/103-java-web-frameworks/103-spark.md
- content/roadmaps/110-java/content/105-java-logging-frameworks/100-log4j2.md
- content/roadmaps/110-java/content/105-java-logging-frameworks/101-logback.md
- content/roadmaps/110-java/content/105-java-logging-frameworks/102-slf4j.md
- content/roadmaps/110-java/content/105-java-logging-frameworks/103-tinylog.md
I have added a few topics in Java but in this merge, my previous javascript contribution is also being added.
> Updated few Topics in Java and JavaScript

- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/101-non-functional-testing/stress-testing.md
Added content for Stress testing for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Stress Testing

- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/101-non-functional-testing/performance-testing.md
Added content for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Performance Testing

- content/roadmaps/110-java/content/100-java-fundamentals/104-datastructures.md
There are very few resources in the java roadmap so, I tried to add a new and best resource for dsa in java which will be really helpful for students. Done according to the issue number:  #1837 , please mark this pr as hacktoberfest-accepted.
> Added one of the best and new resource to the java datastructures list

- content/roadmaps/113-qa/content/111-qa-headless-testing/readme.md
- Description of headless testing
- Example cases of when one would use headless testing
> Add: Headless Testing

- content/roadmaps/106-javascript/content/106-javascript-loops-iterations/102-break-continue/100-labeled-statements.md
I'm new to contributions hope this was helpful.
> Added Mdn Source

- content/roadmaps/107-nodejs/content/100-nodejs-introduction/readme.md
...developer-roadmap/content/roadmaps/107-nodejs/content/100-nodejs-introduction/readme.md file updated with the appropriate guidelines.
> Node.js Introduction updated

- content/guides/what-is-internet.md
Updated what-is-internet.md so the first paragraph reads a bit easier.
> Minor text changes to what-is-internet.md

- content/roadmaps/101-backend/content/123-scalability/100-mitigation-strategies.md
- Added basic description of throttling
- Added basic h2 for additional migration strategies mentioned on the map
> Add: Throttling. 100-migration-strategies.md

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/100-white-grey-listing.md
Added missing content to 100-white-grey-listing.md
> Add missing content to DevOps node

- content/roadmaps/106-javascript/content/117-javascript-chrome-dev-tools/100-debugging-issues.md
- content/roadmaps/106-javascript/content/117-javascript-chrome-dev-tools/101-debugging-memory-leaks.md
- content/roadmaps/106-javascript/content/117-javascript-chrome-dev-tools/102-debugging-performance.md
- content/roadmaps/106-javascript/content/117-javascript-chrome-dev-tools/readme.md
> feat: add Chrome Dev Tools content to the JavaScript roadmap

- content/roadmaps/104-angular/content/107-routing/105-lazy-loading.md
- content/roadmaps/104-angular/content/107-routing/readme.md
- content/roadmaps/104-angular/content/108-services-remote-data/100-dependency-injection.md
- content/roadmaps/104-angular/content/108-services-remote-data/readme.md
- content/roadmaps/104-angular/content/109-lifecycle-hooks.md
- content/roadmaps/104-angular/content/110-state-management/100-ngxs.md
- content/roadmaps/104-angular/content/110-state-management/101-ngrx.md
- content/roadmaps/104-angular/content/110-state-management/readme.md
I am adding the content roadmap of angular in this PR I added the following topics
What is State management ?
Why use Lifecycle hooks of angular ?
What is Ngxs ?
What is Ngrx ?
What is Services remote data ?
What is Lazy loading ?
What is Routing in angular ?
What is Dependency injection in angular ?
> Pr hacktober fest angular content state management

- content/roadmaps/107-nodejs/content/104-nodejs-async-programming/103-async-await.md
Added content for Async-Await in **Nodejs roadmap**.
> Add Async-Await

- content/roadmaps/102-devops/content/107-monitoring/100-infrastructure-monitoring/102-monit.md
content for infrastructure monitoring devops roadmap.
> Adding Monit Content to Devops Roadmap

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/readme.md
Added content for Load and Performance Test for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Load and Performance Test

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/101-jmeter.md
Added more contents to JMeter.
> Add JMeter

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/106-lighthouse.md
Add content for Lighthouse for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Lighthouse

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/100-vegeta.md
Add content for Vegeta for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: vegeta

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/105-artillery.md
Added content for Artillery for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Artillery

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/102-locust.md
Added content for Locust for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Locust

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/100-load-and-performance-testing/103-gatling.md
Added content for Gatling for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Gatling

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/102-automation-frameworks/jasmine.md
- Added basic content and useful tutorial for QA Automation Jasmine framework.
> (#1840) Add basic content for QA-Automation-Jasmine.

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/100-selenium-ide.md
- content/roadmaps/113-qa/content/108-qa-vcs/100-git.md
SeleniumIDE for automated frontend testing, Git for version control. Added links and basic tutorials for each.
> Update SeleniumIDE and Git for QA Roadmap

- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/106-string-operators.md
- content/roadmaps/106-javascript/content/109-javascript-functions/104-arguments-object.md
I added string operators basic info and two links to some docs: MDN and JavaScript.info
> String operators

- content/roadmaps/104-angular/content/103-angular-cli/100-ng-build.md
- content/roadmaps/104-angular/content/103-angular-cli/101-ng-serve.md
- content/roadmaps/104-angular/content/103-angular-cli/102-ng-generate.md
- content/roadmaps/104-angular/content/103-angular-cli/103-ng-test.md
- content/roadmaps/104-angular/content/103-angular-cli/104-ng-e2e.md
- content/roadmaps/104-angular/content/103-angular-cli/105-ng-new.md
- content/roadmaps/104-angular/content/103-angular-cli/readme.md
I am adding the content roadmap of angular in this PR I added the following topics
What is Angular CLI ?
Why Ng build ?
What is Ng serve ?
What is Ng generate ?
What is Ng test ?
What is Ng new ?
What is Ng e2e ?
> adding content to angular roadmap - angular cli

- content/roadmaps/106-javascript/content/109-javascript-functions/104-arguments-object.md
I have updated the arguments.object.md with data and link to mdn docs
> Adding arguments-object

- content/roadmaps/101-backend/content/107-nosql-databases/101-column-databases.md
I belive that the original author mistook ["columnar databases" with "coloumn databases"](https://en.wikipedia.org/wiki/Wide-column_store#Wide-column_stores_versus_columnar_databases)
> Fix mistakes and add content to column databases

- content/roadmaps/104-angular/content/102-angular-basics/104-dependency-injection.md
I have added content in Dependency Injection on the topic of UNDERSTANDING BASICS in ANGULAR ROADMAP. This content is part of the issue raised by @kamranahmedse having the link below.
https://github.com/kamranahmedse/developer-roadmap/issues/1847
@kamranahmedse Please review this PR (Pull Request) and label this PR as "HACTOBERFEST-ACCEPTED".
> Add content to Angular Roadmap - Basics - Dependency Injection

- content/roadmaps/109-golang/content/104-go-web-frameworks/100-beego.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/101-gin.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/102-revel.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/103-echo.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/104-gorilla.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/105-gofiber.md
- content/roadmaps/109-golang/content/104-go-web-frameworks/106-buffalo.md
- content/roadmaps/114-software-architect/content/109-working-with-data/101-etl-datawarehouses.md
- content/roadmaps/114-software-architect/content/109-working-with-data/103-analytics/100-apache-spark.md
- content/roadmaps/114-software-architect/content/109-working-with-data/103-analytics/101-hadoop.md
- content/roadmaps/114-software-architect/content/109-working-with-data/103-analytics/102-datawarehouses-principles.md
- content/roadmaps/114-software-architect/content/112-architect-frameworks/100-babok.md
- content/roadmaps/114-software-architect/content/112-architect-frameworks/101-iaf.md
- content/roadmaps/114-software-architect/content/112-architect-frameworks/101-uml.md
- content/roadmaps/114-software-architect/content/112-architect-frameworks/102-togaf.md
- content/roadmaps/114-software-architect/content/114-networks/100-osi-tcp-ip-model.md
- content/roadmaps/114-software-architect/content/114-networks/101-http-https.md
- content/roadmaps/114-software-architect/content/114-networks/102-proxies.md
- content/roadmaps/114-software-architect/content/114-networks/103-firewalls.md
I have added content for Frameworks, Analytics, and Networks for Software Architect Roadmap. 
Update - 
I have also added some content to GO Roadmap which includes most of the web frameworks
> Added content in Software Architect Roadmap and Go Roadmap

- content/roadmaps/102-devops/content/105-infrastructure-as-code/102-configuration-management/100-ansible.md
Fixed a typo and added a complete video course link.
> Fixed typo and added a video course link

- content/roadmaps/102-devops/content/105-infrastructure-as-code/103-infrastructure-provisioning/101-aws-cdk.md
One of the main features of CDK is its flexibility to code in multiple languages. Added the supported languages in the description.
> Add description for AWS CDK

- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/103-actors.md
- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/105-solid.md
- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/106-ddd.md
- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/106-tdd.md
Add content to the following nodes from Patterns and Design Principles from the Software Architect Roadmap:
- Actors;
- SOLID;
- Domain-Driven Design;
- Test Driven Development.
As per issue #1879.
> add resources to Patterns and Design Principles

- content/roadmaps/106-javascript/content/116-javascript-memory-management/100-memory-lifecycle.md
Added Information about memory life cycle in javascript
according to issue #1838
> Updated Memory Life cycle in javascript

- content/roadmaps/109-golang/content/101-go-advanced/104-context.md
> added content and resources to golang node (context)

- content/roadmaps/106-javascript/content/107-javascript-control-flow/100-exception-handling/102-utilizing-error-objects.md
- Issue #1838 
- Adding content in Javascript roadmap on Utilizing error objects node
> Adding Utilizing error object - JS roadmap

- content/roadmaps/100-frontend/content/111-pick-a-framework/100-react-js/readme.md
The beta React docs contain very thorough descriptions of the many features available in React and are an excellent resource that I believe deserve mention in the roadmap.
> Added beta React docs to the React readme.md

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/134-strace.md
Added some content as a description of strace.
> Adding content to 134-strace.md

- content/roadmaps/110-java/content/100-java-fundamentals/103-functions.md
After the change, BadgeLinks will comply to the rules specified here (https://github.com/kamranahmedse/developer-roadmap/blob/b44b69b4c6119b7849f1410e59474ff3e04b8e77/contributing.md#adding-content)
> Fix BadgeLink colours in Java Functions

- content/roadmaps/113-qa/content/107-qa-monitoring-logs/100-grafana.md
Added Grafana for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: Grafana

- content/roadmaps/113-qa/content/107-qa-monitoring-logs/106-pager-duty.md
Added PagerDuty for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add: PagerDuty

- content/roadmaps/106-javascript/content/111-javascript-this-keyword/107-call-method.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/108-apply-method.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/109-bind-method.md
Issue #1838
With reference to issue #1838 , I've added the following contents to the Javascript Roadmap.
@kamranahmedse
Contents for :
call() method.
apply() method.
bind() method.
@kamranahmedse Please review this PR (Pull Request) and label this PR as "hacktoberfest-accepted".
> creat call-apply-bind-methods readme files

- content/roadmaps/107-nodejs/content/117-nodejs-common-modules/100-builtin-modules.md
- content/roadmaps/107-nodejs/content/117-nodejs-common-modules/readme.md
- Issue: #1839 
- add content on "built-in modules" node in `Node.js` roadmap
- add content on "common built-in modules" node in the `Node.js` roadmap
**please** label this PR as "hacktoberfest-accepted", if it is mergable
> Add content in Node.js roadmap

- content/roadmaps/114-software-architect/content/106-architect-tools/100-git.md
- content/roadmaps/114-software-architect/content/106-architect-tools/101-slack.md
- content/roadmaps/114-software-architect/content/107-architectures/100-serverless.md
- content/roadmaps/114-software-architect/content/110-apis-and-integrations/105-messaging-queues.md
Add content to the following nodes under Software Architect Roadmap:
Git;
Slack;
Serverless;
Messaging Queues.
As per issue https://github.com/kamranahmedse/developer-roadmap/issues/1879.
> Added git, slack, messaging queues, serverless content

- content/roadmaps/104-angular/content/105-rendering-topics/100-builtin-directives.md
- content/roadmaps/104-angular/content/105-rendering-topics/101-builtin-pipes.md
- content/roadmaps/104-angular/content/105-rendering-topics/102-change-detection.md
I am adding the content roadmap of angular in this PR I added the following topics
What is Built-in Directives ?
What is Builtin pipes ?
What is Change detection ?
> add content to rendering topics in angular roadmap

- content/roadmaps/110-java/content/107-testing-java-apps/103-jbehave.md
- content/roadmaps/110-java/content/107-testing-java-apps/105-testng.md
- content/roadmaps/110-java/content/107-testing-java-apps/106-rest-assured.md
Issue https://github.com/kamranahmedse/developer-roadmap/issues/1837
With the reference of the issue https://github.com/kamranahmedse/developer-roadmap/issues/1837, I've added and updated contents in jbehave, testng and rest-assured  in the Java Roadmap. 
@kamranahmedse Please review this PR (Pull Request) and label this PR as "HACTOBERFEST-ACCEPTED".
> Added jbehave,testng and rest-assured content

- content/roadmaps/106-javascript/content/109-javascript-functions/105-scope-and-function-stack/readme.md
- Issue: #1838 
- adding content of the 'scope and function stack' node in Javascript roadmap.
**please** label this PR as "hacktoberfest-accepted".
> Add content on 'scope and function stack' node

- content/roadmaps/100-frontend/content/114-css-frameworks/114-js-first/105-daisy-ui.md
Resolve issue [#2217](https://github.com/kamranahmedse/developer-roadmap/issues/2217)
> Add link to official website and official docs for daisyUI

- content/roadmaps/104-angular/content/101-rxjs-basics/101-observable-lifecycle.md
Added content and resources for Observable Lifecycle
According to issue #2087
> Observable Lifecycle. Update 101-observable-lifecycle.md

- content/roadmaps/104-angular/content/107-routing/101-router-outlets.md
Added content and free resources for router-outlet in angular
According to issue #2087
> Added Content for Router-Outlet in Angular.Update 101-router-outlets.md

- content/roadmaps/109-golang/content/107-go-api-clients/100-rest/readme.md
The tutorial link are specific to Go language
> Added content to Rest in Golang section

- content/roadmaps/100-frontend/content/114-css-frameworks/114-js-first/104-mantine.md
Mantine is a great library of components, I have used and recommend. I've added some official content for anyone who wants to start.
path: content/roadmaps/100-frontend/content/114-css-frameworks/114-js-first/104-mantine.md
@kamranahmedse please label this PR as "hacktoberfest-accepted".
> Add content for Mantine JS first CSS framework

- content/roadmaps/100-frontend/content/101-html/104-accessibility.md
This page introduces some basic considerations to help you get started developing web content that is more accessible to people with disabilities. These tips are good practice to help you meet Web Content Accessibility Guidelines (WCAG) requirements. Follow the links to the related WCAG requirements, detailed background in the “Understanding” document, guidance from Tutorials, user stories, and more.
> Added official resource from W3C's Web Accessibility Initiative

- content/roadmaps/107-nodejs/content/112-nodejs-logging/readme.md
- Issue: #1839 
- add content in content/112-nodejs-logging/readme.md
- Add content of the logging node in the node.js roadmap
please labelled this PR as 'hacktoberfest-completed', If it is able to merge.
> Add content of Logging node

- content/roadmaps/102-devops/content/112-management-and-monitoring.md
- content/roadmaps/110-java/content/104-java-orm/103-ebean.md
- content/roadmaps/110-java/content/104-java-orm/readme.md
- content/roadmaps/110-java/content/106-java-jdbc/100-jdbi3.md
- content/roadmaps/110-java/content/106-java-jdbc/101-jdbc-template.md
- content/roadmaps/110-java/content/107-testing-java-apps/101-cucumber-jvm.md
Fill devops node management and monitoring
> Devops fill nodes

- content/roadmaps/110-java/content/104-java-orm/103-ebean.md
- content/roadmaps/110-java/content/106-java-jdbc/100-jdbi3.md
- content/roadmaps/110-java/content/107-testing-java-apps/101-cucumber-jvm.md
Add content to the following nodes under Java Roadmap:
jdbi3;
cucumber;
ebean;
As per issue https://github.com/kamranahmedse/developer-roadmap/issues/1837.
> Added jdbi3, cucumber, ebean content

- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/100-oop.md
- content/roadmaps/114-software-architect/content/106-architect-tools/102-trello.md
- content/roadmaps/114-software-architect/content/107-architectures/105-service-oriented.md
- content/roadmaps/114-software-architect/content/109-working-with-data/102-sql-databases.md
- content/roadmaps/114-software-architect/content/109-working-with-data/103-nosql-databases.md
Add content to the following nodes under Software Architect Roadmap:
OOP;
SQL Databases;
NoSQL Databases;
Trello;
SOA;
As per issue https://github.com/kamranahmedse/developer-roadmap/issues/1879.
> Added oop, sql, nosql, trello, soa content

- content/roadmaps/113-qa/content/100-qa-basics/105-manage-your-testing/101-test-rail.md
- content/roadmaps/113-qa/content/100-qa-basics/105-manage-your-testing/102-test-link.md
- content/roadmaps/113-qa/content/100-qa-basics/105-manage-your-testing/103-zephyr.md
- content/roadmaps/113-qa/content/100-qa-basics/105-manage-your-testing/readme.md
Update Testing Management Information as well as tools:
- TestRail
- TestLink
- Zephyr
> Update Testing Management Tools

- content/roadmaps/106-javascript/content/107-javascript-control-flow/readme.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/107-call-method.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/108-apply-method.md
- content/roadmaps/106-javascript/content/111-javascript-this-keyword/109-bind-method.md
Issue #1838 
With reference to issue #1838 , I've added the following contents to the Javascript Roadmap.
@kamranahmedse
Contents for :
**added the content on Javscript Control Flow readme.md file.**
@kamranahmedse Please review this PR (Pull Request) and label this PR as "hacktoberfest-accepted".
> update the JavaScript Control flow readme.md file

- content/roadmaps/104-angular/content/104-templates/100-interpolation.md
Added documentation for interpolation
> Added documentation for interpolation

- content/roadmaps/104-angular/content/101-rxjs-basics/104-operators/readme.md
Added Documentation for RxJS Operators
> Added Documentation for RxJS Operators

- content/roadmaps/113-qa/content/101-qa-sdlc/102-agile-model/100-kanban.md
- content/roadmaps/113-qa/content/101-qa-sdlc/102-agile-model/101-scrum.md
- content/roadmaps/113-qa/content/101-qa-sdlc/102-agile-model/102-safe.md
- content/roadmaps/113-qa/content/101-qa-sdlc/102-agile-model/103-xp.md
Update all included Agile Models:
- Kanban
- Scrum
- SAFe
- XP
> Update All Agile Models

- content/roadmaps/114-software-architect/content/111-web-and-mobile/101-react-vue-angular.md
- content/roadmaps/114-software-architect/content/111-web-and-mobile/103-pwa.md
Add content to the following nodes from Web, Mobile from the Software Architect Roadmap:
* React, Vue, Angular;
* PWA.
As per issue #1879 .
> Add content to react, vue, angular and pwa

- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/100-oop.md
- content/roadmaps/114-software-architect/content/105-patterns-and-design-principles/102-cqrs-eventual-consistency.md
In this commit added to the roadmap: 
- Introduction to object-oriented programming.
- Two FreeCodeCamp courses to apply object-oriented programming to python and c++.
- Description of the CQRS architecture pattern.
- Two resources to dive deeper into the CQRS architecture pattern
> added content in Software Arquitect

- content/roadmaps/104-angular/content/103-angular-cli/106-schematics.md
- content/roadmaps/104-angular/content/104-templates/100-interpolation.md
- content/roadmaps/104-angular/content/112-creating-a-custom-x/102-library.md
- content/roadmaps/104-angular/content/113-angular-ssr/100-angular-universal.md
- content/roadmaps/104-angular/content/114-angular-ssg/100-scully.md
- content/roadmaps/104-angular/content/115-testing-angular-apps/100-testing-pipes.md
- content/roadmaps/104-angular/content/115-testing-angular-apps/101-testing-services.md
- content/roadmaps/104-angular/content/115-testing-angular-apps/102-testing-component-bindings.md
- content/roadmaps/104-angular/content/115-testing-angular-apps/103-testing-directives.md
- content/roadmaps/104-angular/content/115-testing-angular-apps/104-testing-component-templates.md
Added content in Angular Roadmap
> Added content in Angular Roadmap

- content/roadmaps/107-nodejs/content/106-nodejs-command-line-apps/102-taking-input/100-process-stdin.md
- content/roadmaps/107-nodejs/content/106-nodejs-command-line-apps/102-taking-input/101-prompts.md
- content/roadmaps/107-nodejs/content/106-nodejs-command-line-apps/102-taking-input/102-inquirer.md
- content/roadmaps/107-nodejs/content/115-nodejs-streams.md
this PR adds content for streams in node.js roadmap #1839
> Update content for streams and taking input

- content/roadmaps/104-angular/content/104-templates/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I made the required additions to this file and resolved the issue.
> Updated readme.md file of 104-templates folder in Angular

- content/roadmaps/102-devops/content/100-language/readme.md
> Fixed typo in readme.md

- content/roadmaps/107-nodejs/content/107-nodejs-apis/101-express-js.md
Resources  added in **Roadmap/Nodejs/express.js**
> Resources added to Nodejs/Express.js

- content/roadmaps/104-angular/content/101-rxjs-basics/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I made the required changes and added the content to the readme.md file in 101-rxjs-basics folder
> Added content for the readme.md file of 101-rxjs-basics

- content/roadmaps/113-qa/content/107-qa-monitoring-logs/readme.md
[#1847](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I added content to the readme.md file of 107-qa-monitoring-logs to resolve this issue! Please check this PR
> Added content to the readme.md file of 107-qa-monitoring-logs

- content/roadmaps/104-angular/content/100-typescript-basics/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I added content to the readme.md file of 100-typescript-basics to resolve this issue
> Added and Updated the readme.md file of 100-typescript-basics folder

- content/roadmaps/102-devops/content/102-managing-servers/100-operating-system/100-windows.md
Updated information about windows on DevOps roadmap.
> Updated info on windows card

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/108-sar.md
Added information about sar command
> Added information about sar command

- content/roadmaps/114-software-architect/content/115-operations-knowledge/103-linux-unix.md
@kamranahmedse   please have a look and suggest changes needed if any.
> [content] Added note on history and use of linux OS.

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/138-df.md
Added information and usage about df command.
> Added information about df command

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/140-du.md
Added information about du command in linux
> Added information about du command

- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/100-functional-testing/exploratory-testing.md
* Update content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/100-functional-testing/exploratory-testing.md
> Adds description for 'exploratory testing'

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/ProgrammerError.md
Added another type of error that can occur in Node Js
> created programmer error file

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/operational errors
Added another type of error that can occur in Node Js
> created operational error file

- content/roadmaps/114-software-architect/content/115-operations-knowledge/102-serverless-concepts.md
Added the missing concept server less  in system architect
> serverless concept

- content/roadmaps/113-qa/content/100-qa-basics/readme.md
[#1840 ](https://github.com/kamranahmedse/developer-roadmap/issues/1840) I added content to readme.md file of 100-qa-basics folder to resolve this issue! Please check this PR
> Updated and Added content to readme.md file of 100-qa-basics folder

- content/roadmaps/114-software-architect/content/103-technical-skills.md
technical skill required for the software architect is being added
> Added technical skills

- content/roadmaps/113-qa/content/106-qa-reporting/100-junit.md
[#1840](https://github.com/kamranahmedse/developer-roadmap/issues/1840) I added the content to 100-junit.md file of the 106-qa-reporting folder to resolve this issue. Please check into this PR!
> Updated and Added the content to 100-junit.md file

- content/roadmaps/104-angular/content/115-testing-angular-apps/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I contributed to this issue by adding the content to the readme.md file of 115-testing-angular-apps folder.
> Added content to the readme.md file of 115-testing-angular-apps

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/readme.md
[#1840 ](https://github.com/kamranahmedse/developer-roadmap/issues/1840) I contributed to this issue by adding content to the readme.md file of 104-qa-non-functional-testing folder.
> Added content to readme.md file of 104-qa-non-functional-testing

- content/roadmaps/107-nodejs/content/116-nodejs-more-debugging/100-memory-leaks/readme.md
also added some free blog links for more information
> Added content on memory leaks, its causes and its detectors

- content/roadmaps/107-nodejs/content/101-nodejs-modules/readme.md
Reverts kamranahmedse/developer-roadmap#2341
> Revert "Removed Nodejs Error"

- content/roadmaps/100-frontend/content/103-javascript/103-es6-and-modular-javascript.md
Added W3Schools resource about ES6
> Added W3Schools resource about ES6

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/102-automation-frameworks/puppeteer.md
added content with free read content
> added content to Puppeteer

- content/roadmaps/106-javascript/content/116-javascript-memory-management/100-memory-lifecycle.md
> added links to memory management docs

- content/roadmaps/104-angular/content/104-templates/101-property-binding.md
- content/roadmaps/104-angular/content/104-templates/102-template-statements.md
- content/roadmaps/104-angular/content/104-templates/103-binding-data-props-attrs-events.md
- content/roadmaps/104-angular/content/104-templates/104-reference-vars.md
- content/roadmaps/104-angular/content/104-templates/105-input-output.md
This PR adds content for templates in Angular
resolves #1847
> Update content for templates in angular

- content/roadmaps/106-javascript/content/104-javascript-data-structures/readme.md
Added basic understanding of data structures with a free-read content
> Added content to data structure readme.md

- content/roadmaps/114-software-architect/content/100-software-architect-basics/101-what-is-software-architect.md
I'd like to contribute a better definition with proper functionality of an Artitect.
> Hi , I'd like to provide an alternative definition to this.

- content/roadmaps/107-nodejs/content/106-nodejs-command-line-apps/102-taking-input/readme.md
> Updated readme.md file of 102-taking-input in Node.js

- content/roadmaps/114-software-architect/content/111-web-and-mobile/100-reactive-functional-programming.md
- content/roadmaps/114-software-architect/content/111-web-and-mobile/102-spa-ssr-ssg.md
- content/roadmaps/114-software-architect/content/111-web-and-mobile/104-microfrontends.md
- content/roadmaps/114-software-architect/content/111-web-and-mobile/105-w3c-and-whatwg-standards.md
this PR adds content in software architect roadmap
resolves #1879
> Update content for web and mobile in software architect

- content/roadmaps/104-angular/content/114-angular-ssg/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I added the required content to the readme.md file in 114-angular-ssg folder to resolve the issue.
> Added content to readme.md file in 114-angular-ssg

- content/roadmaps/104-angular/content/113-angular-ssr/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I added the content to readme.md file of the 113-angular-ssr folder to resolve the issue
> Added content to readme.md file of 113-angular-ssr

- content/roadmaps/104-angular/content/112-creating-a-custom-x/readme.md
[#1847 ](https://github.com/kamranahmedse/developer-roadmap/issues/1847) I made the required addition of content to readme.md file of 112-creating-a-custom-x to resolve the issue.
> Added content to readme.md file of 112-creating-a-custom-x folder

- content/guides/what-is-internet.md
Unlike other topics, cybersecurity and cybercrime didn't have a brief intro, so i added one.
> Added content to what-is-internet.md

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/100-javascript-errors.md
along with free tutorial link and YouTube link
> Added content for JavaScript Error and its types

- content/roadmaps/101-backend/content/103-learn-a-language/106-python.md
Added Python reference read guide link from freecodecamp.org
How to Learn Python?
> Added Python Refrence read guide link.

- content/roadmaps/106-javascript/content/112-javascript-asynchronous-javascript/100-event-loop.md
added a very helpful video resource(youtube video) on the topic of the event loop, please check it out.
> Added video resource(Youtube video) for event loop.

- content/roadmaps/100-frontend/content/101-html/readme.md
- content/roadmaps/100-frontend/content/102-css/readme.md
- content/roadmaps/100-frontend/content/103-javascript/readme.md
1. [htmlreference.io: All HTML elements at a glance](https://htmlreference.io/)
2. [cssreference.io: All CSS properties at a glance](https://cssreference.io/)
3. [Learn JavaScript: Covered many topics](https://www.javascripttutorial.net/)
> Added HTML, CSS & JavaScript content

- content/roadmaps/101-backend/content/123-scalability/104-observability.md
- content/roadmaps/101-backend/content/123-scalability/readme.md
There was no issue related to this content but I just noticed this after I started writing, hope it helps nevertheless.
I added information about observability and scalability into the backend roadmap. I'm actually dealing with those things myself in my current job so I thought of giving it a go as well.
Please label this PR as 'hacktoberfest-accepted', If you think is valuable enough.
> Adding sections about observability and scalability

- content/pages/about.md
Fixed line 54 `contributing` > `contributing.md`
> Update internal URL of contribution

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/100-authentication-authorization.md
- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/101-vulnerability-scanning.md
- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/102-owasp-10.md
- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/103-attack-vectors.md
- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/104-secrets-management.md
- content/roadmaps/113-qa/content/104-qa-non-functional-testing/102-security-testing/readme.md
- content/roadmaps/113-qa/content/107-qa-monitoring-logs/101-new-relic.md
- content/roadmaps/113-qa/content/107-qa-monitoring-logs/102-run-scope.md
- content/roadmaps/113-qa/content/107-qa-monitoring-logs/103-sentry.md
- content/roadmaps/113-qa/content/107-qa-monitoring-logs/104-kibana.md
- content/roadmaps/113-qa/content/107-qa-monitoring-logs/105-data-dog.md
Added content for Monitoting and Logs and Security testing for https://github.com/kamranahmedse/developer-roadmap/issues/1840
> Add monitoring logs

- content/roadmaps/102-devops/content/106-ci-cd/readme.md
Issue #1885
Please review the PR
> CI CD readme documentation added

- content/roadmaps/100-frontend/content/100-internet/103-dns-and-how-it-works.md
- content/roadmaps/100-frontend/content/106-web-security-knowledge/100-https.md
- content/roadmaps/101-backend/content/100-internet/103-dns-and-how-it-works.md
- content/roadmaps/101-backend/content/111-web-security-knowledge/105-https.md
- content/roadmaps/102-devops/content/103-networking-protocols/101-dns.md
- content/roadmaps/102-devops/content/103-networking-protocols/103-https.md
I recently discovered [some cool comics by dnsimple](https://dnsimple.com/comics) that explain in an easy and visual way, how key concepts of the internet, like DNS and HTTPS work. I added them in the respective places.
> Add dnsimple comics

- content/roadmaps/100-frontend/content/103-javascript/readme.md
- content/roadmaps/101-backend/content/103-learn-a-language/105-javascript.md
- content/roadmaps/106-javascript/content/100-javascript-introduction/readme.md
- content/roadmaps/112-blockchain/content/109-dapps/107-supporting-languages/100-javascript.md
This PR adds You Don't Know JS Yet, a book series by Kyle Simpson diving deep into the core mechanisms of the JavaScript language.
The book series is fully available on GitHub for free and has 6 volumes, two of them in its second edition. As the book series touches on a great number of topics about the language, I think it's best to add it to the broadest JavaScript topic in each roadmap.
On that note, this PR adds the book to the following roadmaps:
Related to #2058 (closed)
> Add You Don't Know JS Yet (book series) 

- content/roadmaps/100-frontend/content/110-build-tools/readme.md
There are a lot of others but these seem to be quite stable and not deprecated
> Added some build tools

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/101-using-debugger.md
Issue - Add content to Node.js roadmap https://github.com/kamranahmedse/developer-roadmap/issues/1839
Q - What does this PR cover?
A - Added content in Node.js Roadmap for debugger
> Update content for 101-using-debugger.md

- content/roadmaps/113-qa/content/104-qa-non-functional-testing/101-accessibility-testing/readme.md
content added in 101-accessibility-testing with a free read content
>  added content to 101-accessibility-testing

- content/roadmaps/101-backend/content/103-learn-a-language/103-php.md
- Add a link to PHP: The Right Way website
- Update description of PHP to match the current state
> Update page for PHP

- content/roadmaps/103-react/content/100-react-fundamental-topics/100-create-react-app.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/101-jsx.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/102-components/100-functional-components.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/102-components/101-class-components.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/102-components/readme.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/103-props-vs-state.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/104-conditional-rendering.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/106-lists-and-keys.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/107-composition-vs-inheritance.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/108-basic-hooks/100-use-state.md
- content/roadmaps/103-react/content/100-react-fundamental-topics/108-basic-hooks/101-use-effect.md
- content/roadmaps/103-react/content/101-react-advanced-topics/100-hooks/101-writing-your-own-hooks.md
- content/roadmaps/103-react/content/101-react-advanced-topics/100-hooks/102-common-hooks.md
- content/roadmaps/103-react/content/101-react-advanced-topics/100-hooks/readme.md
- content/roadmaps/103-react/content/101-react-advanced-topics/101-context.md
- content/roadmaps/103-react/content/101-react-advanced-topics/102-refs.md
- content/roadmaps/103-react/content/101-react-advanced-topics/103-render-props.md
- content/roadmaps/103-react/content/101-react-advanced-topics/104-high-order-components.md
- content/roadmaps/103-react/content/102-react-ecosystem/100-routers/100-react-router.md
- content/roadmaps/103-react/content/102-react-ecosystem/103-api-calls/readme.md
- content/roadmaps/103-react/content/102-react-ecosystem/105-forms/readme.md
- content/roadmaps/103-react/content/102-react-ecosystem/106-testing/101-react-testing-library.md
- content/roadmaps/103-react/content/102-react-ecosystem/107-state-management/100-context-state.md
- content/roadmaps/103-react/content/102-react-ecosystem/107-state-management/readme.md
- content/roadmaps/103-react/content/102-react-ecosystem/108-styling/103-styled-components.md
- content/roadmaps/103-react/content/102-react-ecosystem/108-styling/readme.md
- content/roadmaps/103-react/content/102-react-ecosystem/readme.md
Hi Kamran. I hope these articles help your readers a lot. Let me know if any tutorials are missing for your roadmap, if any tutorials need updates, or if anything should be removed :)
Some more sugesstions:
- Vite as alternative to CRA
- Vitest as alternative to Jest
- some topics could be added
- React Fundamentals:
- Reusable Components: 
- https://www.robinwieruch.de/react-reusable-components/
- e.g. https://www.robinwieruch.de/react-checkbox/ or https://www.robinwieruch.de/react-radio-button/ and some more ...
- Events
- Event Handler https://www.robinwieruch.de/react-event-handler/
- Event Bubbling https://www.robinwieruch.de/react-event-bubbling-capturing/
- React Advanced
- Project Structure https://www.robinwieruch.de/react-folder-structure/
> react-roadmap/new-resources

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/102-uncaught-exceptions.md
Issue - Add content to Node.js roadmap https://github.com/kamranahmedse/developer-roadmap/issues/1839
Q - What does this PR cover?
A - Added content in Node.js Roadmap for uncaught-exceptions
> Update content for uncaught-exceptions

- content/roadmaps/109-golang/content/109-go-microservices/101-rpcx.md
- add Rpcx description
- Address this issue: https://github.com/kamranahmedse/developer-roadmap/issues/1836
> docs: add Rpcx description

- content/roadmaps/106-javascript/content/readme.md
(#1838) [https://github.com/kamranahmedse/developer-roadmap/issues/1838]  I resolved this issue by adding the content. Please look into my PR!!
> Added content to readme.md file of 106-javascript.

- content/roadmaps/107-nodejs/content/110-nodejs-databases/101-document/readme.md
- add document database explanation
- Address issue: https://github.com/kamranahmedse/developer-roadmap/issues/1839
> docs: add document database explanation

- content/roadmaps/109-golang/content/109-go-microservices/105-protocol-buffers.md
- Put critical information on Protobuf in Go
- Address this issue: https://github.com/kamranahmedse/developer-roadmap/issues/1836
> docs: Put critical information on Protobuf in Go

- content/roadmaps/109-golang/content/109-go-microservices/108-twirp.md
- Add Twirp Brief Explanation and Links
- Help addressing this issue: https://github.com/kamranahmedse/developer-roadmap/issues/1836
> docs: Add Twirp Brief Explanation and Links

- content/roadmaps/107-nodejs/content/107-nodejs-apis/readme.md
(#1839) [https://github.com/kamranahmedse/developer-roadmap/issues/1839] Please look at my PR!
> added readme.md file

- content/roadmaps/113-qa/content/102-qa-manual-testing/100-tdd.md
- content/roadmaps/113-qa/content/102-qa-manual-testing/101-test-planning.md
- content/roadmaps/113-qa/content/102-qa-manual-testing/102-test-cases-and-scenarios.md
- content/roadmaps/113-qa/content/102-qa-manual-testing/104-compatibility.md
- content/roadmaps/113-qa/content/102-qa-manual-testing/105-verification-and-validation.md
Updated Manual Testing Processes. Few are bit lengthy but I believe it explains the process really well in 2-3 sentences.
- TDD
- Test Planning
- Test Cases and Scenarios
- Compatibility
- Verification and Validation
> Update Manual Testing Processes

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/104-bash-scripting.md
Update bash scripting with 'The Bash Hackers Wiki' link. Must read for everyone who wants to learn bash.
> The Bash Hackers Wiki

- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/100-default-params.md
- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/101-rest-params.md
- content/roadmaps/106-javascript/content/109-javascript-functions/101-function-parameters/readme.md
- content/roadmaps/106-javascript/content/109-javascript-functions/102-arrow-functions.md
- content/roadmaps/106-javascript/content/109-javascript-functions/103-iifes.md
- content/roadmaps/106-javascript/content/109-javascript-functions/readme.md
Update headers for "Free Content"
Fix label badge text
Add resources
> Update Function node, JavaScript Roadmap

- content/roadmaps/107-nodejs/content/110-nodejs-databases/readme.md
(#1839 ) [https://github.com/kamranahmedse/developer-roadmap/issues/1839] I solved this issue by adding content. Please look at my PR!!
> added content to read.md file of   110-nodejs-databases

- content/roadmaps/106-javascript/content/108-javascript-expressions-and-operators/107-conditional-operators.md
> Fixes typo

- content/roadmaps/101-backend/content/109-apis/readme.md
- Add Interactive video on explanation of "What is An API"
> docs: add video references on 'what is an API?'

- content/roadmaps/101-backend/content/108-more-about-databases/107-sharding-strategies.md
- Add Sharding Strategies Description
- Add Sharding Strategies Relevant links
> docs: Explain Database Sharding Strategies

- content/roadmaps/103-react/content/100-react-fundamental-topics/108-basic-hooks/101-use-effect.md
- content/roadmaps/109-golang/content/101-go-advanced/102-types-and-type-assertions.md
- content/roadmaps/109-golang/content/101-go-advanced/105-goroutines.md
- content/roadmaps/109-golang/content/101-go-advanced/106-channels.md
- content/roadmaps/109-golang/content/101-go-advanced/107-buffer.md
- content/roadmaps/109-golang/content/101-go-advanced/108-select.md
- content/roadmaps/109-golang/content/106-go-realtime-communication/101-centrifugo.md
- content/roadmaps/109-golang/content/109-go-microservices/108-twirp.md
> Golang typos fix

- content/roadmaps/103-react/content/100-react-fundamental-topics/108-basic-hooks/101-use-effect.md
added initial mounting phase as well for useeffect
> added initial mounting phase as well for useeffect

- content/roadmaps/109-golang/meta.json
Hi!
This is my first pull request to this repository!
It's minor, but I'd be happy to `hacktoberfest-accepted` label it if you'd like.
> fix typo in 109-golang meta information

- content/roadmaps/109-golang/content/106-go-realtime-communication/101-centrifugo.md
Hello, awesome project! 
Just noticed that the link is broken.
> Fix typo in href

- content/roadmaps/109-golang/content/100-go-basics/103-for-loop.md
- content/roadmaps/109-golang/content/100-go-basics/107-conditionals.md
- content/roadmaps/109-golang/content/100-go-basics/112-arrays.md
- content/roadmaps/109-golang/content/100-go-basics/113-slices.md
- content/roadmaps/109-golang/content/100-go-basics/114-maps.md
- content/roadmaps/109-golang/content/100-go-basics/115-make.md
- content/roadmaps/109-golang/content/101-go-advanced/103-interfaces.md
- content/roadmaps/109-golang/content/101-go-advanced/105-goroutines.md
- content/roadmaps/109-golang/content/101-go-advanced/106-channels.md
Effective Go is a good read for all Go developers. Adding reference to Effective Go for Arrays, Slices, Maps and more
> Add more content to Go Roadmap

- content/roadmaps/100-frontend/content/121-mobile-applications/100-react-native.md
CodeAcademy offers a great way to understand the basic concepts of React Native for developers new to this development paradigm and is very hands on.
> Add new couse option to react-native node content

- content/roadmaps/106-javascript/content/118-working-with-apis/100-xml-http-request.md
- content/roadmaps/106-javascript/content/118-working-with-apis/101-fetch.md
- content/roadmaps/106-javascript/content/118-working-with-apis/readme.md
Added content for XMLHttpRequest and Fetch in Working with APIs.
According to #1838
> Added content for Working with APIs.

- content/roadmaps/100-frontend/content/101-html/101-writing-semantic-html.md
I think the already given description was not enough for new learners, so I added a little more about what semantic elements in HTML are and what they do.
> Added more to semantic elements

- content/roadmaps/107-nodejs/content/105-nodejs-working-with-files/105-fs-extra.md
- content/roadmaps/107-nodejs/content/105-nodejs-working-with-files/106-chokidar.md
For issue [Add content to Node.js Roadmap #1839](https://github.com/kamranahmedse/developer-roadmap/issues/1839)
> feat: add content for fs-extra node for Node.js Roadmap

- content/roadmaps/101-backend/content/121-web-sockets.md
- content/roadmaps/102-devops/content/101-os-concepts/105-sockets.md
- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/101-non-functional-testing/accessibility-testing.md
- content/roadmaps/113-qa/content/102-qa-manual-testing/100-tdd.md
- content/roadmaps/113-qa/content/103-qa-automated-testing/102-backend-automation/101-cypress.md
1. Adding reference about library Socket.io for websockets in backend and sockets context 
2. References in IBM accessibility tools for documentation and references in methods for accessibility tests 
3. Adding course in section TDD about Introduction to Test Driven Development 
4. Adjusting cypress page in blank
> (hacktoberfest-2022)add new references in docs

- content/roadmaps/108-python/content/100-python-basics/106-string-methods.md
> added improved string methods in python basics

- content/roadmaps/109-golang/content/109-go-microservices/104-go-zero.md
> Update 104-go-zero.md #1836

- content/roadmaps/110-java/content/107-testing-java-apps/102-cukes.md
Please review the PR
Issue #1837
> cukes-rest node added in java roadmap

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/readme.md
added contetn into readme.md file
repostiroy name: 101-live in terminal ( devops roadmap)
> content added into readme.md

- content/roadmaps/113-qa/content/106-qa-reporting/101-allure.md
Changed Allue to Allure in Allure node (OFFICIAL DOCS: Allure Official Docs)
> Fixed typo in Allure node

- public/project/software-design-architecture.json
Changed abstarction to abstraction in **Design Principles** - _Program against abstraction_
> Typo Corrected

- content/roadmaps/107-nodejs/content/117-nodejs-common-modules/100-builtin-modules.md
DNS , events , child_processes , REPL , readline , util , querystring , string_decoder , tls
> Added 9 more common modules

- content/roadmaps/113-qa/content/103-qa-automated-testing/102-backend-automation/readme.md
(#1840 ) [https://github.com/kamranahmedse/developer-roadmap/issues/1840] I solved this issue, Please look at my PR!!
> added content to readme.md file of  102-backend-automation

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/102-uncaught-exceptions.md
> Adds content and suggestion

- content/roadmaps/110-java/content/100-java-fundamentals/100-basic-syntax.md
- content/roadmaps/110-java/content/100-java-fundamentals/101-data-types-variables.md
- content/roadmaps/110-java/content/100-java-fundamentals/102-conditionals.md
- content/roadmaps/110-java/content/100-java-fundamentals/103-functions.md
- content/roadmaps/110-java/content/100-java-fundamentals/104-datastructures.md
- content/roadmaps/110-java/content/100-java-fundamentals/106-files-and-apis.md
- content/roadmaps/110-java/content/100-java-fundamentals/106-packages.md
- content/roadmaps/110-java/content/100-java-fundamentals/107-loops.md
- content/roadmaps/110-java/content/100-java-fundamentals/108-exception-handling.md
> added content to 100-java-fundamentals

- content/roadmaps/107-nodejs/content/102-nodejs-npm/102-updating-packages.md
- content/roadmaps/107-nodejs/content/105-nodejs-working-with-files/103-glob.md
- content/roadmaps/107-nodejs/content/107-nodejs-apis/101-express-js.md
- content/roadmaps/107-nodejs/content/112-nodejs-logging/100-morgan.md
> Nodejs roadmap content

- content/roadmaps/100-frontend/content/121-mobile-applications/readme.md
added content for mobile applications
> added content for mobile applications

- content/roadmaps/109-golang/content/101-go-advanced/105-goroutines.md
> hyperlink typo fix

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/101-system-errors.md
- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/102-user-specified-errors.md
Issue - Add content to Node.js roadmap https://github.com/kamranahmedse/developer-roadmap/issues/1839
Q - What does this PR cover?
A - Added content in Node.js Roadmap for system-errors and user-specified-errors
> Update content for system-errors and user-specified-errors

- content/roadmaps/102-devops/content/108-cloud-providers/108-IBM-Cloud.md
Added content related to IBM-Cloud under "developer-roadmap/content/roadmaps/102-devops/content/108-cloud-providers"
#1885
> Added Content under DevOps roadmap #1885

- content/roadmaps/101-backend/content/123-scalability/101-instrumentation-monitoring-telemetry.md
There was no data on instrumentation, monitoring, and telemetry, so I decided to contribute and help others by also providing links.
> Added instrumentation, telemetry, monitoring

- content/roadmaps/101-backend/content/110-caching/102-client-side.md
There was no data on client-side-file-caching, so I added some for people to learn.
> Added client-side-file-caching

- content/roadmaps/100-frontend/content/106-web-security-knowledge/readme.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19IxERcBC9LvOcpCAjhJtjsJB5ZW1Crc0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Vfm_Gi2)
Added YouTube OWASP Course Playlist by Arkenstone Learning
> Update Web Security Knowledge Readme

- content/roadmaps/100-frontend/content/111-pick-a-framework/104-solid-js.md
Update the Solid.js Resource panel with an introductory text
> Add an Introductory Text to Solid.js

- content/roadmaps/100-frontend/content/111-pick-a-framework/101-angular/readme.md
This course is an in-depth angular introductory course with 17hrs of content from freecodecamp. covers topics ranging from TS introduction to Important Angular topics.
> Add a resource to angular course

- content/roadmaps/110-java/content/105-java-logging-frameworks/100-log4j2.md
Talks about why Apache Log4 had become the most deployed pieces of open source software, Log4j exploits, and How to protect against it.
> A detailed guide about Apache Log4j Project

- content/roadmaps/109-golang/content/104-go-web-frameworks/readme.md
Added a github repository that compares the state of Web frameworks in Golang
> Go Web Frameworks comparison

- content/roadmaps/105-vue/content/101-advanced-topics/104-watch.md
Talks about deep and immediate options with examples. showcases example use cases on how to use watchers in action, and when to utilize computed properties, and when to use watchers.
> An indepth introductory guide about watchers

- content/roadmaps/103-react/content/102-react-ecosystem/100-routers/readme.md
Talks about how the development of single-page websites or mobile applications that permit navigating without refreshing the page. Additionally, how react-router allows us to access browser history functionalities while preserving the correct application view, how component-based routing plays a huge role, and much more.
> Indepth guide about Routing (Beginner Friendly)

- content/roadmaps/105-vue/content/101-advanced-topics/112-plugins.md
Talks about what are plugins, shows how to create a simple vue.js plugin, Add directives, mixins, filters, and how to accept options.
> Add a resource to plugins in Vue.js

- content/roadmaps/108-python/content/102-python-advanced-topics/100-oop/readme.md
All the concepts of Object Oriented Programming summarized in one video with best explanation and implementation.
> Adding resources in readme.md

- content/roadmaps/101-backend/content/103-learn-a-language/103-php.md
- Add a link to PHP for Beginners (2023 Edition) [Free Course]
> A course added for PHP

- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/100-functional-testing/exploratory-testing.md
- content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/101-non-functional-testing/load-testing.md
- content/roadmaps/113-qa/content/103-qa-automated-testing/102-backend-automation/102-soap-ui.md
- content/roadmaps/114-software-architect/content/111-web-and-mobile/105-w3c-and-whatwg-standards.md
> Fixed typos (small changes) see commits

- content/roadmaps/103-react/content/102-react-ecosystem/103-api-calls/104-axios.md
Talks about why we should use it, set up instructions, GET, POST,  PUT, DELETE Requests, create a custom useAxios Hook, how to create an Axios Instance, and much more.
> Use Axios with React

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/100-basic-introduction/responsive-vs-adaptive.md
Added info to Responsive vs Adaptive node 👍
> Add info to Responsive vs Adaptive node

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/103-check-my-links.md
Added info to Check My Links node 👍
> Add info to Check My Links node

- content/guides/proxy-servers.md
> Update Grammar Mistakes

- content/roadmaps/102-devops/content/102-managing-servers/101-live-in-terminal/104-bash-scripting.md
Added blog reference for bash scripting guide for beginners. It also got featured in daily.dev and crossed 4K+ views.
Issue #1885
> Added resource to 104-bash-scripting.md

- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/100-equality-algorithms/readme.md
I added an explainer and a MZ doc link to explain equality algorithms in JS
> content update for JS equality algorithms

- content/roadmaps/106-javascript/content/109-javascript-functions/readme.md
I added more details to clarify the role and usefulness of functions in JavaScript
> content update for JS functions

- content/roadmaps/106-javascript/content/101-javascript-variables/103-scopes/readme.md
I added more detail to the Scope subtopic in the JavaScript roadmap
> updated content for JavaScript Scopes

- content/roadmaps/101-backend/content/115-architectural-patterns/readme.md
readme.md added in Architectural patterns node
> Backend Roadmap: Architectural patterns readme.md added

- content/roadmaps/102-devops/content/101-os-concepts/100-networking.md
Added Full free networking course by Kunal Kushwaha
> Added new networking content

- content/roadmaps/110-java/content/107-testing-java-apps/104-junit.md
update junit links related to this issue #1837
> update junit resources link

- content/roadmaps/102-devops/content/103-networking-protocols/103-emails/readme.md
Issue #1885
Please review the PR
> devops roadmap: email readme.md node added

- content/roadmaps/113-qa/content/105-qa-email-testing/100-mailinator.md
Mailinator node information added 👍
> Add Mailinator node info

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/102-automation-frameworks/qa-wolf.md
QA Wolf node information added👍
> Add QA Wolf node information

- content/roadmaps/103-react/content/102-react-ecosystem/103-api-calls/readme.md
Added a small description of what an API is and what is an API call and how it benefits people
> Added more about API calls

- content/roadmaps/103-react/content/100-react-fundamental-topics/108-basic-hooks/readme.md
added a more user friendly description about what hooks in react do, so that learners can understand the concept quickly and easily
> Added additional details about Hooks

- content/roadmaps/100-frontend/content/104-version-control-systems/100-basic-usage-of-git.md
- content/roadmaps/100-frontend/content/105-repo-hosting-services/100-github.md
Added Git and GitHub learning resources
> Added Git and GitHub learning resources 

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/100-basic-introduction/swas-pwas-jamstack.md
Added information to SWAs, PWAs and Jamstack node 👍
> Add SWAs, PWAs and Jamstack node information

- content/roadmaps/110-java/content/100-java-fundamentals/104-datastructures.md
- content/roadmaps/110-java/content/100-java-fundamentals/readme.md
Added free java complete course
Removed paid resource
> Added more resources in java roadmap

- content/roadmaps/110-java/content/100-java-fundamentals/101-data-types-variables.md
- content/roadmaps/110-java/content/100-java-fundamentals/102-conditionals.md
> Updated and fixed java resources

- content/roadmaps/117-flutter/content/100-dart-basics/100-dart-pad.md
- content/roadmaps/117-flutter/content/100-dart-basics/101-variables.md
- content/roadmaps/117-flutter/content/100-dart-basics/102-built-in-types.md
- content/roadmaps/117-flutter/content/100-dart-basics/103-functions.md
- content/roadmaps/117-flutter/content/100-dart-basics/104-operators.md
- content/roadmaps/117-flutter/content/100-dart-basics/105-control-flow-statements.md
- content/roadmaps/117-flutter/content/101-setup-development-environment/100-flutter-cli.md
- content/roadmaps/117-flutter/content/102-widgets/100-stateless-widgets.md
- content/roadmaps/117-flutter/content/102-widgets/101-stateful-widgets.md
- content/roadmaps/117-flutter/content/102-widgets/102-styled-widgets/100-material-widgets.md
- content/roadmaps/117-flutter/content/102-widgets/102-styled-widgets/101-cupertino-widgets.md
- content/roadmaps/117-flutter/content/103-working-with-assets/100-fonts.md
- content/roadmaps/117-flutter/content/103-working-with-assets/101-images.md
- content/roadmaps/117-flutter/content/107-package-manager/100-pub-dev.md
- content/roadmaps/117-flutter/content/108-working-with-apis/100-json.md
- content/roadmaps/117-flutter/content/108-working-with-apis/101-web-sockets.md
- content/roadmaps/117-flutter/content/109-storage/102-firebase/readme.md
- content/roadmaps/117-flutter/content/110-advanced-dart/100-core-libraries.md
- content/roadmaps/117-flutter/content/111-state-management/100-provider.md
- content/roadmaps/117-flutter/content/111-state-management/102-flutter-bloc.md
- content/roadmaps/117-flutter/content/111-state-management/105-redux.md
- content/roadmaps/117-flutter/content/112-animations/104-hero.md
- content/roadmaps/117-flutter/content/112-animations/105-opacity.md
- content/roadmaps/117-flutter/content/112-animations/readme.md
- content/roadmaps/117-flutter/content/113-testing/100-unit-testing.md
- content/roadmaps/117-flutter/content/113-testing/101-widget-testing.md
- content/roadmaps/117-flutter/content/113-testing/102-integration-testing.md
- content/roadmaps/117-flutter/content/115-dev-tools/100-flutter-inspector.md
Added descriptions with links to mostly official Flutter/Dart documentation and libraries from pub.dev
> Update Flutter Roadmap

- content/roadmaps/100-frontend/content/101-html/readme.md
Added HTML Full Course for Beginners | Complete All-in-One Tutorial  by Dave gray
> Added new resources

- content/roadmaps/110-java/content/100-java-fundamentals/105-oop.md
Added OOPs playlist by Kunal Kushwaha
> Added more oops resources

- content/roadmaps/101-backend/content/109-apis/106-authentication/102-basic-authentication.md
Intro and a good link to the resource about basic auth added
> Intro to Basic Authentication added

- content/roadmaps/114-software-architect/content/115-operations-knowledge/103-linux-unix.md
Added beginners-friendly blog reference for Linux. It also got featured in the dev community and crossed 10K+ views.
> Added resource to 103-linux-unix.md

- content/guides/session-based-authentication.md
This PR adds two missing apostrophes in the `res.setHeader` calls.
> Add missing apostrophes

- content/roadmaps/107-nodejs/content/106-nodejs-command-line-apps/readme.md
description added for command line apps
> node.js command line apps readme added

- content/roadmaps/113-qa/content/103-qa-automated-testing/100-frontend-automation/102-bug-management.md
Please check #2884 on why I updated name to Bug Magnet.
> Update Bug Magnet

- content/roadmaps/100-frontend/content/102-css/101-making-layouts.md
- content/roadmaps/100-frontend/content/102-css/readme.md
Added css complete course by Dave Gray and rearrange the css content.
> Updated CSS topic in Frontend roadmap

- content/roadmaps/106-javascript/content/101-javascript-variables/102-naming-rules.md
This resource gives some very useful variable naming tips for JavaScript.
> Added new resource to variable naming rules - JavaScript Roadmap

- content/roadmaps/107-nodejs/content/104-nodejs-async-programming/102-promises.md
Deleted page is not available anymore
> Delete a page 

- content/roadmaps/100-frontend/content/101-html/101-writing-semantic-html.md
theres a duplicated topic here and in the website
> removed duplicated topic

- content/roadmaps/101-backend/content/102-os-general-knowledge/104-basic-terminal-commands.md
The article name has changed from 34 to 40 Basic Linux Commands
> update article name for basic linux commands

- content/roadmaps/111-design-system/content/101-design-system-terminology/readme.md
Add a snapshot of the post https://web.archive.org/web/20220620075140/https://superfriendly.com/design-systems/glossary/
> design-systems glossary page unavailable

- content/roadmaps/106-javascript/content/100-javascript-introduction/100-what-is-javascript.md
<BadgeLink badgeText='Watch' href='https://www.youtube.com/watch?v=PkZNo7MFNFg'>Learn Javascript - Full course for bignners></BadgeLink>
> update free content

- content/roadmaps/116-aspnet-core/content/100-basics-of-csharp/102-dotnet-cli.md
hello Mr. Kamranahmed
thats my first PR to this big project
i added some content to Learn the Basics of csharp (.NET CLI) in ASP.NET Core roadmap
good luck.
> added content in Learn the Basics of csharp (.NET CLI) in ASP.NET Core roadmap

- content/roadmaps/117-flutter/content/109-storage/101-shared-preferences.md
Added SharedPreference description from pub.dev
> Added SharedPreference description

- content/roadmaps/114-software-architect/content/108-security/101-pki.md
> Add PKI node information

- content/roadmaps/114-software-architect/content/106-architect-tools/103-atlassian-tools.md
Atlassian Tools information added 👍
> Add information to Atlassian Tools node

- content/roadmaps/116-aspnet-core/content/103-basics-of-aspnet-core/100-mvc.md
I've updated the basic  intro of MVC and documentation link
> Updated intro of MVC and added the documentation link

- content/roadmaps/106-javascript/content/102-javascript-datatypes/101-object/102-builtin-objects.md
Since the attached video has different languages in its content it might be difficult to understand the concept properly.
> deleted a video resource that has mixe of english and other language

- content/roadmaps/106-javascript/content/104-javascript-data-structures/readme.md
Additional resources for tree and graph algorithms for technical interviews 
JavaScript code implementation
> Additional resources for tree and graph algorithms

- content/roadmaps/101-backend/content/103-learn-a-language/106-python.md
Adding a strong Python video tutorial to the other resources, given there is no video content currently. Many users prefer this form of media in the first instance, so hopefully this expands this section to those more comfortable with video learning!
> Adding video option to Python content

- content/roadmaps/108-python/content/100-python-basics/readme.md
Added W3Schools python tutorial link as a read free resource
> Added W3Schools link Python

- content/roadmaps/107-android/landscape.md
I capitalized any product names that were incorrectly in lowercase. I also fixed any grammar, punctuation, and writing mechanics issues that I noticed.
> Fix typos and writing issues

- content/roadmaps/114-software-architect/content/115-operations-knowledge/100-infrastructure-as-code.md
Fix for free reading resource "What is Infrastructure as Code (IaC)?"
> Fix a link to an article

- content/roadmaps/117-flutter/content/104-version-control-systems/readme.md
Definition and examples of Version Control Systems.
> Defining Version Control Systems

- content/roadmaps/100-frontend/content/103-javascript/101-learn-dom-manipulation.md
> Fixing typo in DOM section

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/readme.md
Added some useful links and description to Types of Errors block
> Update Node.js roadmap Types of Errors

- content/roadmaps/106-javascript/content/102-javascript-datatypes/readme.md
"There are eight basic data types in JavaScript" is ambiguous (are objects considered "basic" ?). Javascript features seven (7) primitive datatypes and all objects are non-primitives.
Source (MDN) : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
> Clarification about the number of datatypes in JS.

- content/roadmaps/107-nodejs/content/103-nodejs-error-handling/103-error-types/103-assertion-errors.md
Updated Assertion Errors block with some useful links and description
> Update Node.js roadmap Assertion Errors

- src/roadmaps/computer-science/content/116-system-design/110-grpc.md
> fix: gRPC typo

- src/roadmaps/react/content/102-components/103-props-vs-state.md
- src/roadmaps/react/content/102-components/105-composition-vs-inheritance.md
- src/roadmaps/react/content/103-rendering/102-render-props.md
1. Came across two other interesting topics related to props and state in react
2. Would like to suggest that we add these to the list as well as they highlight something important
3. One is from robinwieruch and the other from Dominik Dorfmeister (TkDodo)
> [Build] React Roadmap

- src/roadmaps/flutter/content/100-dart-basics/103-functions.md
- src/roadmaps/flutter/content/100-dart-basics/index.md
Dart can also be used to build server and desktop application
> Update Dart Basic and Dart Functions 

- src/roadmaps/nodejs/content/104-nodejs-async-programming/104-callbacks.md
Update Callback broken link based on this issue #3307
> fix: Update Broken Link to NodeJS Callback

- src/roadmaps/flutter/content/114-reactive-programming/100-rxdart.md
Added some content to `src/roadmaps/flutter/content/114-reactive-programming/100-rxdart.md`
> Update - content for rxdart under flutter roadmap

- src/roadmaps/python/content/100-python-roadmap-note.md
Fixed a minor typo in python roadmap note. 
Note : I am new to open source contribution. I have tried to follow contribution guides. Would love to know if I need improvements. Thank you.
> Fixed a typo in python roadmap note

- src/roadmaps/backend/content/111-web-security-knowledge/105-https.md
I have added a brief explanation of how the HTTPS protocol works and a new resource to learn more
> Extended HTTP page

- src/roadmaps/postgresql-dba/postgresql-dba.md
> docs: add PostGIS and Bytebase to the postgresql-dba roadmap.

- src/roadmaps/spring-boot/content/100-spring-core/107-spring-bean-scope.md
> Spring boot - scope content

- src/roadmaps/angular/content/101-rxjs-basics/104-operators/100-filtering.md
> Updated 100-filtering.md added new content

- src/data/roadmaps/typescript/content/100-typescript/102-install-configure/index.md
the exclude option should go in the root of the tsconfig
> Move 'exclude' option in tsconfig.json out of 'compilerOptions

- src/data/roadmaps/frontend/content/104-version-control-systems/100-basic-usage-of-git.md
Stumbled across this website while learning git and it helped me a lot to understand and visualize what's going.
GitHub repository of added resource: https://github.com/pcottle/learnGitBranching
It has MIT Licensing, so I don't think there's and issue referencing it.
> Add Interactive Git Branching Guide by pcottle

- src/data/roadmaps/kubernetes/content/104-services-and-networking/100-networking-and-pod-to-pod-communication.md
> Fix a link

- src/data/roadmaps/backend/content/123-scalability/102-migration-strategies.md
> Fix - Typo in 3rd line of migration strategies

- src/data/roadmaps/react/content/105-routers/100-react-router.md
I'm adding a link to a React Router cheatsheet/reference covering examples of various routes, including core components and routers introduced in v6.4.
> Updating resources for React Router

- src/data/roadmaps/backend/content/104-version-control-systems/100-basic-usage-of-git.md
Atlassian's Git Tutorials come across the beginning up to advanced tips on git usage, a great place to dive into its understanding
> feat: Include atlassian tutorials in git section

- src/data/roadmaps/backend/content/100-internet/101-what-is-http.md
I created this 5-hour course on the FreeCodeCamp YouTube channel, and I think it can help a ton of folks learn HTTP from the perspective of a web developer!
Like all of the content on Boot.dev, it's free and doesn't require sign up.
> Add updated HTTP networking course

- src/data/roadmaps/software-design-architecture/content/108-enterprise-patterns/110-orms.md
> Update 110-orms.md. Title from Orms to ORMs

- src/data/roadmaps/qa/content/100-qa-basics/105-manage-your-testing/106-xray.md
- src/data/roadmaps/qa/content/100-qa-basics/106-project-management/100-atlassian.md
- src/data/roadmaps/qa/content/100-qa-basics/107-testing-techniques/100-functional-testing/smoke-testing.md
**Added xRay management tool and links**
**Added smoke testing link explanation**
**Added Jira documentation and how to start**
> added xRay management tool and useful links around smoke testing technique

- .prettierrc.cjs
- .vscode/settings.json
- package.json
- pnpm-lock.yaml
- src/pages/roadmaps.astro
Prettier configuration for Astro component's formatting and Tailwind CSS class sorting.
> tooling: prettier for astro and tailwind

- src/data/roadmaps/javascript/content/100-javascript-introduction/102-javascript-versions.md
I replaced and with it in the Javascript versioning paragraph
> Fix minor typo

- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/107-consensus-protocols.md
Update the broken link to a new one from the same site
> Update invalid link (#3751)

- src/data/roadmaps/angular/content/100-typescript-basics/103-type-inference.md
in the Type Inference content at Angular -> the basics -> Type Inference .. replaced the wrong interface keyword into Inference
> fix typo, replace Interface with Inference

- src/data/roadmaps/cyber-security/content/102-networking-knowledge/understand-these/100-man.md
Fixed the MAN explanation
Issue #3762
> fix: wrong MAN explanation

- src/data/roadmaps/mongodb/content/102-useful-concepts/101-cursors.md
> Issues:  Text not showing up properly #3796

- src/data/best-practices/frontend-performance/content/analyse-stylesheets-complexity.md
- src/data/best-practices/frontend-performance/content/avoid-inline-css.md
- src/data/best-practices/frontend-performance/content/use-non-blocking-javascript.md
- add an "s" to "reason"
- change "it's" to "is"
- change "remove" to "removing"
- change comma to semicolon
- change "don't" to "doesn't"
- add "is" before "relied upon"
> Typo-fixes

- src/components/AuthenticationFlow/LoginPopup.astro
- src/components/BestPracticeHeader.astro
- src/components/UpcomingForm.astro
- src/icons/check.svg
Fix: even after logging in, the subscription form appears.
> fix: notify for upcoming page

- public/jsons/roadmaps/full-stack.json
> Fix wrong backend and devops links on fullstack roadmap top.

- src/components/AuthenticationFlow/EmailLoginForm.tsx
- src/components/AuthenticationFlow/GitHubButton.tsx
- src/components/AuthenticationFlow/GoogleButton.tsx
- src/components/AuthenticationFlow/ResetPasswordForm.tsx
- src/components/AuthenticationFlow/TriggerVerifyAccount.tsx
> User gets logged out on browser quit.

- src/data/roadmaps/react/content/104-hooks/102-common-hooks.md
The external link is broken, YouTube is showing the following:
`This video isn't available anymore`
> The external link is broken

- src/data/roadmaps/software-design-architecture/content/100-clean-code-principles/103-indentation-and-code-style.md
> fix: typo: mor -> more

- src/data/roadmaps/qa/content/103-qa-automated-testing/100-frontend-automation/102-automation-frameworks/playwright.md
I fixed a typo in the word "Tutorial"
> Fixed typo in the word tutorial

- src/data/roadmaps/react/content/105-routers/100-react-router.md
> 🔗 Fix Outdated Link -> React Router

- src/data/roadmaps/devops/content/102-live-in-terminal/103-process-monitoring.md
> [Issue] #4068 Remove duplicated explanation/links

- src/data/roadmaps/software-architect/software-architect.md
> [Issue] Software Architect - Duplicated python in related roadmaps

- src/data/roadmaps/computer-science/content/101-pick-a-language/101-c.md
> 🔗 Fix Broken Link -> Computer Science (C)
