- src/data/roadmaps/computer-science/content/117-databases/114-views.md
> Fix spelling Mistake

- src/data/roadmaps/spring-boot/content/109-spring-mvc/100-servlet.md
[FIXED] Last link typos in the Servlet section of the Spring boot developer roadmap titled "What is Dispatcher Servlet in Spring?" 100-servlet.md
> fix(typo): link updated in 100-servlet.md

- src/data/roadmaps/computer-science/content/104-common-algorithms/109-cache-algorithms/102-mfu-cache.md
> Fix Computer Science roadmap MFU cache description

- src/data/roadmaps/nodejs/content/100-nodejs-introduction/102-history-of-nodejs.md
Deleted broken link of official documentation and added some suggestions of links that can fill in.
> [Node.js Developer] Update 102-history-of-nodejs.md

- src/data/roadmaps/cpp/content/100-introduction/index.md
> 🔗 fix: broken link in roadmap cpp

- src/data/guides/introduction-to-llms.md
> remove trailing spaces/lines

- src/data/roadmaps/code-review/content/102-documentation.md
This pull request addresses minor issues in the code-review document ([102-documentation.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/code-review/content/102-documentation.md)) by fixing a typo and making grammatical improvements.
> Fix typo and grammatical improvements for code-review (102-documentation.md)

- src/data/roadmaps/cpp/content/101-setting-up/102-first-program.md
> fix(typo): fixed typo in  cpp - main() function heading

- src/components/DeleteTeamPopup.tsx
- src/components/TeamMembers/LeaveTeamButton.tsx
- src/components/TeamMembers/LeaveTeamPopup.tsx
- src/components/TeamSettings/UpdateTeamForm.tsx
> Leave Team confirmation popup

- src/components/CreateTeam/RoadmapSelector.tsx
- src/components/CreateTeam/SelectRoadmapModal.tsx
- src/components/CreateTeam/Step2.tsx
- src/icons/plus-white.svg
> Select Roadmaps Modal

- src/components/TeamDropdown/TeamDropdown.tsx
- src/components/TeamProgress/MemberProgressItem.tsx
- src/components/TeamProgress/TeamProgressPage.tsx
> Show current user progress first

- src/components/ReactIcons/CloseIcon.tsx
- src/components/RoadmapHint.astro
- src/components/TeamProgress/MemberProgressItem.tsx
- src/components/TeamProgress/MemberProgressModal.tsx
- src/components/TeamProgress/ProgressHint.tsx
- src/components/TeamProgress/TeamProgressPage.tsx
> Add update progress functionality in modal

- src/components/ReactIcons/MailIcon.tsx
- src/components/TeamDropdown/TeamDropdown.tsx
- src/components/TeamMembers/MemberActionDropdown.tsx
- src/components/TeamMembers/RoleBadge.tsx
- src/components/TeamMembers/TeamMemberItem.tsx
- src/components/TeamMembers/TeamMembersPage.tsx
> Team Member listing and Progress Reminder

- src/data/roadmaps/cpp/content/102-basic-operations/103-bitwise.md
Updated the link of youtube channel in c++ roadmap, bitwise operators
> Update the link of youtube channel

- src/components/Activity/ResourceProgress.tsx
- src/components/BestPracticeHint.astro
- src/components/ReactIcons/ShareIcon.tsx
- src/components/ResourceProgressStats.astro
- src/components/RoadmapHint.astro
- src/components/UserProgress/ProgressShareButton.tsx
- src/components/UserProgress/UserProgressModal.tsx
- src/lib/resource-progress.ts
- src/pages/[roadmapId]/index.astro
- src/pages/best-practices/[bestPracticeId]/index.astro
- src/pages/team/index.astro
> Share Progress

- src/data/roadmaps/cyber-security/content/extras/certifications/beginner-certifications/200-comptia-aplus.md
I added a link to the channel that searches for CompTIA A+ 220-1101 on Professor Messer's channel.
> fix: broken link to CompTIA A+ 220-1101 [Roadmap cyber-security]

- src/data/roadmaps/typescript/content/108-classes/105-method-overriding.md
> Fix typo in Method Overriding in Typescript

- src/data/roadmaps/frontend/content/102-css/102-responsive-design-and-media-queries.md
removed broken youtube link from list of resources in 102-responsive-design-and-media-queries.md
> fix: removed unavailable youtube link from 102-responsive-design-and-media-queries.md

- src/data/roadmaps/prompt-engineering/content/102-prompts/index.md
> [issue-4210]: Fix typo from bug 4210

- src/components/Feedback/SubmitFeedbackPopup.tsx
- src/components/TeamSidebar.tsx
> Team Feedback Popup

- src/data/roadmaps/javascript/content/101-javascript-variables/103-scopes/index.md
javascript\variable\scope\understanding global local function block scope - new link provided
Fix: #4344
> javascript-variable-scope index.md

- src/data/roadmaps/cpp/content/104-data-types/index.md
cpp\datatype\struct and class clarification
Fixes: #4363
> Cppdatatypestructandclass

- src/data/roadmaps/golang/content/100-go-basics/107-conditionals.md
golang\conditional-statement\golang programs switch case - new link provided
fix : #4372
> golang\conditional-statement

- src/data/roadmaps/android/android.md
Updated the link to the correct Gradle webpage: [#4422](https://github.com/kamranahmedse/developer-roadmap/issues/4422)
> Updated link on the Android Roadmap

- src/data/best-practices/frontend-performance/content/minify-html.md
Updated the HTML minify url to a new one that exists and is free:  #4463
> Fixing HTML Minify URL

- src/data/roadmaps/backend/content/109-apis/106-authentication/105-openid.md
- Update URL for "OAuth 2.0 and OpenID Connect (in plain English)" in backend roadmap - Fixes #4458
> Update URL for OpenID Link

- contributing.md
- Add a line break for link to show correctly in markdown
- Use correct link
> Fix content link in contributing.md

- src/data/roadmaps/javascript/content/101-javascript-variables/103-scopes/index.md
javascript-roadmap-scope-variable-local scope description added fixes : #4388
> javascript-roadmap-scope-variable

- src/data/roadmaps/backend/content/103-learn-a-language/103-php.md
changed from php.org to php.net
> Fixed PHP official website address in backend roadmap

- src/data/roadmaps/aspnet-core/content/114-microservices/106-yarp.md
asp.net-core-YARP-description fixex
fixes : #4406
> asp.net-core-YARP

- src/data/roadmaps/qa/content/103-qa-automated-testing/101-mobile-automation/100-appium.md
QA-roadmap-appium website - new link provided
fix: #4205
> qa-link-to-appium-documentation

- src/data/roadmaps/postgresql-dba/content/104-learn-sql-concepts/103-advanced-topics/index.md
json_build_object is used to create json object and get it
> fix(103-advanced-topics)

- package-lock.json
- src/data/roadmaps/angular/content/101-rxjs-basics/104-operators/101-rate-limiting.md
Issue - In the "Rate limiting" section, Blogs and tutorials on RxJS refers to a 404 page.
The dead link has been fixed with the correct and appropriate link.
> Issue : #4485 Dead Link

- src/data/roadmaps/backend/content/123-scalability/100-mitigation-strategies/101-throttling.md
backend-roadmap-throttling- missed URL fixed
fixes : #4473
> backend-roadmap-throttling

- src/data/roadmaps/backend/content/111-web-security-knowledge/106-cors.md
- src/data/roadmaps/frontend/content/106-web-security-knowledge/102-cors.md
* Sync resource links of `backend/content/.../106-cors.md` and `frontend/content/.../102-cors.md`.  
* I added a new link to an article I wrote about CORS that I hope can help people to learn the topic.
> Update CORS Resources

- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/100-solana.md
solana whitepaper url  added in the solana Blockchain  section
> Solana whitepaper added

- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/102-evm-based/index.md
Understanding the Ethereum Virtual Machine (EVM): Concepts and Architecture video added 
Video Link: https://www.youtube.com/watch?v=kCswGz9naZg
Topics covered include:
World state (0:00)
Externally owned accounts vs. Smart contract accounts (2:40)
Merkle Patricia Tries (3:43)
Block lifecycle (6:58)
Why use a virtual machine? (8:15)
EVM architecture (11:45)
EVM machine space (16:47)
Transaction lifecycle (18:22)
Higher-level languages (24:00)
Gas costs and opcode (26:53)
Environmental and Block opcodes (39:53)
EVM limitations (41:44)
Smart contract interactions (43:08)
Message calls (45:17)
I highly recommend adding this video, as it helped me a lot in understanding the EVM better
> Understanding the Ethereum Virtual Machine (EVM): Concepts and Architecture Video added

- src/data/roadmaps/system-design/content/107-domain-name-system.md
Transfer an article to a new line
> separate articles in 107-domain-name-system.md

- src/components/CustomRoadmap/CustomRoadmap.tsx
- src/components/CustomRoadmap/RoadmapHeader.tsx
- src/components/CustomRoadmap/SkeletonRoadmapHeader.tsx
- src/stores/roadmap.ts
Add Creator details at the top of the `roadmap` title.
> Add Creator Details

- src/components/CustomRoadmap/RoadmapListPage.tsx
- src/components/ShareOptions/ShareOptionsModal.tsx
- src/components/ShareOptions/ShareTeamMemberList.tsx
- src/components/ShareOptions/TransferToTeamList.tsx
Users must select the team members who will have access to the roadmap when transferring it from a personal to a team roadmap.
> Add Members while Transferring Roadmap

- src/data/roadmaps/aspnet-core/content/104-orm/100-entity-framework-core/102-change-tracker-api.md
aspnet-change-tracker-api URL fixed
fixes : #4544
> roadmap-aspnet-change-tracker-api.md

- .github/workflows/deploy.yml
- .github/workflows/update-deps.yml
Update actions/checkout version to v4
https://github.com/actions/checkout/releases/tag/v4.0.0
> Update checkout version to v4

- src/components/CustomRoadmap/PersonalRoadmapList.tsx
- src/components/CustomRoadmap/RoadmapHeader.tsx
- src/components/ShareOptions/ShareSuccess.tsx
- src/components/TeamRoadmapsList/TeamRoadmaps.tsx
> Minor Improvement for Custom Roadmap

- package-lock.json
- src/hooks/use-outside-click.ts
Before
https://github.com/kamranahmedse/developer-roadmap/assets/74682593/79a0e3bc-1259-4615-8f0a-f1227bc94db9
After
https://github.com/kamranahmedse/developer-roadmap/assets/74682593/7208d17d-8fc4-4306-aed6-ce0a4e036d90
> Fix: google translate extenstion close side panel

- src/data/roadmaps/backend/backend-forkable.json
- src/data/roadmaps/backend/backend.md
> Add forkable Backend Roadmap

- src/data/roadmaps/devops/devops-forkable.json
- src/data/roadmaps/devops/devops.md
> Add Forkable DevOps

- src/data/roadmaps/frontend/content/122-desktop-applications/100-electron.md
frontend-roadmap-javascript-electron URL fixed
fixes : #4587
> frontend-roadmap-electron

- src/data/roadmaps/frontend/content/117-progressive-web-apps/112-lighthouse.md
> Fix unavailable link

- src/data/roadmaps/ai-data-scientist/content/deployment-models.md
Add the Fullstack Deeplearning free online MOOC 2022 edition developed by UC Berkeley to the MLOps course section.
> Add Fullstack Deep Learning to MLOps

- src/data/roadmaps/backend/content/115-architectural-patterns/105-service-mesh.md
This PR updates the service mesh node within the backend roadmap.
Related issue: https://github.com/kamranahmedse/developer-roadmap/issues/4751
What I have done:
- added more details about service mesh, sidecar proxy and available popular solutions to check out (istio, linkerd)
- added one more video resource I found helpful (if someone prefers videos over articles)
Let me know if it is too long or you have some ideas for reworking some parts (for instance to make it more compact), or simply if you have any other objections.
> Update backend service mesh description

- src/data/roadmaps/python/content/106-python-frameworks/101-asynchronous/index.md
The number changed from 5 to 9 in the original article.
> Update index.md python 

- src/data/roadmaps/backend/content/123-scalability/100-mitigation-strategies/102-backpressure.md
Resource in the backpressure backend node is not working anymore. I am linking it with a new and complex one that contains more information about backpressure.
As always - in case of any objections, please let me know here. This time without creating a separate issue.
> Update resource in the backpressure backend node

- src/data/roadmaps/backend/content/114-design-and-development-principles/101-domain-driven-design.md
This PR solves the following issue: https://github.com/kamranahmedse/developer-roadmap/issues/4759
In case of any objections let me know, otherwise it's good to go.
> Replace not working DDD resource in backend node

- src/data/roadmaps/backend/content/109-scaling-databases/index.md
This pull request updates the database section to focus on scaling databases. Due to the duplication and lack of information on database scaling. It provides information on techniques like sharding and replication, which are key for efficiently handling more data and users. Additionally, it includes relevant resources for further learning.
---
The current "Scaling Databases" section:
> Update database section to focus on scaling databases

- src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md
I made a slight modification to improve the clarity of the sentence. Specifically, I changed:
"Make sure to follow the instructions provided by the editor's documentation to set up C++ correctly."
to:
"Make sure to follow the instructions provided in the editor's documentation to set up C++ correctly."
This change maintains the same meaning but improves the flow of the sentence.
> Slight modification to improve the clarity of the sentence Updated 101-code-editors.md

- src/data/question-groups/javascript/content/heap-and-stack.md
> Fix typo in heap-and-stack.md

- src/data/roadmaps/game-developer/content/101-game-mathematics/106-orientation/index.md
Fixing Typos: The heading was wrong. The Orientation node showed Curve but was supposed to Orientation
> Fixed the heading index.md (Curve to Orientation)

- src/data/roadmaps/computer-science/content/103-asymptotic-notation/103-common-runtimes/index.md
Polynomial time complexity is $O(n^k)$.
> Fixed typo O(n^n) -> O(n^k)

- src/data/roadmaps/angular/content/100-typescript-basics/106-type-guard.md
This PR solves the following issue: https://github.com/kamranahmedse/developer-roadmap/issues/4799
> Fixed Angular Roadmap Type Guard video URL

- src/data/guides/introduction-to-llms.md
Just fixing a typo—changing from "discsus" to "discuss"!
> Fix "discuss" typo

- src/data/roadmaps/qa/content/104-qa-non-functional-testing/101-accessibility-testing/100-chrome-devtools.md
Changed "temprary" to "temporary"
> Fixed a small typo in Chrome Devtools.md

- src/components/TopicDetail/TopicDetail.tsx
- src/lib/markdown.ts
- src/pages/guides/[guideId].astro
> Fix Topic Details Markdown link issue

- src/data/roadmaps/react/content/108-api-calls/106-superagent.md
Fix broken superagent official website link
> Fix broken superagent official website link

- src/data/roadmaps/nodejs/content/102-nodejs-npm/index.md
> fix npm links

- src/data/roadmaps/blockchain/content/102-blockchain-oracles/index.md
- src/data/roadmaps/blockchain/content/109-dapps/index.md
Changed `decentralised` to `decentralized` for enhanced consistency across the repository.
> Consistency in spelling

- src/data/roadmaps/backend/content/111-web-security-knowledge/105-https.md
Fixes - https://github.com/kamranahmedse/developer-roadmap/issues/4862
> issue-4862: Updated enable http reference url.

- src/data/roadmaps/rust/content/101-language-basics/100-syntax/101-variables.md
Add links for variables and data types from The Book (Official docs)
> [Rust roadmap] Add links to 101-variables.md

- src/data/roadmaps/frontend/content/115-testing-your-apps/100-jest.md
I believe this video tutorial will help greatly for jest beginners learn it's core concepts on how to use jest to test their javascript apps.
> Added javascript testing with jest (youtube video tutorial)

- src/data/roadmaps/ux-design/content/100-human-decision-making/index.md
This PR fixes issue #4995 
based on data in [archive.org](https://archive.org)
> fix: replace the broken youtube link with the correct one in ux-design

- src/data/roadmaps/blockchain/blockchain.json
> fix foundry in blockchain roadmap

- src/components/AuthenticationFlow/AuthenticationForm.tsx
- src/components/AuthenticationFlow/EmailLoginForm.tsx
- src/components/AuthenticationFlow/EmailSignupForm.tsx
- src/components/AuthenticationFlow/GitHubButton.tsx
- src/components/AuthenticationFlow/GoogleButton.tsx
- src/components/AuthenticationFlow/LinkedInButton.tsx
- src/components/AuthenticationFlow/LoginPopup.astro
- src/pages/login.astro
- src/pages/signup.astro
It solves the multi-click issue, when you click any two social login buttons at a time it will throw an error. It solves the issue by disabling them when you click one of the buttons until it resolves.
> fix: disable login buttons

- src/data/roadmaps/mongodb/content/108-developer-tools/102-developer-tools/101-vs-analyzer.md
- changed broken link for VS Analyzer
- changed installation steps
> MongoDB Roadmap: VS Analyzer broken link fix

- src/data/roadmaps/backend/content/109-apis/104-hateoas.md
the video is no longer available. see: https://www.okta.com/video/oktane17-appdev-designing-beautiful-rest-plus-json-apis/
> Update 104-hateoas.md: remove unavailable okta's video

- src/data/roadmaps/software-architect/content/105-patterns-and-design-principles/106-ddd.md
> Fix: #5142

- src/pages/get-started.astro
Corrected the description of the blockchain roadmap card to "Blockchain Developer" instead of "Technical Writer".
> Fix: Corrected a typo in get started page

- src/data/roadmaps/typescript/content/101-typescript-types/115-type-assertions/101-as-type.md
Near identical sentences appeared in two paragraphs. This condenses that.
> Remove duplication

- src/data/roadmaps/sql/content/107-sub-queries/index.md
Updated the row query definition. Row queries can return not just one but multiple rows.
> Updated index.md

- src/data/roadmaps/datastructures-and-algorithms/content/104-algorithmic-complexity/101-calculating.md
Added video resource for time and space complexity in Data structures and Algorithms section.
> feat/ Added complexity video resource

- src/data/roadmaps/java/content/101-java-advanced-topics/107-garbage-collection.md
changed the  original link : https://www.youtube.com/watch?v=xxoacv5xm9s
updated uppercase link : https://www.youtube.com/watch?v=XXOaCV5xm9s
> Fix : Invalid link in Java Developer roadmap #5408

- src/data/roadmaps/docker/content/104-data-persistence/100-ephemeral-container-fs.md
Solve conflict in information between lines 3 and 9 
"stopped (and) removed" in line 3
"stopped (or) removed" in line 9
The (or) in line 9 should be replaced by (and) because the data will persist in the file system when the container is stopped, it should be lost only when the container is removed.
> Replace "or" by "and" in line 9 : 100-ephemeral-container-fs.md

- src/data/roadmaps/frontend/content/117-progressive-web-apps/112-lighthouse.md
https://www.youtube.com/watch?v=5flw5q5odie
The link was broken, i proposed to delete it, and to replace it by an another cool stuff : 
https://unlighthouse.dev/
https://github.com/harlan-zw/unlighthouse
It's like lighthouse but for a global scan, on every pages, really usefull stuff !
> Fix broken video link, and add unlighthouse to the ressources

- src/data/roadmaps/backend/content/108-more-about-databases/103-n-plus-one-problem.md
Remove link to payed content and provide free access article
> Replace payed content - 103-n-plus-one-problem.md

- src/data/roadmaps/java/content/101-java-advanced-topics/101-memory-management.md
> fix:updated 101-memory-management.md

- src/data/roadmaps/devops/content/109-serverless/103-gcp-functions.md
Added some intro text and materials to get started.
> DevOps / Serverless / GCP (Cloud) Functions

- src/components/RoadCard/RoadCardPage.tsx
- src/env.d.ts
- src/lib/road-card.ts
- src/pages/card/[version]/[userId].ts
Add `PUBLIC_APP_URL` env variable.
> feat: migrate road card endpoint

- src/components/Activity/ActivityStream.tsx
- src/components/Activity/ActivityTopicTitles.tsx
- src/components/Activity/ActivityTopicsModal.tsx
- src/components/TeamActivity/TeamActivityItem.tsx
- src/components/TeamActivity/TeamActivityPage.tsx
- src/components/TeamActivity/TeamActivityTopicsModal.tsx
> fix: change `topicIds` to `topicTitles`

- src/components/Activity/ActivityTopicTitles.tsx
- src/components/TeamActivity/TeamActivityItem.tsx
> fix: activity word spacing

- src/components/Activity/ActivityStream.tsx
- src/components/Activity/ActivityTopicTitles.tsx
- src/components/Activity/EmptyStream.tsx
- src/components/TeamActivity/TeamActivityItem.tsx
- src/components/TeamActivity/TeamEmptyStream.tsx
> fix: update activity stream design

- src/data/roadmaps/blockchain/content/102-blockchain-oracles/102-oracle-networks.md
Fixes - https://github.com/kamranahmedse/developer-roadmap/issues/4740
> issue-4740: Updated the dead oracle network link.

- src/data/roadmaps/python/content/102-python-advanced-topics/103-lambdas.md
python-roadmap-lambdas URL fixed
fixes : https://github.com/kamranahmedse/developer-roadmap/issues/4597
> Fix Python Lambda Functions hyperlink

- src/data/roadmaps/backend/content/123-scalability/100-mitigation-strategies/103-loadshifting.md
The linked content now results in a 404.
> Removed empty AWS Content Link

- src/data/best-practices/api-security/api-security.json
**Before**:
User proper HTTP methods for the operation
**After**:
Use proper HTTP methods for the operation
> Fix typo in input section of API Security Best Practice Roadmap

- src/data/roadmaps/backend/content/103-learn-a-language/105-javascript.md
Added official Javascript documentation link for it to learn in depth.
> Add official JavaScript documentation link

- src/data/roadmaps/game-developer/content/109-advanced-rendering/100-real-time-ray-tracing/101-vulcan-ray-tracing.md
- src/data/roadmaps/game-developer/content/109-advanced-rendering/100-real-time-ray-tracing/101-vulkan-ray-tracing.md
> Fix typo of Vulcan to Vulkan

- src/data/roadmaps/game-developer/game-developer.json
An issue was raised where Vulkan was misspelt as Vulcan, this was addressed by the reporting contributor but they were not able to fix the typo on the card itself.
> fixed vulkan typo in advanced render topic

- src/data/roadmaps/software-design-architecture/content/104-design-patterns/index.md
Add resource site https://refactoring.guru/
> Add new design pattern link

- src/data/roadmaps/docker/content/110-docker-cli/index.md
`ls` command added to `docker container` and `docker image` to be more specific
> update docker list commands

- src/data/roadmaps/javascript/content/102-javascript-datatypes/100-primitive-types.md
This update highlights the distinction between primitive data types and non-primitives based on the values they hold and the properties and methods they possess.
> Add further explanations of primitive data types

- src/data/roadmaps/rust/content/100-introduction/101-why-rust.md
added links to beginner friendly videos on choosing rust
> Add video content to the 'why rust' section

- src/data/best-practices/frontend-performance/content/enable-compression.md
> Fix grammatical error in 'enable-compression' section

- src/data/roadmaps/prompt-engineering/content/101-prompting-introduction/100-basic-prompting.md
Fixed the spelling of the word "practices"
> Fix spelling error on 100-basic-prompting.md

- src/data/roadmaps/game-developer/content/101-game-mathematics/101-vector.md
Added a video on the introduction to "Vectors" for game development".
> Add youtube video link on 'Vectors'

- src/data/best-practices/frontend-performance/content/use-non-blocking-javascript.md
> Update pagespeed insights url version

- src/data/roadmaps/technical-writer/content/100-introduction/101-what-technical-writing.md
Added 2 points, made the text easier to read by including gaps at certain points.
> Improve readability of 'what is technical writing' section

- src/data/roadmaps/prompt-engineering/content/101-prompting-introduction/index.md
Capitalized the "French" word in the first example chunk.
> Capitalized 'French'

- src/data/roadmaps/backend/content/109-apis/104-hateoas.md
- src/data/roadmaps/docker/docker.json
fixes : #5109
As i checked there was no Outdated URL as such. 
Also added an interesting article on HATEOAS
> Added HATEOAS resources

- src/data/roadmaps/rust/content/100-introduction/100-what-is-rust.md
Added a Rust introduction video to the Rust introduction section of the roadmap.
> add rust video to rust intro section

- src/data/roadmaps/rust/content/101-language-basics/102-constructs/100-enums.md
Wrote an example of enum code.
> Add Rust enum example

- src/data/roadmaps/docker/content/108-running-containers/101-docker-compose.md
Hello,
Add a little information on the management of the launch order of containers in addition that can be more than convenient.
Hope it can help
> Add depends_on to dockerfile example

- src/data/roadmaps/python/content/102-python-advanced-topics/105-modules/100-builtin-modules.md
> fix grammatical error in copy

- src/data/roadmaps/react-native/content/109-interactions/100-touchables.md
duplicated "TouchableHighlight", should be TouchableScale
> Remove duplication of TouchableHighlight

- src/data/roadmaps/android/content/101-the-fundamentals/105-hello-world-app.md
Added resource for creating first android app
> Add android tutorial article

- src/data/roadmaps/android/content/101-the-fundamentals/104-using-gradle.md
> Add free Gradle PDF

- src/data/roadmaps/aws/content/101-ec2/101-cpu-credits.md
Added a reference link. This helped me understand the CPU credits better. It will be a good resource for other learners too.
> Add link to AWS documentation for CPU Credits

- src/data/roadmaps/rust/content/101-language-basics/101-ownership/index.md
> Fix typo in content heading

- src/data/roadmaps/kubernetes/content/102-setting-up-kubernetes/101-choosing-a-managed-provider.md
> Remove inactive content link

- src/data/roadmaps/devops/content/105-setting-up-x/104-firewall.md
> Remove duplicated link in 104-firewall.md

- src/data/roadmaps/sql/content/106-join-queries/index.md
Added a kind of join (Natural Join).
> Add Natural Join as an example of the types of join

- src/data/roadmaps/cpp/content/101-setting-up/102-first-program.md
Added additional information about the functions and return values about the program.
> Add int and std clarifications

- src/data/roadmaps/linux/content/103-working-with-files/100-permissions.md
> Fix type in copy

- src/data/roadmaps/sql/content/104-aggregate-queries/103-avg.md
Added SQL language identifier to enable syntax highlighting
> Add SQL identifier to enable highlighting in snippet

- src/data/roadmaps/system-design/content/112-caching/103-database-caching.md
Added a simplified explanation of database caching using analogies for easier understanding.
> Add caching analogies to db caching copy

- src/data/roadmaps/devops/content/102-live-in-terminal/scripting/100-bash-scripting.md
Added link to an interactive shell scripting tutorial
> Add interactive shell tutorial

- src/data/roadmaps/computer-science/content/116-system-design/100-horizontal-vs-vertical-scaling.md
The previous URL redirects to a whole different website which has nothing related to the topic.
> Replace article link

- src/data/roadmaps/devops/content/102-live-in-terminal/index.md
fixed spelling from "use" to "used"
> Fix typo in cocpy

- src/data/roadmaps/react/content/101-cli-tools/101-create-react-app.md
Added W3schools resource to learn react with create react app. w3schools does a pretty great job at explaining stuff.
> Add w3school content

- src/data/roadmaps/backend/backend.md
Adjusted copy for the Q "What does a Backend Developer do?"
> Update backend - adjusted copy

- src/data/roadmaps/frontend/content/110-build-tools/100-task-runners/index.md
add bun for running package.json scripts
> Add Bun as a task runner

- src/data/roadmaps/golang/content/101-go-advanced/110-scheduler.md
- src/data/roadmaps/golang/golang.json
Added Go Schedular node and content at the request of @nikzayn
https://github.com/kamranahmedse/developer-roadmap/assets/25537601/a92a547e-5bb6-4afc-9967-f01936f84edd
> Add go schedular content and roadmap node

- src/data/roadmaps/javascript/content/102-javascript-datatypes/102-typeof-operator.md
Improved the definition of typeof operator.
> Improve 102-typeof-operator.md definition

- src/data/roadmaps/cpp/content/105-pointers-and-references/index.md
Just adjusted a space, now it's more readable
> Correct C++ indentation standard

- src/data/roadmaps/cpp/content/105-pointers-and-references/index.md
> Update C++ snippet to correct indentation

- src/data/roadmaps/javascript/content/108-javascript-expressions-and-operators/104-logical-operators.md
> Fix Javascript logical operators resources

- src/data/roadmaps/frontend/frontend-beginner.json
- src/data/roadmaps/frontend/frontend.json
- src/data/roadmaps/full-stack/full-stack.json
- src/data/roadmaps/react/react.json
Solve Tailwind > TailwindCSS #4526
> Solve Tailwind > TailwindCSS

- src/data/roadmaps/backend/content/104-version-control-systems/101-git.md
backend-roadmap-git-new-link
introduction to git : #4561
> backend-roadmap-git

- src/data/roadmaps/backend/content/103-learn-a-language/106-python.md
Updating Codecademy Python course to the course for version 3: https://www.codecademy.com/learn/learn-python-3
> Suggest python 3 in backend roadmap

- src/data/roadmaps/flutter/content/100-dart-basics/105-control-flow-statements.md
It felt appropriate to add a link to Loops in Dart as loops are discussed in the main section on Control Flow Statements.
> Added link to Loops in Dart

- src/data/roadmaps/python/content/102-python-advanced-topics/100-oop/100-methods-dunder.md
Add `__` for dunder methods listed in example.
> Add underscore for dunder methods.

- src/data/roadmaps/backend/content/123-scalability/100-mitigation-strategies/104-circuit-breaker.md
New circuit breaker resource: https://mateus4k.github.io/posts/circuit-breakers/
> feat(backend): add new resource to circuit breaker

- src/data/roadmaps/system-design/content/112-caching/100-client-caching.md
Adding HTTP Caching article from mozilla.org.
> Add HTTP Caching article from mozilla.org

- src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
Removed link - Dosen't belong to this section "How JVM Works"
> removed unwanted link

- src/data/roadmaps/computer-science/content/111-design-patterns/index.md
Refactoring Guru added to the computer science roadmap Design Patterns section.
> Refactoring Guru in the Design Patterns section

- src/pages/signup.astro
> fix(signup.astro): typo unnecessary "videos" word

- src/data/roadmaps/javascript/content/101-javascript-variables/101-hoisting.md
javascript-roadmap-hoisting - newvideo-link-added
fixes: #5066
> javascript-roadmap-hoisting

- src/data/roadmaps/backend/content/103-learn-a-language/100-go.md
Resolving suggestion (issue) [#5082](https://github.com/kamranahmedse/developer-roadmap/issues/5082)
Introducing Go Class by Matt
Go Class is a Youtube series designed to be beginner-friendly and covers topics such as data types, control structures, functions, pointers, concurrency, Go channels, modules, testing and more.
> Added Go class by Matt to Backend/Learn a language - Go resources

- src/data/roadmaps/blockchain/content/110-building-for-scale/102-zero-knowledge-rollups-and-zero-knowledge-proof.md
> Fix broken link

- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/101-printing-output/index.md
Update index.md of 'Printing output' in NodeJs Roadmap
> Update index.md of 'Printing output' in NodeJs Roadmap

- src/data/roadmaps/frontend/content/110-build-tools/100-task-runners/index.md
> docs(task-runners): refined README description and added additional learning resource

- src/data/roadmaps/postgresql-dba/content/102-rdbms-concepts/100-object-model/106-queries.md
> Added CROSS JOIN type

- src/data/roadmaps/golang/content/100-go-basics/index.md
Specified link for W3 Schools' Golang tutorial to add clarity
> Specified link for W3 Schools' Golang tutorial to add clarity

- src/data/question-groups/javascript/content/append-child-vs-insert-before.md
Fixed the incorrect variable name in the first code example given in the answer
> Fix small bug in code example

- src/data/roadmaps/frontend/content/118-server-side-rendering/100-react-js/100-next-js.md
Added an up-to-date video tutorial by Lee Robinson
> Add up to date resource to learn Next.js

- src/data/best-practices/frontend-performance/content/minimize-http-requests.md
existing URL points to unavailable resources. I provided a more reliable URL with very good insight to the topic. Updated description to include a little more context providing enough heads up before visiting the URL to read the details
> fix: broken url in minimize-http-requests.md

- src/data/roadmaps/flutter/content/106-design-principles/103-oop.md
A more in-depth overview of OOP concepts, explaining the main principles of OOP.
> Add a video resource to 103-oop.md

- src/data/roadmaps/angular/content/101-rxjs-basics/102-marble-diagrams.md
Hello !
I added 2 videos explainning about Marble diagrams. I thinh they helpfull
> ADD: Videos explainning how marble diagrams works

- src/data/guides/frontend-languages.md
Updated with optimised og image
> Updated og image

- readme.md
- src/pages/index.astro
- Updated readme.md file with `cd developer-roadmap` command to move into that folder before running further npm command.
> Minor update in readme.md file

- src/data/roadmaps/vue/content/102-ecosystem/101-forms/100-formkit.md
The old formkit domain has been changed to a new one
> Update 100-formkit.md (fix broken link)

- src/data/roadmaps/sql/content/102-ddl/103-drop-table.md
- src/data/roadmaps/sql/sql.json
DROP table was the only DDL operation missing, and one that should be known.
> add DROP table sub-topic

- src/data/roadmaps/computer-science/content/103-asymptotic-notation/103-common-runtimes/104-exponential.md
There's a mistake in the example that has been provided.  According to the complexity analysis, the current example yields the exponential time complexity, not the previous one.
The recurrence relations:
- Previous: $T(n) = T (n - 1) + O(1) \rightarrow O(n)$
- Current : $T(n) = 2\cdot T(n - 1) + O(1) \rightarrow O(2^n)$
> Change of content in 104-exponential.md

- src/components/Navigation/Navigation.astro
https://github.com/kamranahmedse/developer-roadmap/assets/25537601/dae35572-a398-4d48-aca2-90f5bf79f96a
> Highlight Teams Navigation item over AI item

- src/data/roadmaps/computer-science/content/103-asymptotic-notation/103-common-runtimes/105-factorial.md
the original sample code's complexity is O(n) instead of O(n!)
> modify the sample code

- contributing.md
Added new develop branch rules as well as how to create a branch off the develop branch.
> update contribution doc with develop rules

- src/components/TopicDetail/TopicProgressButton.tsx
This will not close the Topic Details when updating status to "In Progress"
> Fix "In Progress" #5730

- src/data/roadmaps/angular/content/102-angular-basics/101-angular-components.md
> add links to angular section

- src/data/roadmaps/ios/content/cocoa-touch@leozxW-5fAOfkKbQM4FD1.md
- src/data/roadmaps/ios/content/core-os@IdGdLNgJI3WmONEFsMq-d.md
- src/data/roadmaps/ios/content/core-services@LHM7gNgTtfn_QDW-oQskD.md
Add copy and links to the **Core OS**, **Core Services** & **Cocoa Touch** topics.
> add copy and links to architecture topics

- src/data/roadmaps/angular/content/104-templates/101-property-binding.md
Update 101-property-binding.md
> Update 101-property-binding.md to most recent link

- src/data/roadmaps/api-design/content/api-security@qIJ6dUppjAjOTA8eQbp0n.md
Added a link to OWASP API Security Top 10 which lists 10, major problems with API security. It is a good resource to understand API security and the problems associated with it.
> added content to api security

- src/data/roadmaps/ios/content/functional-programming@Pj-hqRZUmwx1WhmTbLoFD.md
- src/data/roadmaps/ios/content/git@QifWR7WSJJTcTK2IfczxG.md
- src/data/roadmaps/ios/content/github@U_xXGSFF5iibQ4VkzPAWf.md
- src/data/roadmaps/ios/content/oop@FoqlB7xBIrV4yUp4ReBkw.md
Added content to `Core Programming Concepts` & `Version Control`
> Add iOS content 

- .astro/settings.json
- src/data/guides/how-to-become-devops-engineer.md
- src/pages/devops/how-to-become-devops-engineer.astro
Added new guide "How to become DevOps Engineer in 2024.
Set date as tomorrow as it's late in the day.
https://github.com/kamranahmedse/developer-roadmap/assets/25537601/919ebd05-bea0-44ef-8bae-850ddf4e5a00
> Add how to become devops engineer guide

- src/data/roadmaps/typescript/content/114-ecosystem/103-build-tools.md
see https://github.com/egoist/tsup/issues/1134
> docs(typescript/build-tools): update tsup link

- readme.md
Added the newly created product manager roadmap to the readme.md.
> Add Product Manager Roadmap to readme.md

- src/data/guides/devops-vs-sre.md
- src/pages/devops/devops-vs-sre.astro
Added the new DevOps vs SRE guide.
> add devops vs sre guide

- src/data/roadmaps/ios/content/av-foundation@UKgiSQvR9cryQT50t7riZ.md
- src/data/roadmaps/ios/content/core-animation@KpcmuLWX0xAjz6ty4ebtB.md
- src/data/roadmaps/ios/content/core-audio@4bAABCfTvxchS5C5NlAro.md
- src/data/roadmaps/ios/content/core-graphics@kRE9xT3mT9Si4NwJr9yGi.md
- src/data/roadmaps/ios/content/core-image@6zE_M0_oVpwW0B9qFSRgP.md
- src/data/roadmaps/ios/content/installing@R8LdFpfyS0MFYJuMLk8RG.md
- src/data/roadmaps/ios/content/meta@5VguZoP4h40rTWkxWxaxU.md
- src/data/roadmaps/ios/content/new-project@BJgoAgH85U6S3RtXq7hHV.md
- src/data/roadmaps/ios/content/preferences@SeGfULWFR7ufdv4U9Db3F.md
- src/data/roadmaps/ios/content/xcode@la5M4VoH79bhnN8qj5Izp.md
Added a short copy and a minimum of two links to the following topics:
- AVFoundation
- Core Audio
- Core Graphics
- Core Animation
- Core Image
- Xcode
> Add iOS media layer topic content

- src/data/roadmaps/javascript/content/112-javascript-asynchronous-javascript/index.md
Added links to two videos for better understanding. One video features comprehensive and visually appealing content, while the other from JSConf provides visuals suited for beginners.
> Update JavaScript-asynchronous resources

- src/data/roadmaps/javascript/content/112-javascript-asynchronous-javascript/104-promises/index.md
- src/data/roadmaps/javascript/content/117-javascript-chrome-dev-tools/101-debugging-memory-leaks.md
- src/data/roadmaps/javascript/content/117-javascript-chrome-dev-tools/102-debugging-performance.md
- src/data/roadmaps/javascript/content/118-working-with-apis/index.md
Update JavaScript-asynchronous Promises resources
Replaced a broken link in the Javascript/Working-With-APIs
> Fix and Update JavaScript Recourses Links

- src/data/roadmaps/java/content/100-java-fundamentals/101-data-types-variables.md
Closing this issue : https://github.com/kamranahmedse/developer-roadmap/issues/5939
> Java roadmap - added enum and records

- src/data/roadmaps/computer-science/content/101-pick-a-language/100-c-plus-plus.md
This pull request updates the C++ resources section in the Computer Science roadmap -> pick a language -> C++ documentation. The changes include adding a new resource link and correcting an existing typos and link to ensure users have access to accurate and useful information for learning C++.
Added a New Resource: Added a link to https://cplusplus.com, a comprehensive resource for C++ programming.
Corrected an Existing Link: Updated the link text for feed from C to C++ to ensure it accurately reflects the resource.
> Add and correct links in C++ resources section

- src/data/roadmaps/java/content/100-java-fundamentals/106-files-and-apis.md
added newer Files.* API with articles
> Java roadmap - Added newer Files.* API for reading Files

- src/data/roadmaps/datastructures-and-algorithms/content/103-basic-data-structures/101-linked-lists.md
- src/data/roadmaps/datastructures-and-algorithms/content/103-basic-data-structures/102-stacks.md
- src/data/roadmaps/datastructures-and-algorithms/content/103-basic-data-structures/103-queues.md
- src/data/roadmaps/datastructures-and-algorithms/content/103-basic-data-structures/104-hash-tables.md
Added Python linked list video link.
> DRAFT: Added link(s) for DSA Roadmap

- src/data/roadmaps/cpp/content/101-setting-up/100-installing.md
- src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md
- src/data/roadmaps/cpp/content/101-setting-up/index.md
- src/data/roadmaps/cpp/content/102-basic-operations/101-logical-operators.md
- src/data/roadmaps/cpp/content/102-basic-operations/102-loops.md
- src/data/roadmaps/cpp/content/103-functions/index.md
- src/data/roadmaps/cpp/content/104-data-types/index.md
- src/data/roadmaps/cpp/content/105-pointers-and-references/100-references.md
- src/data/roadmaps/cpp/content/107-structures-and-classes/101-oop/100-static-polymorphism/overloading-functions.md
- src/data/roadmaps/cpp/content/108-exception-handling/100-exceptions/index.md
- src/data/roadmaps/cpp/content/109-language-concepts/index.md
- src/data/roadmaps/cpp/content/114-debuggers/100-debugger-messages.md
- src/data/roadmaps/cpp/content/libraries/102-poco.md
I have corrected and improved some things in the C++ roadmap.
Here are the major changes I have made:
---
[100-installing.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/100-installing.md) and [101-setting-up/index.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/index.md)
- MinGW is not a compiler
[101-code-editors.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md)
- Mention Visual Studio here
- Vscode has no built-in support for C++, only extensions
[103-functions/index.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/cpp/content/103-functions/ind …
> Corrected / Improved C++ roadmap

- src/data/roadmaps/linux/content/103-working-with-files/100-permissions.md
Add a link to an itsfoss.com article and a popular YouTube video by Travis Media.
> add linux permissions article and video

- src/data/roadmaps/data-analyst/content/108-descriptive-analysis/102-distribution-shape/100-skewness.md
This is a simple and useful article, which I think might be very useful for understanding the concept of skewness.
> Addition: [roadmaps/DataAnalyst] Add article for Skewness

- src/data/roadmaps/data-analyst/content/108-descriptive-analysis/102-distribution-shape/101-kurtosis.md
Add a link (article) that describes the topic of Kurtosis, and I think it might be useful to understanding the concept better.
> Addition: [roadmaps/DataAnalyst] Add article for Kurtosis

- src/data/roadmaps/flutter/content/116-flutter-internals/index.md
Added the Flutter Article for Flutter Internals. 
As discussed with @dansholds 
Under Issue #5987
> feat: Added Article for flutter internals

- src/data/roadmaps/data-analyst/content/110-statistical-analysis/101-correlation-analysis.md
Just add an article for Correlation Analysis.
> Addition: [roadmaps/DataAnalyst] Add article for Correlation Analysis

- src/data/roadmaps/blockchain/content/109-dapps/108-client-libraries/index.md
> Add viem library to blockchain roadmap (#5975)

- src/data/roadmaps/datastructures-and-algorithms/content/102-data-structures/100-what-are-datastructures.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/103-quick-sort.md
This MR updates the links for
102 | Data Structures
103| Quick Sort
> DSA Roadmap | Updated Links for 102 & 105

- src/data/roadmaps/ios/content/concurrency@-aLGB3cDXZHIhVU3t-Ve4.md
Add first part of description of Concurrency in Swift by Apple.
> Concurrency in Swift by Apple

- src/data/roadmaps/api-design/content/api-security@qIJ6dUppjAjOTA8eQbp0n.md
- src/data/roadmaps/backend/content/server-security@TZ0BWOENPv6pQm8qYB8Ow.md
- src/data/roadmaps/cyber-security/content/103-security-skills-and-knowledge/100-cryptography/index.md
I found some great articles which I believe can be put up in the above mentioned three topics as a resource.
I have attached their links in the commit changes, however I am dropping them below as well for a quick reference. I request if they can be made a part of this.
links - <br>
- [API and Cyber Security Article (one for the two topics, I think it sits well)](https://www.freecodecamp.org/news/hmac-diffie-hellman-in-node/)
- [Server Security Article](https://www.freecodecamp.org/news/defending-against-ssrf-attacks/)
@dansholds @kamranahmedse  kindly take a look at them and let me know what you think.
> Articles on API security, server security and cyber security

- src/data/roadmaps/frontend/frontend.json
Simple issue to fix, FS roadmap link was set to nodejs roadmap not FS.
> correct FS link to FS roadmap rather than nodejs

- src/data/roadmaps/api-design/api-design.json
> fix: label line break

- src/data/question-groups/react/react.md
Hi team, just found some typos and grammar errors in the react.md. 
Please review, thanks!
> chore(docs): fix typos and grammar errors for react.md

- src/data/roadmaps/backend/content/javascript@8-lO-v6jCYYoklEJXULxN.md
- src/data/roadmaps/nodejs/content/102-nodejs-npm/100-npx.md
- src/data/roadmaps/nodejs/content/102-nodejs-npm/104-running-scripts.md
- src/data/roadmaps/nodejs/content/102-nodejs-npm/105-npm-workspaces.md
- src/data/roadmaps/nodejs/content/103-nodejs-error-handling/101-using-debugger.md
- src/data/roadmaps/nodejs/content/103-nodejs-error-handling/102-uncaught-exceptions.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/100-event-loop.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/102-promises.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/103-async-await.md
- src/data/roadmaps/nodejs/content/105-nodejs-working-with-files/101-path-module.md
- src/data/roadmaps/react-native/content/111-security/index.md
Corrected type tags and links, formatted content text, and added new links.
> Roadmap: MORE Node.js Resources Updates and Fixes for Nearly 1/2 the Roadmap

- src/data/roadmaps/terraform/content/version-management@6zFuSNOfbPaYIE_t--2nr.md
- src/data/roadmaps/terraform/terraform.json
As requested in #6021 , I have added a subtopic for Version Management in the Scaling Terraform topic. 
As projects grow, and as companies start to work with multiple terraform projects rather than a single, modern one, version management can become required if the company do not wish to keep all projects up the date with the latest version of terraform.
> add version management subtopic

- src/data/roadmaps/react/content/103-rendering/105-high-order-components.md
- src/data/roadmaps/react/content/106-state-management/101-zustand.md
This pull request adds a new video tutorial for the State-management topic, focusing on Zustand, a lightweight and flexible state-management library for React applications. The tutorial is designed to help developers understand and implement Zustand in their projects, providing a comprehensive guide to its core concepts and practical usage.
Changes Included:
- New Video Tutorial: Added a detailed video tutorial on Zustand to the State-management section.
> Added Zustand video tutorial for State-management topic

- src/data/roadmaps/ios/content/combine@UzpdLLPs226N00c6weWRv.md
- src/data/roadmaps/ios/content/navigation-stacks@TLm70PlTI0K3Odn1iYxWX.md
Hey there!
This PR includes content (documentation + video tutorial links), as well as a brief description to NavigationStack and Combine. I couldn't find any guides on PR structure, so I hope this is fine.
I hope it helps!
> Add Combine & NavigationStack content to the iOS roadmap

- src/data/roadmaps/datastructures-and-algorithms/content/102-data-structures/100-what-are-datastructures.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/100-bubble-sort.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/101-merge-sort.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/103-quick-sort.md
This MR update links on 105
- Quick Sort
- Merge Sort
- Bubble Sort
> DSA | Updated 105, Sorting Algorithm links

- src/data/roadmaps/ios/content/architectural-patterns@ajPGMwoaFb1UFWTtpi5kd.md
- src/data/roadmaps/ios/content/async--await-in-swift@3GtrUXvLgvXK3G8cXRb-P.md
- src/data/roadmaps/ios/content/basic-interfaces@0o3V_zveN1xCIt7rayrCF.md
- src/data/roadmaps/ios/content/basics--creating-animations@w0i5Dxp40XS2HnF5nXeZI.md
- src/data/roadmaps/ios/content/components@A1TFKVjGU5RbeTF_zxJlu.md
- src/data/roadmaps/ios/content/concurrency-gcd-asyncawait@aALIiAxKz4f7B_EYyhBCi.md
- src/data/roadmaps/ios/content/core-programming-concepts@mk02yV7_XHkgp2xdNIxaU.md
- src/data/roadmaps/ios/content/error-handling@N5ojp6bqgH074MPKYjCHV.md
- src/data/roadmaps/ios/content/media@nGCG74_Xp_Ngt0u7PZnZl.md
- src/data/roadmaps/ios/content/mvp@lVNrnUK6p4eifKRVSnOje.md
- src/data/roadmaps/ios/content/mvvm-c@iLT2jAkQg-Ex0zSLquNfl.md
- src/data/roadmaps/ios/content/mvvm@taTxZw2c3xS18JOwgkNHM.md
- src/data/roadmaps/ios/content/navigation-view@IBr2P7dknWTnZ2a-fFCqN.md
- src/data/roadmaps/ios/content/navigationlink@my77jLU2qxU7bQ7_Fx2iH.md
- src/data/roadmaps/ios/content/presenting--dismissing-views@4pmjLa7WvwV7D3RZlM6Hp.md
- src/data/roadmaps/ios/content/swiftui@kAIKsDcDzwI1E0wSnC_uo.md
- src/data/roadmaps/ios/content/tca@NhC0SBZgUFGjMLNICvbTI.md
- src/data/roadmaps/ios/content/uikit@-7OW2IgiMk1eot1PaYd7m.md
- src/data/roadmaps/ios/content/user-interactions@GKuxilB0AwjcTgCSk3FeU.md
- src/data/roadmaps/ios/content/version-control@sGnDm2xuJxqfU3pwmlY7H.md
- src/data/roadmaps/ios/content/view-controllers@mfWdkUm1RhjygtMyInXiD.md
- src/data/roadmaps/ios/content/view-transitions@cwVcNDTBBulBY2m4Wzn4G.md
- src/data/roadmaps/ios/content/viewcontroller-lifecycle@DZaY060-5D6PbfryOZH9H.md
- src/data/roadmaps/ios/content/views@se9w7mT1XJLGlmWUhH4Uv.md
- src/data/roadmaps/ios/content/viper@mTdnDPGYSDupM9VBNdXRg.md
- src/data/roadmaps/ios/content/xibs@RwvC4Pi18_1phcrJL-9iu.md
Completed various topics around architecture, animation, UIKit and SwiftUI.
Putting this PR up to prevent it getting too big.
> Add iOS copy and links

- src/data/roadmaps/angular/content/106-forms/index.md
removed link to article was about angularjs version
> fix(roadmap/angular): remove outdated article about angular forms

- contributing.md
- src/data/roadmaps/android/android.json
- src/data/roadmaps/backend/backend.json
- src/data/roadmaps/blockchain/blockchain.json
- src/data/roadmaps/devops/devops.json
- src/data/roadmaps/frontend/frontend.json
- src/data/roadmaps/qa/qa.json
Updated the following items based on issue https://github.com/kamranahmedse/developer-roadmap/issues/6081 :
- android.json
- Replace 'BitBucket' with 'Bitbucket'
- backend.json
- Replace 'Github' with 'GitHub'
- Replace 'Repo hosting services' with 'Repo Hosting Services'
- blockchain.json
- Replace 'BitBucket' with 'Bitbucket'
- devops.json
- Replace 'VCS Hosting' with 'Repo Hosting Services'
- Replace 'BitBucket' with 'Bitbucket'
- frontend.json
- Replace 'VCS Hosting' with 'Repo Hosting Services'
- qa.json
- Replace 'BitBucket' with 'Bitbucket'
- contributing.md
- Changed "None English content." to "Non-English content."
> Update capitalizations and replace VCS Hosting w/Repo Hosting Services

- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/101-printing-output/100-process-stdout.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/101-printing-output/101-process-stderr.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/101-printing-output/102-chalk.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/102-taking-input/100-process-stdin.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/103-command-line-args/100-process-argv.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/103-command-line-args/index.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/104-environment-variables/100-dotenv.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/104-environment-variables/101-process-env.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/104-environment-variables/index.md
- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/index.md
fixed wrong resource links, formatted, edited, and added content text and new resources.
> Updates on 106-nodejs-command-line-apps

- src/data/roadmaps/nodejs/content/106-nodejs-command-line-apps/101-printing-output/index.md
Tried to adapt it based on issue #6085
> Adding console.* and more recources to 106-nodejs-command-line-apps

- src/data/roadmaps/api-design/api-design.json
The ID and OldId where the wrong way around, Id now read the same as the file ID
> fix incorrect Id on SOAP api

- src/components/FrameRenderer/renderer.ts
> fix: checkbox right click

- src/data/roadmaps/devrel/content/advocacy@7MCmY1bABGPfmzjErADvg.md
- src/data/roadmaps/devrel/content/community-support@1NFcpGzCJylRPbFYdD9bB.md
- src/data/roadmaps/devrel/content/content-creation@_3ZnPUl4kzzuM0bKQ8IAq.md
- src/data/roadmaps/devrel/content/developer-experience@No-UnhdGmtLW9uFGLy-ca.md
- src/data/roadmaps/devrel/content/developer-journey@BooGiYTMoS0N5eobwjPHY.md
- src/data/roadmaps/devrel/content/developer-marketing@UhMk8g5MMhvi3kWLLI6B1.md
- src/data/roadmaps/devrel/content/education@EjqJkyojhO7f1uFHIoyGY.md
- src/data/roadmaps/devrel/content/feedback-loop@IxRvVvX9Fax08YUbVob4s.md
- src/data/roadmaps/devrel/content/history-and-evolution@KP28dl1I9hxM130gIPxSZ.md
- src/data/roadmaps/devrel/content/importance-of-devrel@N9HXTCQq2wfC-QurSofE_.md
- src/data/roadmaps/devrel/content/what-is-devrel@SiYUdtYMDImRPmV2_XPkH.md
Added copy and content to all of the "What is DevRel" topics.
> completed the introduction section content

- src/data/roadmaps/devops/content/netlify@hCKODV2b_l2uPit0YeP1M.md
Add description and links relating to Netlify Functions
> Add description and links relating to Netlify Functions in DevOps roadmap

- src/data/roadmaps/sql/content/100-introduction/102-sql-vs-nosql.md
- src/data/roadmaps/system-design/content/111-databases/102-sql-vs-nosql.md
Wanted to also make sure is there some guidance on similar content? Should those 2 files be copies of the same content? Or is there some other approach
> FIx links for sql vs nosql in system-design and sql roadmaps

- src/data/roadmaps/ios/content/combine-and-mvvm@pY_zaMcFpeFDLgVk2W0Vy.md
- src/data/roadmaps/ios/content/components@xkH7Llut6uP2-8iTMw76F.md
- src/data/roadmaps/ios/content/data-binding@yR94uHs0SiSScU4gPBzfr.md
- src/data/roadmaps/ios/content/declarative-syntax@QVg4_8EXeQBJbleryy8c1.md
- src/data/roadmaps/ios/content/modals-and-navigation@jb89kQxDhZND3vQo0EH7r.md
- src/data/roadmaps/ios/content/navigation-controllers-segues@tUbMr1pGlw4JwMuW311JJ.md
- src/data/roadmaps/ios/content/navigation-stacks@mUMDZsgzCB6cs_K6pfUY1.md
- src/data/roadmaps/ios/content/observables--observers@k232wKg7XCb_ngjZ5Mwsy.md
- src/data/roadmaps/ios/content/operators--pipelines@GAn12SsVR_mPxOaOVckdz.md
- src/data/roadmaps/ios/content/operators@t7IYTY8tVjC_xzM1n8wts.md
- src/data/roadmaps/ios/content/publishers--subscribers@noBaDV_PvCTzqPyw9eO4H.md
- src/data/roadmaps/ios/content/pushing-presenting@gqd6zjxP_qFj4Ru-6LARo.md
- src/data/roadmaps/ios/content/reactive-programming@28HMXXBJWd3n-ZPgeQRDa.md
- src/data/roadmaps/ios/content/rxswift-with-mvvm@g_1f5a6tIB5V_36NjgtL5.md
- src/data/roadmaps/ios/content/rxswift@0xwoWj9jek36p1AwU3WkK.md
- src/data/roadmaps/ios/content/schedulers@UqA01PT86_w_JzN6KZBku.md
- src/data/roadmaps/ios/content/state-management@RvyOkQelc-GChQGJyEx72.md
- src/data/roadmaps/ios/content/subjects@1xYZdnlI6JSJzNvmz4-0v.md
- src/data/roadmaps/ios/content/ui-design@4fPgpGwNXmVoZoruBRb_B.md
- src/data/roadmaps/ios/content/views-view-controllers@XX5rCd_yTHvOfYif4Kpbl.md
Completed 20 topics around UIKit, SwiftUI, and reactive programming.
> add swiftui, uikit & reactive programming content

- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/110-linked-list.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/111-binary-heap.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/112-stack.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/113-queue.md
> Fix link labels

- src/data/roadmaps/angular/content/107-routing/104-guards.md
- remove deprecated `canLoad` angular guard
- change the description to use functional guards
> fix(roadmaps/angular): guards roadmap information 

- src/data/roadmaps/devops/devops-beginner.json
Fix small typo in DevOps Beginner Roadmap.
> Fix small typo in devops beginner roadmap intro text

- src/components/UpdateProfile/ProfileUsername.tsx
> fix: username input validation

- src/components/AuthenticationFlow/TriggerVerifyEmail.tsx
- Removed a duplicate full stop from text displayed to the user during verifying email flow.
> Fix punctuation in Verify Email flow

- src/data/roadmaps/cyber-security/content/103-security-skills-and-knowledge/108-authentication-vs-authorization.md
> correct styling of content i.e. links to the bottom

- src/data/roadmaps/backend/content/ssltls@0v3OsaghJEGHeXX0c5kqn.md
Very simple and newbie friendly explanation of TLS handshake
The video is short (5 min), yet informative. All unnecessary details (such as cipher algorithms in specific protocol version) are hidden, necessary details are mentioned (e.g. why to switch to symmetric encryption).
> Add ssl/tls explanation video 

- src/data/roadmaps/java/content/100-java-fundamentals/101-data-types-variables.md
changed typo from Rerords -> Records
> (Typo) Update 101-data-types-variables.md

- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/100-bubble-sort.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/101-merge-sort.md
- src/data/roadmaps/datastructures-and-algorithms/content/105-sorting-algorithms/103-quick-sort.md
Hi! I found a recurring mistake in the word «visualization», I suggest correcting it.
> Fix grammar in sorting algorithms articles

- src/data/roadmaps/javascript/content/102-javascript-datatypes/101-object/100-prototype.md
Adding a youtube video for understanding concept of prototype in javascript and Object prototype and Prototype Inheritance.
> Feature - updating content of  100-prototype.md

- src/data/roadmaps/product-manager/content/discovery@vP4tfzP-hOiAsv4K4RsQy.md
Added video URL on Product Management Discovery content page
> Added video URL on Product Management Discovery content page

- src/data/roadmaps/devrel/content/writing-skills@0ntOE6PSdMl_EXB9gdgIv.md
* Enhanced the explanation of the importance of good writing skills for software developers
* Added three resources for further reading on effective communication and documentation
> Improve "Update writing-skills" section and add additional resources

- src/data/roadmaps/angular/content/115-testing-angular-apps/100-testing-pipes.md
I made copy changes as I felt it did not follow the structure.
> Changes in copy testing pipes angular

- src/data/guides/java-developer-skills.md
Updated as per Ed's instructions.
> update java/developer-skills guide

- src/data/guides/frontend-languages.md
updated the guide and added all the images to back office.
> Update frontend languages guide

- src/data/roadmaps/cyber-security/content/gtfobins@Jd9t8e9r29dHRsN40dDOk.md
- src/data/roadmaps/cyber-security/content/wadcoms@Rnpx7VkhrBkSQTni6UuTR.md
- src/data/roadmaps/cyber-security/cyber-security.json
Two new topics were added to the "Using Tools for Unintended Purposes" section.
- WADCOMS
- GTFOBINS
Satisfies #6210
> add wadcoms, gtfobins

- src/data/roadmaps/javascript/content/@lJwcc6JoUIQoiQ6FkV2KW.md
Update @lJwcc6JoUIQoiQ6FkV2KW.md
> Update Js Roadmap Strict Equality Operator ===

- src/data/roadmaps/cyber-security/content/dns@ORIdKG8H97VkBUYpiDtXf.md
- src/data/roadmaps/cyber-security/content/dns@r1IKvhpwg2umazLGlQZL1.md
- src/data/roadmaps/cyber-security/content/understand-cia-triad@uz6ELaLEu9U4fHVfnQiOa.md
Fix the YouTube video link error and update the video…
> Update dns.md 

- src/data/guides/how-to-become-devops-engineer.md
Updated as per Ed's intructions.
> update how to become a devops engineer guide

- src/data/guides/devops-vs-sre.md
Updated as per Ed's instructions.
> update devops vs sre guide

- src/data/roadmaps/react/content/usecallback@2zrN65JZhCyNimi33g78f.md
This pull request adds a detailed explanation of the useCallback hook in the React section of the roadmap.sh documentation. The new content covers the purpose and usage of useCallback, emphasizing its role in optimizing performance by preventing unnecessary function recreations and component re-renders. This addition aims to provide a clearer understanding for developers, especially those new to React, on how to effectively use this hook in their projects.
Changes include:
A new section under the React Hooks topic, specifically focused on useCallback.
Examples illustrating typical use cases and scenarios where useCallback can enhance performance.
Clarifications on common misconceptions and best practices for using useCallback.
Please review the changes and provide feedback. Thank you!
> Update Detailed Explanation for useCallback Hook in React Documentation usecallback@2zrN65JZhCyNimi33g78f.md

- src/data/roadmaps/typescript/content/100-typescript/101-ts-js-interoperability.md
I worked with legacy JavaScript codebases and transitioning them to TypeScript. During this process, I discovered that TypeScript's compiler can also check plain JavaScript files, which I found quite noteworthy. I also created a video tutorial about it.
> Describe how TypeScript checks JavaScript files

- src/data/roadmaps/react/content/useref@t_laNdMmdLApYszqXRdWg.md
Added useRef documentation for React Developer Roadmap on roadmap.sh
> Updated useref@t_laNdMmdLApYszqXRdWg.md

- src/data/roadmaps/ios/content/data-binding@yR94uHs0SiSScU4gPBzfr.md
- src/data/roadmaps/ios/content/navigation@02VAK4GMkN6nDHf1zqwPA.md
- src/data/roadmaps/ios/content/state-management@RvyOkQelc-GChQGJyEx72.md
- src/data/roadmaps/ios/content/views-and-modifiers@mgUCYztUpKINqIZikT4Bh.md
adding Apple's Official Tutorials for SwiftUI and correcting typos in existing resources
> Adding new contents to SwiftUI

- src/data/roadmaps/golang/content/101-go-advanced/102-types-and-type-assertions.md
I updated the introductory content to Go types and type assertions and added more resources to help people understand the topic more.
> update Go types and type assertions

- src/data/roadmaps/react/content/usecontext@D5_O-uElftYGQr_bTU_se.md
- Rectified bullet point structure (earlier erroneous)
- Added a video tutorial for the same
> Improved usecontext@D5_O-uElftYGQr_bTU_se.md

- src/data/roadmaps/nodejs/content/hono@Xa-lA1wbZ9JZ_XpXfhhw5.md
This is the introduction to Hono and article reference.
> Add resource for Hono

- src/data/roadmaps/software-design-architecture/content/107-architectural-patterns/109-event-sourcing.md
The youtube video for event sourcing is no longer available, so I added an alternative.
> Update video for Event Sourcing (Design & Architecture)

- src/data/roadmaps/javascript/content/null@CxyNyFMuTLS3owtRMgClD.md
This pull request adds a description and some resources for `null` in JavaScript.
> Added Description and Resources for null in JavaScript

- src/data/roadmaps/angular/angular.json
- src/data/roadmaps/javascript/javascript.json
- src/data/roadmaps/nodejs/nodejs.json
- src/data/roadmaps/vue/vue.json
Several roadmap.sh links were broken in roadmaps.
> Fix links in roadmaps

- src/data/roadmaps/javascript/content/number@GZ_SXsWmP7AsXRTc4WUMw.md
Added Definition and Easy to Understand Examples for DataType Number.
> Update JavaScript Datatype -- Number

- src/data/roadmaps/angular/content/ngrx@ir94IdkF1tVAA8ZTD9r0N.md
Updated the NgRx content by removing the outdated videos, cleaning up some typos, and adding some videos that would be good for beginners to NgRx.
> docs: update ngrx content

- src/components/TopicDetail/TopicDetail.tsx
- src/lib/dom.ts
- tailwind.config.cjs
As per the video below, I noticed that when scrolling around the pull out UI the body scroll position was lost.
A bit annoying, seems like a simple fix.
Before:
https://github.com/user-attachments/assets/a349541c-1f54-415d-bdaa-8eb808749b80
After:
https://github.com/user-attachments/assets/ae49c77a-936b-4bf8-8118-956298050127
> Ensure when TopicDetail is open document.body stops scrolling

- src/data/roadmaps/angular/content/pipes-precedence@nZxZnzbQg9dz-SI65UHq9.md
> docs: add pipe precedence content angular

- src/data/roadmaps/frontend/content/notifications@6AlcArOiJMhHXguAosDzn.md
Hi! The link to the video in the notification block is broken. I found another video and updated the reference.
> Updates notifications@6AlcArOiJMhHXguAosDzn.md video reference

- src/data/roadmaps/api-design/api-design.json
- src/data/roadmaps/api-design/content/rate-limiting@O7wjldZ3yTA2s_F-UnJw_.md
- created rate-limiting file that topic was looking for.
- added missing links to blue buttons.
> fix api-design topics not found

- src/data/roadmaps/angular/content/imports@ghbrJhuGvscnNGCtVLh5_.md
- src/data/roadmaps/angular/content/metadata@Szgr8dnZNi-z5i6raIJzW.md
- src/data/roadmaps/angular/content/provider@dOMvz__EQjO-3p-Nzm-7P.md
- src/data/roadmaps/angular/content/selector@cDN0PGo-zkcLmttxCiAI-.md
- src/data/roadmaps/angular/content/standalone@RcNHEh6kmbBK1PICbhAwr.md
- src/data/roadmaps/angular/content/styles@4XJKEmSrQfPxggHlAP30w.md
- src/data/roadmaps/angular/content/template@-gUpm3OLUJl9iAyx6fmHN.md
Threads:
- Metadata
- Selector
- Template
- Styles
- Standalone
- Imports
- Provider
> feat(angular/metadata): add content to the threads

- src/data/roadmaps/nodejs/content/fetch@B_3rTGQxJneMREXoi2gQn.md
Added content to empty roadmap node, describing the functionality of fetch as a stable native API in Node.js as of Node v21 with examples and additional resources for further reading.
> Add content to empty node in "Node.js Developer - Step by step guide to becoming a modern Node.js developer in 2024"

- src/data/roadmaps/angular/content/changedetection@uYHy2yhtTm6fQkKpYx3lU.md
- src/data/roadmaps/angular/content/encapsulation@ctigvSYeFa77y3v7m11gk.md
- src/data/roadmaps/angular/content/viewprovider@doHDoAgp7T59KGSXPpQzZ.md
Add conent to: 
- viewProvider
- Encapsulation
- changeDetection
> feat(angular/metadata): add content to the thread

- src/data/roadmaps/react/content/usememo@w3bNp7OkehI1gjx8NzlC8.md
> Add one great resource to useMemo hook

- src/data/roadmaps/vue/content/v-show@_TlbGTKFCMO0wdLbC6xHX.md
Adds a brief explanation of `v-show` in comparison to `v-if` and links to the official docs.
> feat: add content to v-show on vue roadmap

- src/data/roadmaps/ios/content/core-animation@_mRs6ctH0IsSSi-cwV2b8.md
I've added a quick and useful description for the Core Animation section on the iOS Roadmap. 
If you find it useful, do merge. 
You're welcome and thanks!
> Add content for Core Animation (iOS)

- src/data/roadmaps/react/content/tanstack-router@zWL8VLx_g0SWubavJDs6i.md
Added description and some tutorials to Tanstack Router roadmap section
> Added Tanstack Router

- src/data/roadmaps/react/content/usereducer@v48Mv0wQqjXbvy8x6gDjQ.md
> Added Official & Articles for useReducer Hook

- src/data/roadmaps/angular/content/if@U1Zy2T-2ki9pDkXn9hn-I.md
@Kordrad I bungled the other PR, but I incorporated your feedback into this and maybe this is better and potentially setup to be expanded further later.
> docs(angular): add @if content

- src/data/roadmaps/angular/content/analogjs@kauQofxCmpktXPcnzid17.md
> fix: visit typo analogjs

- src/data/roadmaps/python/content/loops@Dvy7BnNzK55qbh_SgOk8m.md
added information in python loop
> Python LOOP Information

- src/data/roadmaps/react/content/ark-ui@kiCTo0U6VgNON8rv_Ktlj.md
**Updates**
<ul>
<li>
update the content
</li>
<li>
Added Official link
</li>
<li>
Added Video guide link
</li>
<li>
Added Article link
</li>
<li>
Added Get start link
</li>
</ul>
> update content of ark-ui@kiCTo0U6VgNON8rv_Ktlj.md

- src/data/roadmaps/devops/faqs.astro
Added copy approved by @Edlan01 and a link to the similarly titled guide.
> add 'what is the difference between SRE and DevOps' to roadmap FAQ

- src/data/roadmaps/system-design/content/112-caching/index.md
Added link to the topic for more exploration
> Updated caching links for further exploration of topic index.md

- src/data/roadmaps/frontend/content/fetch-api--ajax-xhr@A4brX0efjZ0FFPTB4r6U0.md
Minor update to fix the link on the Frontend Developer Roadmap under the Fetch API node.
> Fix broken link in Frontend Developer Roadmap

- src/data/roadmaps/javascript/content/boolean@b1HvkoWA2t4kt8mS6FySm.md
Update boolean@b1HvkoWA2t4kt8mS6FySm.md
> add Boolean content (JS)

- src/data/roadmaps/kubernetes/content/102-setting-up-kubernetes/102-deploying-your-first-application.md
Fixed broken link in Kubernetes Roadmap.
Related issue: https://github.com/kamranahmedse/developer-roadmap/issues/6343
> Fix broken link in Kubernetes Roadmap (#6343)

- src/data/roadmaps/angular/content/custom-validators@kxRtLsB3y_th8j-HjmJgK.md
Added content to custom validators topic in Angular
> Added content to custom-validators topic

- src/data/roadmaps/angular/content/dynamic-forms@CpufN6DAOj5UNab9vnH0k.md
I have added content and copy to the Dynamic Forms topic in the Angular roadmap.
> Add content to the dynamic forms topic

- src/data/roadmaps/javascript/content/callback-hell@PJSdqvh5OBwPCNpn3q_S5.md
Malicious link has been removed
> malicious link has been removed

- src/data/roadmaps/blockchain/blockchain.json
Typo: Change "**Centralized** Storage" to "**Decentralized** Storage"
> Update blockchain.json. Typo: "Centralized Storage" > "Decentralized Storage"

- src/data/roadmaps/javascript/content/objectis@ATma3bLKdmWY_WTsPIKxh.md
Added description to Object.is in the JavaScript roadmap before without content.
> Update object.is description in JavaScript Roadmap

- src/data/roadmaps/linux/content/107-user-management/100-create-update.md
- src/data/roadmaps/linux/content/107-user-management/101-user-groups.md
- src/data/roadmaps/linux/content/107-user-management/102-permissions.md
Wrangled content and added contents links to the three (3) sub-topics of **User Management**
> docs(linux): wrangle content and add content links to user management

- src/data/roadmaps/vue/content/v-if@xHj3W9Ig3MVuVlGyXchaP.md
`v-if ` conditional was documented for vue using the official documentation
> feat: add v-if documentation for Vue.js

- src/data/roadmaps/python/content/sets@soZFqivM3YBuljeX6PoaX.md
Python Sets article with video
> update Python Sets

- src/data/roadmaps/typescript/typescript.json
> fix: update path to backend roadmap

- src/data/roadmaps/cyber-security/cyber-security.json
> fix: typo in cyber-security

- src/data/roadmaps/cyber-security/content/phishing@7obusm5UtHwWMcMMEB3lt.md
- add some important information about phishing
- add some resources (articles and videos)
> add phishing details in the cybersecurity path

- src/data/roadmaps/golang/content/101-go-advanced/index.md
I've added an introduction to Go advance and included the relevant links
> Add advance Go intro

- src/data/roadmaps/android/content/mvp@aF_xFIqTjQbENtC7pkXvJ.md
Adding content to MVP Architectural patterns
> Docs(android): Add MVP content

- src/data/roadmaps/python/content/sets@soZFqivM3YBuljeX6PoaX.md
Ugh... okay, looks there was ANOTHER error in my last pull request... i think this fixed it??
Really sorry about this... just wanted to add some resources :P
I probably should have created an error for this but I panicked and did this in a rush as you can probably tell from the commit history
> Fix sets@soZFqivM3YBuljeX6PoaX.md

- src/data/roadmaps/git-github/content/basic-git-usage@PtU5Qwfzn3N1i3oRlCGoR.md
- src/data/roadmaps/git-github/content/collaboration@bXfCUG3h1TIFPgD4WUDph.md
- src/data/roadmaps/git-github/content/learn-the-basics@HlUUGj3dOZ68t4gIjerXh.md
- src/data/roadmaps/git-github/content/more-git@aZMVz6kc52vLGcZFD9Dgh.md
- src/data/roadmaps/git-github/content/more-github@sti_TAgZvSpuFWtygAsKc.md
Added content to Git and GitHub (for beginners) roadmap
> Git and GitHub (for beginners) - Add content to roadmap

- src/data/roadmaps/angular/content/component-lifecycle@nCpfj_35ZvW-NTygg06XZ.md
- src/data/roadmaps/angular/content/creating-modules@9YhTXybJw2gszlqFeBtW3.md
Clearly outlines the content and purpose of the guide, provides links for further reading, and emphasizes the benefits of using modules
> Guide on Creating and Managing Modules in Angular

- src/data/roadmaps/android/content/buttons@WhfzFOUpm0DFEj7Oeq21R.md
- src/data/roadmaps/android/content/dialogs@Mtx0bY0drmaTw8sCM5YTl.md
- src/data/roadmaps/android/content/fragments@2iDJrxjXOt7o2fPp2HfRl.md
Add content to Dialogs, fragments and Buttons
> [Add] Android roadmap: Add content to Dialogs, fragments and Buttons

- src/data/roadmaps/git-github/content/git-config@NMCWgzhhfUvFOMO5GbF_u.md
- src/data/roadmaps/git-github/content/git-init@1iOkbO5juk2LO-WZHx_W6.md
- src/data/roadmaps/git-github/content/gitignore@oz2oRAhaEQb0Fm3aRJQG8.md
The added content is as follows git init, git config and gitignore.
> Add content to git-github roadmap

- src/data/roadmaps/android/content/textview@znvZp24L-PcQwkSObtixs.md
- src/data/roadmaps/android/content/toast@BVgO9n7tGlVdiS72-hFSd.md
Add content to TextView and Toast
> [Add] Android Roadmap: Toast and TextView

- src/data/roadmaps/computer-science/computer-science.json
> Fix typo - "Cloud Design Ptterns" should be "Cloud Design Patterns"

- src/data/guides/devops-engineer.md
- src/data/roadmaps/devops/devops.md
- src/pages/devops/devops-engineer.astro
Formatted Article
Added link to the guide in the top FAQ of DevOps RM
> Add what is a devops engineer guide and add link in devops roadmap

- package-lock.json
- src/data/guides/how-to-become-frontend-developer.md
- src/pages/frontend/how-to-become-frontend-developer.astro
Completed along with self-hosted images on our CDN.
Also set to "isNew"
> How to become a Frontend Developer in 7 steps article

- src/data/roadmaps/git-github/content/post-checkout@SANEQI2rgOtsMQyn4qUCq.md
- src/data/roadmaps/git-github/content/post-update@buxb5TpzQ-xxn0vqtGdS3.md
- src/data/roadmaps/git-github/content/pr-from-a-fork@8lXXVFkgK6n5IHaYkYe3l.md
- src/data/roadmaps/git-github/content/pr-guidelines@GwDNk2HBjASr_NWIL4G3-.md
- src/data/roadmaps/git-github/content/pre-commit@HhpAIzYMlMiQ9msrYZyDB.md
- src/data/roadmaps/git-github/content/pre-push@j5kWEUKwBFg5EMm8-61K9.md
- src/data/roadmaps/git-github/content/private-vs-public@HEqBbw_A4ZbJI5zEy8ViN.md
- src/data/roadmaps/git-github/content/profile-readme@KbVvFVQ4k77R2_ddsc7WT.md
- src/data/roadmaps/git-github/content/project-planning@q0zy_hXav5iXw8LpGVJVd.md
- src/data/roadmaps/git-github/content/project-readme@WIVr7JxO1AJTNObW8mtY3.md
added copy and links to 10 topics around the git hook and readme sections.
> add content to git hook and readme sections

- src/data/roadmaps/git-github/content/git-log-options@qFEonbCMLri8iA0yONwuf.md
Improved git log flags.
No deletions.
> Improve `git-log-options`

- src/data/roadmaps/game-developer/content/frustum@UcLGWYu41Ok2NYdLNIY5C.md
This PR adds a writeup about frustum culling.
> Updated frustum@UcLGWYu41Ok2NYdLNIY5C.md

- src/data/roadmaps/game-developer/content/point@aNhyXWW2b7yKTv8y14zk9.md
Adds an explanation about point lights.
> Updated point@aNhyXWW2b7yKTv8y14zk9.md

- src/data/roadmaps/game-developer/content/spot@FetbhcK1RDt4izZ6NEUEP.md
Adds a basic writeup about spotlights.
> Updated spot@FetbhcK1RDt4izZ6NEUEP.md

- src/data/roadmaps/game-developer/content/metal@oEznLciLxZJaulMlBGgg4.md
> Updated metal@oEznLciLxZJaulMlBGgg4.md

- src/data/roadmaps/game-developer/content/opengl@ffa5-YxRhE3zhWg7KXQ4r.md
Adds an excellent playlist for learning OpenGL.
> Updated opengl@ffa5-YxRhE3zhWg7KXQ4r.md

- src/data/roadmaps/game-developer/content/reinforcements-learning@rGEHTfdNeBAX3_XqC-vvI.md
Adds video to visualize reinforcement learning in action.
> Updated reinforcements-learning@rGEHTfdNeBAX3_XqC-vvI.md

- src/data/roadmaps/game-developer/content/assembly@AaRZiItRcn8fYb5R62vfT.md
Adds video about game development on assembly.
> Updated assembly@AaRZiItRcn8fYb5R62vfT.md

- src/data/roadmaps/game-developer/content/unity-3d@rNeOti8DDyWTMP9FB9kJ_.md
This PR adds [Unity in 100 Seconds](https://www.youtube.com/watch?v=iqlH4okiQqg)
> Updated unity-3d@rNeOti8DDyWTMP9FB9kJ_.md

- src/data/roadmaps/game-developer/content/unreal-engine@a6H-cZtp3A_fB8jnfMxBR.md
Adds useful links to the popup.
> Updated unreal-engine@a6H-cZtp3A_fB8jnfMxBR.md

- src/data/roadmaps/backend/content/rabbitmq@GPFRMcY1DEtRgnaZwJ3vW.md
This PR adds [RabbitMQ in 100 Seconds](https://m.youtube.com/watch?v=NQ3fZtyXji0). A nice introduction to the topic.
> Updated rabbitmq@GPFRMcY1DEtRgnaZwJ3vW.md

- src/data/roadmaps/backend/content/aws-neptune@5xy66yQrz1P1w7n6PcAFq.md
This PR adds a brief introduction to AWS Neptune.
> Updated aws-neptune@5xy66yQrz1P1w7n6PcAFq.md

- src/data/roadmaps/backend/content/dynamodb@dwfEHInbX2eFiafM-nRMX.md
This PR adds a nice explanation of dynamoDB.
> Updated dynamodb@dwfEHInbX2eFiafM-nRMX.md

- src/data/best-practices/backend-performance/content/prometheus-graphana.md
This PR adds [Grafana Explained in 3 minutes](https://www.youtube.com/watch?v=X-GLqyMZaJk). It does a good introduction to the topic and explains use cases.
> Updated prometheus-graphana.md

- src/data/best-practices/backend-performance/content/up-to-date.md
This PR adds the video [dependabot on GitHub](https://www.youtube.com/watch?v=TnBEVPUsuAw). 
It adds a practical explanation to the topic to encourage people to implement it right away.
> Updated up-to-date.md

- src/data/roadmaps/postgresql-dba/content/awk@HJCRntic0aGVvdmCN45aP.md
This PR adds  [AWK in 300 Seconds](https://www.youtube.com/watch?v=15DvGiWVNj0).
> Updated awk@HJCRntic0aGVvdmCN45aP.md

- src/data/roadmaps/backend/content/timescale@WiAK70I0z-_bzbWNwiHUd.md
This PR adds the [TimeScaleDB Explained in 100 Seconds](https://www.youtube.com/watch?v=69Tzh_0lHJ8).
> Updated timescale@WiAK70I0z-_bzbWNwiHUd.md

- src/data/roadmaps/postgresql-dba/content/grep@cFtrSgboZRJ3Q63eaqEBf.md
This PR adds [grep: A Practical Guide](https://www.youtube.com/watch?v=crFZOrqlqao). It's a nice resource to understand how grep works.
> Updated grep@cFtrSgboZRJ3Q63eaqEBf.md

- src/data/roadmaps/game-developer/content/godot@7OffO2mBmfBKqPBTZ9ngI.md
> Updated godot@7OffO2mBmfBKqPBTZ9ngI.md

- src/data/roadmaps/angular/content/cross-site-scripting@umUX4Hxk7srHlFR_Un-u7.md
- src/data/roadmaps/angular/content/sanitization@cgI9oeUHufA-ky_W1zENe.md
- src/data/roadmaps/angular/content/security@mm6c7GLQEwoQdAHdAYzGh.md
- src/data/roadmaps/angular/content/trusting-safe-values@XoYSuv1salCCHoI1cJkxv.md
Added content to the security part of the angular roadmap https://roadmap.sh/angular
> add Angular security content

- src/data/roadmaps/java/content/101-java-advanced-topics/108-basics-of-threads.md
I don't know what this `NB!` was supposed to be for. If it is supposed to alter the markdown, it isn't working.
> docs(java): remove nb! in threads

- src/data/roadmaps/aws/content/100-introduction/102-public-private-hybrid.md
Adding a direct aws doc and red hat link
> Update 102-public-private-hybrid.md adding useful links

- src/data/roadmaps/aws/content/100-introduction/101-iaas-paas-saas.md
To speed up the learning, adding direct links to aws docu.
> Update 101-iaas-paas-saas.md adding aws docu link

- src/data/projects/basic-dockerfile.md
- src/data/projects/log-archive-tool.md
Added two projects:
Log Archiving tool for DevOps & Linux Roadmaps.
Basic Dockerfile for DevOps & Docker Roadmaps.
> add two beginner projects

- scripts/generate-og-images.mjs
- src/components/OpenSourceBanner.astro
- src/components/OpenSourceStat.astro
- src/lib/github.ts
- src/pages/about.astro
Based on discussion under #6674 
All other files, except one, seem to produce the expected result! I am not able to test the `generate-og-images.mjs`.
Feedback is always appriciated!
> Update GitHub repository rank display automatically

- src/data/roadmaps/nodejs/content/--watch@812bVEzxwTsYzLG_PmLqN.md
- src/data/roadmaps/nodejs/content/axios@BOLiZg8YDKADMwP01U5ph.md
- src/data/roadmaps/nodejs/content/debugging@ZLNUuDKhJ03Kw7xMVc7IR.md
- src/data/roadmaps/nodejs/content/ejs@L-_N7OxxuHCXsdWYBgZGu.md
- src/data/roadmaps/nodejs/content/semantic-versioning@dOlzIXBfAPmbY542lNOe6.md
- src/data/roadmaps/nodejs/content/testing@90NIFfbWjTbyKZKwyJlfI.md
- src/data/roadmaps/nodejs/content/using-apm@CvkjlOpT34lOHgzQHL40s.md
- src/data/roadmaps/nodejs/content/using-debugger@XEGTeGWw05xWYOfUo3POE.md
- src/data/roadmaps/nodejs/content/what-is-nodejs@Mp056kNnwsRWeEXuhGPy-.md
- src/data/roadmaps/nodejs/content/working-with-databases@5l-lZ8gwVLqqAF_n99vIO.md
*This PR was a part of merged pr (#6664).*
- Fix Spelling and Grammar Mistakes.
- Fix Wrong URLs.
- Few Deletions.
*A Rare PR Count ⚡ - #6666.*
> Further Improvements in Node.js Roadmap.

- src/data/guides/devops-career-path.md
- src/data/roadmaps/devops/faqs.astro
- src/pages/devops/career-path.astro
Added the DevOps Career Parth article & added a link to it and projects in the DevOps roadmap FAQ (as per Eds request)
> Add devops career path article

- src/data/question-groups/frontend/frontend.md
> Add featured image to the frontend questions

- src/data/roadmaps/blockchain/blockchain.json
It's just a typo, nothing serious
> Corrected 'Eherum' with 'Etherum' in blockchain.json

- src/data/roadmaps/game-developer/content/rendering-equation@WVgozaQPFbYthZLWMbNUg.md
This video explains from top to bottom the rendering equation, saw it some months ago, it's too good to miss.
> Updated rendering-equation@WVgozaQPFbYthZLWMbNUg.md

- src/data/roadmaps/git-github/content/git-filter-branch@BKVA6Q7DXemAYjyQOA0nh.md
> docs(Git & GitHub): added resource pre-text to git-filter branch

- src/components/Navigation/Navigation.astro
- src/components/NavigationDropdown.tsx
- src/components/RoadmapDropdownMenu/RoadmapDropdownMenu.tsx
- src/stores/page.ts
> feat: add roadmap dropdown menu

- src/data/roadmaps/game-developer/content/behavior-tree@ztoW8fBY73Es624A_tjd7.md
Adds a practical example on behavior trees.
> Updated behavior-tree@ztoW8fBY73Es624A_tjd7.md

- src/data/roadmaps/git-github/content/--mixed@qis7Z5VRxMcOmbesQlegZ.md
- src/data/roadmaps/git-github/content/--soft@Uc7FyfAKpDFRGRNHwztFo.md
Just a fix for two resource links in the git-github roadmap.
> Fix section in res links

- src/data/roadmaps/game-developer/content/color@WK6fLWJq9Vh2ySVrSqd-U.md
This PR adds a practical resource for learning color theory, made by Pixar.
> Updated color@WK6fLWJq9Vh2ySVrSqd-U.md

- src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
I'd like to suggest adding this video resource to the Java roadmap on the step "How jvm works".
This 8 minutes video by BigDataELearning covers the following topics in depth: class Loader, runtime data area, and execution engine system and process .
It was particularly useful and detailed for beginners developers like me.
> feat: Add new video resource on jvm architecture

- src/data/roadmaps/game-developer/content/translucency--transparency@PuhXaRZ-Ql5PCqzMyz3en.md
Adds a good article on blending (transparency).
> Updated translucency--transparency@PuhXaRZ-Ql5PCqzMyz3en.md

- src/data/roadmaps/game-developer/content/computer-graphics@lIb5MeDoqVj6HycveOgTS.md
Beyond good intro to computer graphics.
> Updated computer-graphics@lIb5MeDoqVj6HycveOgTS.md

- src/data/roadmaps/javascript/content/string@1RcwBHU3jzx0YxxUGZic4.md
> Update JS string content - added backticks ( `` )

- src/data/roadmaps/sql/content/data-manipulation-language-dml@WMSXi-eez_hHGDM8kUdWz.md
> Update data-manipulation-language by adding articles

- src/data/roadmaps/sql/content/drop-table@YzJ6QmY2arMfRzMAPaI0T.md
minor bump: highlight - by transforming to bold - words that are crucial to be stressed on.
> SQL roadmap drop table keyword highlight

- src/data/roadmaps/data-analyst/content/analaysis--reporting-with-excel@sgXIjVTbwdwdYoaxN3XBM.md
- src/data/roadmaps/data-analyst/content/average@yn1sstYMO9du3rpfQqNs9.md
- src/data/roadmaps/data-analyst/content/correlation-analysis@murioZ0NdrTix_lqSGz-8.md
- src/data/roadmaps/data-analyst/content/data-storage-solutions@iTmtpXe7dR4XKslgpsk2q.md
- src/data/roadmaps/data-analyst/content/data-transformation@t_BRtEharsrOZxoyX0OzV.md
- src/data/roadmaps/data-analyst/content/datedif@yBlJrNo9eO470dLp6OaQZ.md
- src/data/roadmaps/data-analyst/content/dispersion@2ldO-_ZnIg364Eo8Jyfgr.md
- src/data/roadmaps/data-analyst/content/ggplot2@E0hIgQEeZlEidr4HtUFrL.md
- src/data/roadmaps/data-analyst/content/ggplot2@n3M49lgNPn28hm7kzki-a.md
- src/data/roadmaps/data-analyst/content/introduction@3xp2fogAVmwXQhdzhZDWR.md
- src/data/roadmaps/data-analyst/content/key-concepts-of-data@R12sArWVpbIs_PHxBqVaR.md
- src/data/roadmaps/data-analyst/content/knn@SStzU_iXSvI_9QWbvGNou.md
- src/data/roadmaps/data-analyst/content/kurtosis@PqGO8AU1zE2ZdtqrIrOkZ.md
- src/data/roadmaps/data-analyst/content/learn-sql@i4VCwFm-wc9cqE73i-BIb.md
- src/data/roadmaps/data-analyst/content/matplotlib@tvDdXwaRPsUSTqJGaLS3P.md
- src/data/roadmaps/data-analyst/content/variance@ict4JkoVM-AzPbp9bDztg.md
- src/data/roadmaps/data-analyst/content/what-is-data-analytics@yCnn-NfSxIybUQ2iTuUGq.md
- src/data/roadmaps/data-analyst/data-analyst.json
Completed data-analyst roadmap content and updated the "Learn SQL" topic button to a blue button that links to the SQL roadmap.
> complete content on data analyst roadmap

- src/data/roadmaps/cyber-security/content/stakeholders@lv6fI3WeJawuCbwKtMRIh.md
Added content to stakeholder section in the cybersecurity roadmap with sources.
> Add content to stakeholder

- src/data/roadmaps/game-developer/content/deep-learning@ltkEyfuDxExs7knqs79ya.md
Excellent resource on neural networks.
> Updated Deep Learning

- src/data/roadmaps/javascript/content/apply@-BtF34cEzI6J8sZCDRlRE.md
updated "apply" description before without content.
> Update apply method of function in Javascript

- src/data/roadmaps/cyber-security/content/directory-traversal@L0ROYh2DNlkybNDO2ezJY.md
Added content to Directory traversal.
> Add content to directory-traversal@L0ROYh2DNlkybNDO2ezJY.md

- src/data/roadmaps/game-developer/content/microsurface-scattering@YrQgfjsdLCIUxrwflpEHO.md
Adds a nice video explaining subsurface scattering
> The 4 main types of subsurface scattering

- src/data/guides/backend-technologies.md
- src/data/roadmaps/backend/faqs.astro
- src/pages/backend/technologies.astro
Added the article and linked it via an FAQ on the BE roadmap.
> Add Backend Technologies Guide

- src/data/roadmaps/game-developer/content/decision-tree-learning@sz1047M8_kScjth84yPwU.md
A good decision learning tree resource.
> Updated decision-tree-learning@sz1047M8_kScjth84yPwU.md

- src/data/roadmaps/datastructures-and-algorithms/content/100-language/104-cpp.md
> Add Dedicated C++ Roadmap Link to Data Structures & Algorithms Roadmap

- src/data/roadmaps/devops/content/docker@P0acFNZ413MSKElHqCxr3.md
Added Docker Roadmap link to DevOps page - Docker resources
> Link Docker Roadmap inside suggested resources #6875

- src/data/roadmaps/angular/content/zones@m4WBnx_9h01Jl6Q1sxi4Y.md
Adding missing `Visit the following...` and added a video.
> docs(angular): update zones content

- src/data/roadmaps/angular/content/router-events@YF_sG292HqawIX0siWhrv.md
Added the missing `Visit` tag and added extra article.
> docs(angular): update router events content

- src/data/roadmaps/angular/content/services-with-dependencies@TGRZBizDy83JKg_MhnRdX.md
The previous content for this was more suited to the `testing-services` file.
> docs(angular): update services with dependencies content

- src/components/TeamMarketing/TeamPricing.tsx
> Add "Copied Text" Prompt Opacity

- src/data/roadmaps/data-analyst/content/visualisation@jowh4CFLQiFzKaaElyCuQ.md
notice that file name is also written wrong and affect the way it's displayed on the screen.
> Fixed a typo on the word "visualisation" - (visualization).

- src/data/roadmaps/sql/content/group-by@Zw8IHfCCMSxmVjx5Ho5ff.md
- src/data/roadmaps/sql/content/max@YqDJq3fPxUZlwsdq0kJg7.md
This PR is just meant to fix/add markdown formatting on SQL pages MAX and GROUP BY.
> SQL: format MAX and GROUP BY markdown

- src/data/roadmaps/cyber-security/content/urlscan@lMiW2q-b72KUl-2S7M6Vb.md
Information is sourced from urlscan.io's about page.
> Add content to urlscan

- src/data/roadmaps/data-analyst/content/types-of-data-analytics@Lsapbmg-eMIYJAHpV97nO.md
It was modified the way the types of data analytics are shown, now is easier to understand the concepts. Also, I've added free resources for a deeper read on the subject (2 links and 2 youtube videos)
> Updated and added free resources to types-of-data-analytics@Lsapbmg-eMIYJAHpV97nO.md

- src/components/AuthenticationFlow/EmailLoginForm.tsx
> Assign `id` Property For Form Label Input Elements

- src/data/projects/basic-github-actions.md
- src/data/projects/basic-iac-with-terraform.md
- src/data/projects/docker-webserver.md
- src/data/projects/local-monitoring-stack.md
Beginner DevOps project to setup a GitHub Actions workflow that tests, builds and deploys an Astro powered GitHub Page.
> Add DevOps Projects

- src/data/roadmaps/frontend/content/pwas@PoM77O2OtxPELxfrW1wtl.md
I linked the frontend roadmap in the same article back.
> Add an article on how to build an offline-capable Notepad app using PWA principles

- src/data/roadmaps/devrel/content/ides@KdFYmj36M2jrGfsYkukpo.md
- src/data/roadmaps/devrel/content/vs-code@j5nNSYI8s-cH8EA6G1EWY.md
- Added history and basics of IDEs
- Added VSCode guide and official links
> Added content inside IDEs and VS Code sections, present inside DevRel Roadmap

- src/data/roadmaps/rust/content/116-gui-dev/100-druid.md
- src/data/roadmaps/rust/content/116-gui-dev/100-tauri.md
- src/data/roadmaps/rust/rust.json
Druid is no longer maintained so I have replaced it with Tauri.
> remove druid add tauri

- src/data/roadmaps/terraform/content/local-values@1mFih8uFs3Lc-1PLgwiAU.md
I have added the content for the Locals Value topic in the Terraform Roadmap.
> Added content for terraform local values page in terraform roadmap.

- src/data/roadmaps/linux/content/101-editing-files/100-vim.md
- src/data/roadmaps/linux/content/104-text-processing/109-pipe.md
- src/data/roadmaps/linux/content/104-text-processing/116-grep.md
- src/data/roadmaps/linux/content/104-text-processing/index.md
- src/data/roadmaps/linux/content/114-shell-programming/index.md
- add a detaild link about piping.
- add a detailed link about text filters in general.
- add a basic link for grep beginners.
- add a detailed link about bash scripting.
- add link to vi cheat sheet
> Add some linux resources

- src/data/roadmaps/cyber-security/content/perimiter-vs-dmz-vs-segmentation@PUgPgpKio4Npzs86qEXa7.md
Hi, want to add some real examples of network segmentations.
> add real examples about segmentations

- src/data/roadmaps/python/content/data-structures--algorithms@VJSIbYJcy2MC6MOFBrqXi.md
A link in the Python roadmap linked to a paywalled resource.
> Removed paid resource

- src/data/roadmaps/ux-design/content/bj-foggs-behavior-model@2NlgbLeLBYwZX2u2rKkIO.md
BJ Fogg has renamed "Triggers" to "Prompts" in late 2017. See: https://behaviormodel.org/prompts/
> Renaming "Triggers" to "Prompts"

- src/data/roadmaps/terraform/content/environment-variables@fm8oUyNvfdGWTgLsYANUr.md
- src/data/roadmaps/terraform/content/validation-rules@U2n2BtyUrOFLnw9SZYV_w.md
I have added the relevant content in the following two sections of the Terraform roadmap -
1. Environment Variables
2. Validation Rules
> Added content for Environment Variable and Validation Rules in Terraform Roadmap

- src/data/guides/devops-skills.md
- src/data/roadmaps/devops/faqs.astro
- src/pages/devops/skills.astro
Guide formatted and new FAQ added that links to the guide.
> Add 10 devops skills guide

- src/data/roadmaps/postgresql-dba/postgresql-dba.json
In the "Learn to Automate" section, we had a blank blue button just called "button", the assumption is that it was going to link to the DevOps roadmap.
> turned blank button into DevOps Roadmap button

- src/data/roadmaps/linux/content/103-working-with-files/103-soft-hard-links.md
- fixed: hard links share the same inode number.
> Fix wrong info in Linux roadmap

- src/components/AuthenticationFlow/EmailLoginForm.tsx
- src/components/FrameRenderer/ProgressNudge.tsx
> fix: progress nudge count

- src/data/roadmaps/git-github/content/git-filter-branch@BKVA6Q7DXemAYjyQOA0nh.md
> add git filter-repo as an alternative to git filter-branch

- src/data/roadmaps/vue/content/v-bind@cuM9q9vYy8JpZPGeBffd1.md
- src/data/roadmaps/vue/content/v-else-if@a9caVhderJaVo0v14w8WB.md
- src/data/roadmaps/vue/content/v-for@3ftwRjQ9e1-qDT9BV53zr.md
- src/data/roadmaps/vue/content/v-html@bZxtIBeIfeUcR32LZWrPW.md
- src/data/roadmaps/vue/content/v-once@5k9CrbzhNy9iiS6ez2UE6.md
- src/data/roadmaps/vue/content/v-pre@mlsrhioiEkqnRIL6O3hNa.md
- src/data/roadmaps/vue/content/v-text@NCIzs3jbQTv1xXhAaGfZN.md
Added content to this Vue topics:
- v-text
- v-html
- v-bind
- v-once
- v-pre
- v-else-if
- v-for
The content follows the structure suggested in the contributing guidelines.
> Added content to some Vue topics.

- public/roadmap-content/devops.json
- src/data/roadmaps/devops/content/ubuntu--debian@cTqVab0VbVcn3W7i0wBrX.md
add "Practice Linux Commands with Hands-on Labs" to "Ubuntu / Debian" node: https://labex.io/courses/linux-basic-commands-practice-online
Practice is the most effective way to learn Linux. This course focuses on Ubuntu/Debian and offers a free online Ubuntu virtual machine (VM) for users to practice and master Linux commands.
> add "Practice Linux Commands with Hands-on Labs" to "Ubuntu / Debian" node

- src/data/roadmaps/ios/content/swiftui@kAIKsDcDzwI1E0wSnC_uo.md
Added new course link of 100 days of SwiftUI | Hacking with SwiftUI
> Added new course link of 100 days of SwiftUI | Hacking with SwiftUI

- src/data/roadmaps/ux-design/content/create-action-funnel@kcG4IpneJzA6di0uqTiwb.md
Updated the explanation to include the key thesis of the framework and the components of the CREATE acronym.
> Update content relevance

- src/data/roadmaps/prompt-engineering/content/103-real-world/100-structured-data.md
Improve the content in `src/data/roadmaps/prompt-engineering/content/103-real-world/100-structured-data.md` to be more concise and understandable for rookies.
> Improve structured data content for rookies

- src/data/roadmaps/frontend/faqs.astro
- src/data/roadmaps/frontend/frontend.md
Updated the FAQs in line with Eds ticket
> Updated FE FAQs

- src/components/Roadmaps/RoadmapCard.tsx
- src/components/Roadmaps/RoadmapsPage.tsx
- src/hooks/use-is-mounted.ts
> feat: add mark favourite button

- src/data/roadmaps/flutter/content/117-ci-cd/102-bitrise.md
- 404 link https://devcenter.bitrise.io/en/getting-started/getting-started-with-flutter-apps
- valid link https://devcenter.bitrise.io/en/getting-started/quick-start-guides/getting-started-with-flutter-apps.html
> Update 102-bitrise.md 404 link

- src/data/roadmaps/javascript/content/symbol@R6ICrk6vjoBxx5nRGo4Jg.md
- Improved sentence flow and readability in the description of Symbols.
- Adjusted resource links formatting for consistency.
- Added link to MDN documentation
- Added link to video on Javascript Symbols
> Add new resource to symbol, refine documentation for clarity and flow.

- src/data/roadmaps/vue/content/v-cloak@RrSekP8Ub01coegMwLP6a.md
- src/data/roadmaps/vue/content/v-slot@m9pQ3daR3KiwRATcQysHA.md
The content follows the structure of the contributing guidelines.
> Added v-cloak and v-slot content on Vue roadmap

- public/roadmap-content/data-analyst.json
Corrected "Prespective Analytics" into _Prescriptive Analytics_ 
References:
Issue #7165 
PR #7177
> Complete spell-check for "Prespective Analytics"

- src/data/guides/frontend-frameworks.md
- src/data/roadmaps/frontend/faqs.astro
- src/pages/frontend/frameworks.astro
As per the outline etc but with one large change.
The markdown table did not fit on the page, so instead I made it into an image.
@Edlan01 please let me know if that's ok.
> add frontend framework guide

- src/data/roadmaps/software-architect/content/what-is-software-architecture@EGG99VA-PEdWdVxNDLtG_.md
Hi everyone!
It's my first time here; I hope I'm doing things right for this contribution.
It's a quick fix for a broken link in the [Software Architect](https://roadmap.sh/software-architect) roadmap. I hope it helps.
> Update broken link in Software Architect roadmap

- src/components/Projects/ProjectCard.tsx
- src/components/Projects/ProjectsList.tsx
> feat: add project status

- src/data/roadmaps/rust/content/108-web-development/104-axum.md
- Add content for 104-axum.md.
> Add content for axum

- src/data/roadmaps/prompt-engineering/content/107-prompt-hacking/index.md
Added an additional detailed summary for the prompt hacking section, which was not present, refining the content.
> Fix: Improved Content in Prompt Hacking

- src/data/roadmaps/redis/content/key-value-database@l2aXyO3STnhbFjvUXPpm2.md
> Added content for KV database

- src/data/roadmaps/devops/content/git@uyDm1SpOQdpHjq9zBAdck.md
- src/data/roadmaps/devops/content/rust@eL62bKAoJCMsu7zPlgyhy.md
This pull request adds new learning resources to the DevOps roadmap for Rust and Git.
Resources added:
A course link for Rust that follows the Rust by Practice book
An interactive Git course link
> Devops Roadmap: Adding Resources Link

- src/data/roadmaps/devops/content/firewall@f3tM2uo6LLSOmyeFfLc7h.md
- src/data/roadmaps/devops/content/load-balancer@i8Sd9maB_BeFurULrHXNq.md
- src/data/roadmaps/devops/content/reverse-proxy@eGF7iyigl57myx2ejpmNC.md
This pull request add resources for devops map reverse proxy, load balancer and firewall.
Resources added:
- One article for reverse proxy - `Understanding Nginx As A Reverse Proxy`
- One article for load balancer - `Nginx: Reverse Proxy and Load Balancing`
- One article for firewall - `Uncomplicated Firewall (ufw)`
> Devops roadmap: add resources links

- src/data/roadmaps/aws/content/101-ec2/index.md
Update index.md of 101-ec2 directory
Added EC2 official website link
> Update index.md of 101-ec2 directory

- .astro/settings.json
- src/components/TopicDetail/TopicDetailLink.tsx
> feat: add open source link type

- src/data/guides/devops-principles.md
Fixed typo and incomplete link in the 9th section for cncf.io
> Fixed typo and incomplete link in devops-principles.md

- src/data/roadmaps/full-stack/content/git@We2APJpOPTr-VNfowG0kI.md
- src/data/roadmaps/full-stack/content/github-actions@863KMXcFJzInvTp_-Ldmz.md
- src/data/roadmaps/full-stack/content/monit@y1SFX7uvWaCy4OYBnECLu.md
- src/data/roadmaps/full-stack/content/nodejs@_aA6Hp4KkgJeptqo8oKTg.md
- src/data/roadmaps/full-stack/content/postgresql@HGhnbMg6jh6cAmUH4DtOx.md
- src/data/roadmaps/full-stack/content/redis@Onfd7Sl8LG2sjh2aQY7gb.md
- src/data/roadmaps/full-stack/content/restful-apis@vmHbWdmMHF53otXIrqzRV.md
- src/data/roadmaps/full-stack/content/tailwind-css@CVCqdPkq_hGQfI8EEi5RC.md
- src/data/roadmaps/full-stack/content/terraform@2kKHuQZScu7hCDgQWxl5u.md
- Added video for REST API
- Added documentation link for Redis
- Added official website for Monit
- Added dedicated roadmaps
- Updated website name for clarity
- Changed type from `article` to `official`
- Updated feed link from `GitHub` to `GitHub Actions`
> Feat: Added Resources, Improvements, and Typo Fixes for Full Stack Roadmap

- src/data/roadmaps/java/content/101-java-advanced-topics/index.md
This PR adds an initial description to the **previously blank** index.md file under the Java Advanced Topics section. The content introduces key topics such as memory management, collection framework, serialization, networking and sockets, how the JVM works, garbage collection, and the basics of threading. Each of these concepts is briefly explained, and I have included relevant links to further resources for in-depth learning.
> Adds initial content to Java Advanced Topics index.md with relevant links

- src/data/roadmaps/software-architect/content/less@qwpsGRFgzAYstM7bJA2ZJ.md
- src/data/roadmaps/software-architect/content/safe@Bg7ru1q1j6pNB43HGxnHT.md
> [Update] software architect: Agile model

- src/data/roadmaps/vue/content/v-html@bZxtIBeIfeUcR32LZWrPW.md
Fixed typos "v-thml" and "HTMI" to  "v-html" and "HTML" respectively.
> Update v-html@bZxtIBeIfeUcR32LZWrPW.md - v-html,HTML typo fix

- src/data/roadmaps/devops/content/github-actions@JnWVCS1HbAyfCJzGt-WOH.md
- src/data/roadmaps/devops/content/nginx@ukOrSeyK1ElOt9tTjCkfO.md
This pull request add resource links to devops roadmap. They are follows:
- On github actions, course video: `GitHub Actions Certification – Full Course to PASS the Exam`
- On nginx, article: `Basic NGINX Setup: Ubuntu Guide to a Functional and Secure Website Serving`
> Devops Roadmap: GitHub action & nginx resource added

- src/data/roadmaps/software-architect/content/what-is-software-architecture@EGG99VA-PEdWdVxNDLtG_.md
replace broken link with new one from other blog which was for me informative.
> replace broken link

- src/data/roadmaps/ios/content/swift-recommended@KJ7fM-V0_azY_lzmhjJAN.md
* Added new course link of 100 days of Swift | Hacking with Swift
* Added new course link of Swift Programming | Programiz
> Added 2 new course links of Swift programming

- src/data/roadmaps/react/content/usecallback@2zrN65JZhCyNimi33g78f.md
- src/data/roadmaps/react/content/usecallback@dgoDNDtW2_q9R9yhkXrcz.md
- src/data/roadmaps/react/react.json
I've removed the duped node and shifted the surround nodes up a little to fill the space.
> removed duplicate subtopic, replaced content, shifted nodes up

- src/data/roadmaps/aws/content/100-introduction/100-cloud-computing.md
- src/data/roadmaps/aws/content/100-introduction/103-aws/101-shared-respons.md
- src/data/roadmaps/aws/content/100-introduction/103-aws/102-well-architected.md
- src/data/roadmaps/aws/content/100-introduction/103-aws/index.md
- src/data/roadmaps/aws/content/100-introduction/index.md
- src/data/roadmaps/aws/content/101-ec2/100-instance-types.md
- src/data/roadmaps/aws/content/101-ec2/101-cpu-credits.md
- src/data/roadmaps/aws/content/101-ec2/106-purchasing-options.md
- src/data/roadmaps/aws/content/101-ec2/index.md
- src/data/roadmaps/aws/content/102-vpc/100-cidr-blocks.md
- src/data/roadmaps/aws/content/102-vpc/101-subnets/100-private.md
- src/data/roadmaps/aws/content/102-vpc/101-subnets/101-public.md
- src/data/roadmaps/aws/content/102-vpc/101-subnets/index.md
- src/data/roadmaps/aws/content/102-vpc/103-security-groups.md
- src/data/roadmaps/aws/content/102-vpc/104-internet-gateway.md
- src/data/roadmaps/aws/content/102-vpc/105-nat-gateway.md
- src/data/roadmaps/aws/content/102-vpc/index.md
- src/data/roadmaps/aws/content/103-iam/100-policies/100-identity-based.md
- src/data/roadmaps/aws/content/103-iam/100-policies/101-resource-based.md
- src/data/roadmaps/aws/content/103-iam/101-users-groups.md
- src/data/roadmaps/aws/content/103-iam/102-roles/100-instance-profiles.md
- src/data/roadmaps/aws/content/103-iam/102-roles/101-assuming-roles.md
- src/data/roadmaps/aws/content/104-autoscaling/100-amis.md
- src/data/roadmaps/aws/content/104-autoscaling/101-launch-templates.md
- src/data/roadmaps/aws/content/104-autoscaling/102-autoscaling-groups.md
- src/data/roadmaps/aws/content/104-autoscaling/103-scaling-policies.md
- src/data/roadmaps/aws/content/104-autoscaling/104-elb.md
- src/data/roadmaps/aws/content/104-autoscaling/index.md
> [!NOTE]
> ## Description
This PR aims to improve the overall AWS Roadmap. (Part-1)
> Improve AWS Roadmap - Part 1

- src/data/roadmaps/aws/content/105-s3/100-buckets-objects.md
- src/data/roadmaps/aws/content/105-s3/101-lifecycle.md
- src/data/roadmaps/aws/content/105-s3/102-storage-types/100-standard.md
- src/data/roadmaps/aws/content/105-s3/102-storage-types/101-s3-ia.md
- src/data/roadmaps/aws/content/105-s3/102-storage-types/102-gladier.md
- src/data/roadmaps/aws/content/105-s3/102-storage-types/index.md
- src/data/roadmaps/aws/content/105-s3/index.md
- src/data/roadmaps/aws/content/106-ses/100-sandbox-limits.md
- src/data/roadmaps/aws/content/106-ses/101-identity-verification.md
- src/data/roadmaps/aws/content/106-ses/102-dkim-setup.md
- src/data/roadmaps/aws/content/106-ses/103-feedback-handling.md
- src/data/roadmaps/aws/content/106-ses/104-configuration-sets.md
- src/data/roadmaps/aws/content/106-ses/105-sender-reputation.md
- src/data/roadmaps/aws/content/106-ses/106-dedicated-ip.md
- src/data/roadmaps/aws/content/106-ses/index.md
- src/data/roadmaps/aws/content/107-route53/100-hosted-zones/100-private.md
- src/data/roadmaps/aws/content/107-route53/100-hosted-zones/101-public.md
- src/data/roadmaps/aws/content/107-route53/100-hosted-zones/index.md
- src/data/roadmaps/aws/content/107-route53/101-routing-policies.md
- src/data/roadmaps/aws/content/107-route53/102-health-checks.md
- src/data/roadmaps/aws/content/107-route53/index.md
- src/data/roadmaps/aws/content/108-cloudwatch/101-events.md
- src/data/roadmaps/aws/content/108-cloudwatch/102-logs.md
- src/data/roadmaps/aws/content/108-cloudwatch/index.md
- src/data/roadmaps/aws/content/109-cloudfront/100-distributions.md
- src/data/roadmaps/aws/content/109-cloudfront/101-policies.md
- src/data/roadmaps/aws/content/109-cloudfront/102-invalidations.md
- src/data/roadmaps/aws/content/109-cloudfront/index.md
> [!NOTE]
> ## Description
This PR aims to improve the overall AWS Roadmap. (Part-2)
> Improve AWS Roadmap - Part 2

- src/data/roadmaps/rust/content/100-introduction/102-memory-safety.md
In this video, he provides a clear explanation of Rust's ownership system, including example code. It could be helpful for understanding ownership concepts.
> feat: add a YouTube video link to Rust memory management

- src/data/roadmaps/react/content/component-lifecycle@8OBlgDRUg-CTgDXY-QHyO.md
> Fix Broken Link in React Roadmap -> Component Life Cycle

- src/data/roadmaps/react/content/jest@opa61u9gYgSpoPtxp58wu.md
Added a section on 'Testing JavaScript with Vultr' to the documentation. The article explains how to deploy and test JavaScript applications on the Vultr cloud platform, covering setup, environment configuration, and basic test scripts for ensuring performance and reliability.
> Add a free article to the  React Roadmap

- src/data/roadmaps/cyber-security/content/router@lwSFIbIX-xOZ0QK2sGFb1.md
Updated content to Cyber-Security Roadmap:
Fix #7460
- Router
(PR for Hacktoberfest)
> fix: update router content in cybersecurity roadmap

- src/data/roadmaps/python/content/nose@SSnzpijHLO5_l7DNEoMfx.md
As nose is deprecated and not actively maintained the information is added to this page of nose tutorial.
> Updated nose -python description (nose is deprecated now)

- src/data/roadmaps/nodejs/content/system-errors@05YY-AhLKzn4Ypr4eow5E.md
Add an Article that explains system errors and fix them
> Add  system errors article to Nodejs Roadmap

- src/data/roadmaps/ai-engineer/content/open-vs-closed-source-models@RBwGsq9DngUsl8PrrCbqx.md
- src/data/roadmaps/ai-engineer/content/opensource-ai@a_3SabylVqzzOyw3tZN5f.md
- src/data/roadmaps/ai-engineer/content/popular-open-source-models@97eu-XxYUH9pYbD_KjAtA.md
This PR adds the content for the AI Engineer roadmap for the following topics:
- Popular Open Source Models
- Open vs Closed Source Models
- OpenSource AI
> Contribution to AI Engineer Roadmap

- src/data/roadmaps/nodejs/content/javascript-errors@Wg7KSpAPxjeFMxC6PBnHO.md
a Javascript error reference article from mdn web documents
> Add a Javascript error reference article to Nodejs roadmap

- src/data/best-practices/frontend-performance/content/compress-your-images.md
I just add another image compressor to the list in frontend performance roadmap
> Add minipic to image compressor list

- src/data/roadmaps/api-design/api-design.json
> fix: api design node id

- contributing.md
There is not a single PR which was helpful. Most if it is people spamming the issues
```
Can you please assign it to me?
``` 
I am going to remove it to avoid the spam.
> Remove from Hacktoberfest

- contributing.md
Reverts kamranahmedse/developer-roadmap#7494
> Revert "Remove from Hacktoberfest"

- src/data/roadmaps/ai-engineer/content/hugging-face-hub@YLOdOvLXa5Fa7_mmuvKEi.md
- src/data/roadmaps/ai-engineer/content/hugging-face-tasks@YKIPOiSj_FNtg0h8uaSMq.md
- src/data/roadmaps/ai-engineer/content/hugging-face@v99C5Bml2a6148LCJ9gy9.md
- src/data/roadmaps/ai-engineer/content/inference-sdk@3kRTzlLNBnXdTsAEXVu_M.md
- src/data/roadmaps/ai-engineer/content/ollama-models@ro3vY_sp6xMQ-hfzO-rc1.md
- src/data/roadmaps/ai-engineer/content/ollama-sdk@TsG_I7FL-cOCSw8gvZH3r.md
- src/data/roadmaps/ai-engineer/content/ollama@rTT2UnvqFO3GH6ThPLEjO.md
- src/data/roadmaps/ai-engineer/content/open-vs-closed-source-models@RBwGsq9DngUsl8PrrCbqx.md
- src/data/roadmaps/ai-engineer/content/opensource-ai@a_3SabylVqzzOyw3tZN5f.md
- src/data/roadmaps/ai-engineer/content/popular-open-source-models@97eu-XxYUH9pYbD_KjAtA.md
- src/data/roadmaps/ai-engineer/content/transformersjs@bGLrbpxKgENe2xS1eQtdh.md
This PR covers all the topics of Hugging face and Ollama thus OpenSource AI block is completely fulfilled on AI Engineer Roadmap
Updating on AI Engineer Roadmap
- Transformers.js
- Inference SDK
- Hugging Face Hub
- Hugging Face Tasks
- Hugging Face
- Ollama SDK
- Ollama Models
- Ollama
> All parts of OpenSource AI is Contributed (AI Engineer Roadmap)

- src/data/projects/caching-server.md
- src/data/projects/database-backup-utility.md
- src/data/projects/expense-tracker.md
- src/data/projects/github-user-activity.md
- src/data/projects/number-guessing-game.md
- src/data/projects/task-tracker.md
This PR will make some projects available at roadmap.sh/cpp
> Add C++ projects

- src/data/roadmaps/datastructures-and-algorithms/content/106-search-algorithms/100-linear-search.md
- src/data/roadmaps/datastructures-and-algorithms/content/106-search-algorithms/101-binary-search.md
Added missing resource links in DSA
> roadmap: added resource links in DSA for linear and binary search

- contributing.md
- license
**Updated the Current Contributing Guidelines and License Year.**
@kamranahmedse , Have a look.
Thanks.
> Improve Contributing Docs.

- src/data/roadmaps/frontend/frontend.md
Added multiple questions within the current one as per Eds instruction.
I had to add `<br>` in order to force gaps between questions as it was hard to control with this amount of text.
> updated frontend roadmap question

- src/data/roadmaps/python/content/learn-the-basics@JDDG4KfhtIlw1rkNCzUli.md
> Use your critical thinking to filter out non-essential stuff. Give honest arguments for why the resource should be included. Have you read this book? Can you give a short article?
I personally recommend this video course because it covers python's fundamentals and filled in a ton of knowledge gaps I didn't know I had.
> add video link of full python course to Python Roadmap

- src/data/roadmaps/datastructures-and-algorithms/content/102-data-structures/101-importance-of-datastructures.md
- src/data/roadmaps/datastructures-and-algorithms/content/104-algorithmic-complexity/103-asymptotic-notation/100-big-o.md
- src/data/roadmaps/datastructures-and-algorithms/content/107-tree-data-structure/102-avl-trees.md
- src/data/roadmaps/datastructures-and-algorithms/content/107-tree-data-structure/103-b-trees.md
- src/data/roadmaps/datastructures-and-algorithms/content/110-complex-data-structures/100-b-bplus-trees.md
- src/data/roadmaps/datastructures-and-algorithms/content/110-complex-data-structures/101-skip-list.md
- src/data/roadmaps/datastructures-and-algorithms/content/110-complex-data-structures/102-isam.md
Added some missing resource link for articles and videos in DSA
> roadmap: added missing resource links in DSA

- src/data/roadmaps/game-developer/content/bezier@DUEEm9sAaZqSI-W-PFZ8f.md
The attached video is one of the most simple to understand yet highly technical for bezier curves.
> Add a video learning resource for bezier curve

- src/data/roadmaps/technical-writer/content/what-is-technical-writing@jl1FsQ5-WGKeFyaILNt_p.md
I added two articles and two YouTube videos to explain more about the subject of technical writing.
> Add resources to Technical Writer Roadmap

- .astro/settings.json
- src/data/videos/frontend-explaination.md
IMG suggest we add the new campaign video to /video
> add new fe overview video to video page

- src/data/roadmaps/ai-engineer/content/adding-end-user-ids-in-prompts@4Q5x2VCXedAWISBXUIyin.md
- src/data/roadmaps/ai-engineer/content/agents-usecases@778HsQzTuJ_3c9OSn5DmH.md
- src/data/roadmaps/ai-engineer/content/ai-agents@9XCxilAQ7FRet7lHQr1gE.md
- src/data/roadmaps/ai-engineer/content/ai-agents@AeHkNU-uJ_gBdo5-xdpEu.md
- src/data/roadmaps/ai-engineer/content/chroma@dSd2C9lNl-ymmCRT9_ZC3.md
This Pull Request includes various updates to the AI Engineer roadmap documentation. The modifications enhance the readability and formatting of Markdown files, ensuring a consistent and professional presentation across the content.
Changes Made:
File: adding-end-user-ids-in-prompts.md
Improved link formatting for better readability.
Adjusted section headings for consistency.
File: agents-usecases.md
Fixed formatting issues in Markdown links by adding spaces.
Updated content for clarity and conciseness.
File: ai-agents.md
Enhanced link formatting and improved text alignment.
Added additional examples to illustrate use cases.
File: ai-agents@AeHkNU-uJ_gBdo5-xdpEu.md
Reformatted lists for better visual hierarchy.
Clarified descriptions to enhance understanding.
File: chroma.md
Corrected …
> fix: add space for Markdown links formatting

- src/data/roadmaps/prompt-engineering/content/108-image-prompting/100-style-modifiers.md
- src/data/roadmaps/prompt-engineering/content/108-image-prompting/101-quality-boosters.md
- src/data/roadmaps/prompt-engineering/content/108-image-prompting/102-weighted-terms.md
- src/data/roadmaps/prompt-engineering/content/108-image-prompting/103-deformed-generations.md
Update topic / sub topics from May 2023 to Oct 2024
- data: `src/data/roadmaps/prompt-engineering/content/108-image-prompting`
- why: Sub topics were empty of content, with only links.
- modify topics: 
- add content 
- 100-style-modifers.md
- 101-quality boosters.md
- 102-weighted-terms.md
- 103-deformed-generations.md
- add links
- 102-weighted-terms.md
> 📃 Prompt Eng Roadmap (Image Prompting) - Improve (2023, Q2 -> 2024, Q4)

- public/roadmap-content/backend.json
- src/data/roadmaps/backend/content/kafka@VoYSis1F1ZfTxMlQlXQKB.md
Adding Kafka Streams documentation
> Adding Kafka Streams documentation

- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/100-brute-force.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/101-backtracking.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/102-greedy-algorithms.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/103-randomised-algorithms.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/104-divide-and-conquer.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/105-recursion.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/106-dynamic-programming.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/107-two-pointer-techniques.md
- src/data/roadmaps/datastructures-and-algorithms/content/112-problem-solving-techniques/108-sliding-window-technique.md
Missing resource links added for all the techniques in "problem solving techniques"
> roadmap(DSA): added missing resouce links in problem solving techniques

- src/data/roadmaps/cyber-security/content/ssl--tls@LKK1A5-xawA7yCIAWHS8P.md
One of the SSL files incorrectly had the SSO copy within, this has been fixed.
> update SSL copy from the incorrect SSO one

- src/data/roadmaps/cyber-security/content/ldap@lV3swvD6QGLmD9iVfbKIF.md
Added missing video title in LDAP section:
> fix(r-cs-ldap): add missing video title

- src/data/roadmaps/cyber-security/content/basics-of-subnetting@E8Z7qFFW-I9ivr0HzoXCq.md
The video titled "Subnetting for hackers" is mostly about numbers conversion.
The video "Lets subnet your home network!" is part of the playlist I propose to change the link of the video resource to. It's much more comprehensive pack than two videos put here earlier.
Let me know what you think ✌
> chore(r-cs-subnetting): replace the video resource with better one

- src/data/roadmaps/api-design/content/cookies@UFuX8wcxZQ7dvaQF_2Yp8.md
> fix typo in cookies@UFuX8wcxZQ7dvaQF_2Yp8.md

- src/data/guides/devops-shift-left-testing.md
- src/data/roadmaps/devops/faqs.astro
- src/pages/devops/shift-left-testing.astro
added the guide as per Ed's instruction as well as linking it in the FAQs
> add shift left devops guide

- src/data/roadmaps/javascript/content/relational-operators@BbrrliATuH9beTypRaFey.md
- src/data/roadmaps/javascript/javascript.json
Relational and Conditional operators are the same thing, as even stated in the Relational Topic.
Removing this as requested in #7609
> removed relational operators in favour of conditional

- src/data/roadmaps/linux/content/110-disks-filesystems/100-inodes.md
From handle to handled, I believe this is grammatically correct.
> Fixes typo in 100-inodes.md: from handle to handled

- .gitignore
- src/components/Guide/GuideContent.astro
- src/components/Guide/RelatedGuides.tsx
- src/lib/guide.ts
- src/lib/markdown.ts
- src/pages/frontend/job-description.astro
> feat: related guides sidebar

- src/data/roadmaps/backend/content/unit-testing@3OYm6b9f6WOrKi4KTOZYK.md
I do think this node article resource wasn't good enough, seems like most of the text was AI generated (and it's not a tutorial 😆 ).
I don't know what you guys think about Wikipedia, but this article is significantly better.
> feat(backend): update unit testing node resources

- src/data/roadmaps/ai-engineer/content/ai-code-editors@XcKeQfpTA5ITgdX51I4y-.md
Added PearAI to the list of AI Code Editors (An Open Source Option for developers!)
> Added PearAI to the list of AI Code Editors (An Open Source Option for developers!)

- src/data/roadmaps/software-architect/content/auth-strategies@KiwFXB6yd0go30zAFMTJt.md
Hello folks! I have added a guide on the difference between authentication and authorization since these terms are often confused. Thanks for considering my PR.
> Added article on AuthN vs AuthZ

- src/data/roadmaps/docker/content/107-container-registries/101-dockerhub-alt.md
Fix typo in dockerhub alternatives
> Fix typo in dockerhub alternatives

- src/data/roadmaps/engineering-manager/content/system-design-and-architecture@iX4HPgoiEbc_gze1A01n4.md
This PR adds a README.md file to provide a comprehensive guide for Engineering Managers focused on System Design and Architecture. The README includes:
An overview of system design and architecture tailored for engineering managers.
Links to key resources:
[System Design Roadmap](https://roadmap.sh/system-design)
[Software Architect Roadmap](https://roadmap.sh/software-architect)
> Update README for System Design and Architecture Resources

- src/data/guides/introduction-to-llms.md
…ctuation
- Editing the URL of the image, it was broken.
- Editing the URL of BERT, it was broken.
- Some punctuation corrections
> introduction-to-llms.md - editing a broken link and an image, and punctuation

- src/data/roadmaps/engineering-manager/content/what-is-engineering-management@_hYN0gEi9BL24nptEtXWU.md
Wrote the first article of the "Engineering Manager" roadmap, with a pointer to useful open source engineering manager resources on Github.
> What is engineering management?

- src/data/roadmaps/backend/content/scrypt@kGTALrvCpxyVCXHRmkI7s.md
Adds a link to the scrypt Wikipedia article.
> Adds Resources for scrypt

- src/data/roadmaps/linux/content/104-text-processing/index.md
Added Some Resources for Linux -> Text Processing
> Adding Resources in Linux

- src/data/roadmaps/frontend/content/angular@-bHFIiXnoUQSov64WI9yo.md
- src/data/roadmaps/frontend/content/angular@k6rp6Ua9qUEW_DA_fOg5u.md
- src/data/roadmaps/frontend/content/cypress@DaynCz5RR26gjT6N6gTDL.md
- src/data/roadmaps/frontend/content/eleventy@io0RHJWIcVxDhcYkV9d38.md
- src/data/roadmaps/frontend/content/npm@ib_FHinhrw8VuSet-xMF7.md
- src/data/roadmaps/frontend/content/sass@kukEE5rMSPa4NeNjx21kt.md
- src/data/roadmaps/frontend/content/svelte-kit@P4st_telfCwKLSAU2WsQP.md
- src/data/roadmaps/frontend/content/typescript@0asdhvwBH3gn-ercktV7A.md
- src/data/roadmaps/frontend/content/using-devtools@3_sJHKTogkDoCjR518-OL.md
- src/data/roadmaps/frontend/content/using-lighthouse@RIhHMHLsLLPhNl05Q9aBf.md
- src/data/roadmaps/frontend/content/vcs-hosting@MXnFhZlNB1zTsBFDyni9H.md
- src/data/roadmaps/frontend/content/version-control-systems@NIY7c4TQEEHx0hATu-k5C.md
- src/data/roadmaps/frontend/content/vite@0Awx3zEI5_gYEIrD7IVX6.md
- src/data/roadmaps/frontend/content/vuepress@CMrss8E2W0eA6DVEqtPjT.md
- src/data/roadmaps/frontend/content/webpack@twufEtHgxcRUWAUQ9bXus.md
Fixes #7825 and Minor Adjustments to Topic Links.
> Refractor Frontend Roadmap.

- src/data/projects/ec2-instance.md
There was a spelling mistake in the content. So corrected it.
> "Instances" Spelling Correction

- src/data/roadmaps/qa/content/accessibility-tests@mmDIqSD6MU3ZhWREGI5E2.md
- src/data/roadmaps/qa/content/ajax@jn02FD5hjhZFVWaJjjNN3.md
- src/data/roadmaps/qa/content/allure@jaHOo-vZGjTnABxQKMT3_.md
- src/data/roadmaps/qa/content/appium@UIKUiCfSw5MkrRJZ3Ah3x.md
- src/data/roadmaps/qa/content/artillery@j1DYOQbIUT1tw_9WIPBkE.md
- src/data/roadmaps/qa/content/assembla@xLPE9CqqiYz0miMFI3ThY.md
- src/data/roadmaps/qa/content/atlassian@wVqbs8Rh0WjLQqJZ0XiF0.md
- src/data/roadmaps/qa/content/authentication--authorization@75-XdVA4BL6UrcvpC9grx.md
- src/data/roadmaps/qa/content/axe@_4jJ8YQeLcaT-z38kxRRR.md
- src/data/roadmaps/qa/content/azure-devops-services@u0tKd7HZVN2gGv9Cz3jHz.md
- src/data/roadmaps/qa/content/backend-automation@mPaMQ5h8ZcXKOfcuSwB2-.md
- src/data/roadmaps/qa/content/bamboo@j4J5OhHEf7t-LVNkNVW3M.md
- src/data/roadmaps/qa/content/bitbucket@4xlbvY7NS3cemSZsEQAkD.md
- src/data/roadmaps/qa/content/browser--dev-tools@cHI05cf8fLh3XB1Bt6jNP.md
- src/data/roadmaps/qa/content/caching@qvlA7iIOvoWMXm5MCAysZ.md
- src/data/roadmaps/qa/content/chrome-devtools@Xadg2WZTz6Cc_Ir9FsbgY.md
- src/data/roadmaps/qa/content/circle-ci@z1kZkWTL_RRPZY59aWylU.md
- src/data/roadmaps/qa/content/cypress@5cMhZ-7YMQ6ccs-AaIi-0.md
- src/data/roadmaps/qa/content/cypress@D7zGshmgwqWluF-W7OTWe.md
- src/data/roadmaps/qa/content/cypress@iQ7xwiA6xmbLyRIkI7tXM.md
- src/data/roadmaps/qa/content/datadog@Y2I_dcVZb4xZremXoajjx.md
- src/data/roadmaps/qa/content/detox@gZnNHDjFMI003Od7u2RNa.md
- src/data/roadmaps/qa/content/drone@3oDyxhhbCCqxuCh1sT9VC.md
> [!TIP]
> ## QA Roadmap - Part 1
**Topic Links Fixes and Improvements.**
> Refractor QA Roadmap - 1st

- src/data/roadmaps/qa/content/espresso@stMeB1U3SfuefZ-yS8wGF.md
- src/data/roadmaps/qa/content/frontend-automation@hU5OCnEe3tG206xuGsVFd.md
- src/data/roadmaps/qa/content/gatling@J1Yx1VcO20Lc3r3PdGpUW.md
- src/data/roadmaps/qa/content/ghost-inspector@mX7bNNP7WjFdlsRK6qIgy.md
- src/data/roadmaps/qa/content/git@WrqKdOTRUiOnc1aIhTZeB.md
- src/data/roadmaps/qa/content/github@v4gjV1qolrFXdESrY9bzG.md
- src/data/roadmaps/qa/content/gitlab-ci@iW3oaTl7c3a1kNlCKy-13.md
- src/data/roadmaps/qa/content/gitlab@RfwyTgwfb_xu5H9N-8_s9.md
- src/data/roadmaps/qa/content/gmail-tester@mIM9ausl_tSUNPUerIfEr.md
- src/data/roadmaps/qa/content/grafana@8CztIu0BOPZZRZsqR9asW.md
- src/data/roadmaps/qa/content/html-css-javascript@pYkfl-4gMHRj9wIeH8RTP.md
- src/data/roadmaps/qa/content/html-unit@-Sf7DLr8Ywoorrmsx3bfd.md
- src/data/roadmaps/qa/content/jasmine@HP55XWH18THmCNjCq-gBl.md
- src/data/roadmaps/qa/content/jenkins@3l2dkN1vBy9johFhAgZhT.md
- src/data/roadmaps/qa/content/jest@ZeJSeYs8fkZLQ-Pc3TqEM.md
- src/data/roadmaps/qa/content/jmeter@UeeDNUPZ61_HHgcaF9-__.md
- src/data/roadmaps/qa/content/k6@Jcp29_ASj9QZ_DjDBIapJ.md
- src/data/roadmaps/qa/content/kanban@cJyQx-LBcOL11nkK-P2JH.md
- src/data/roadmaps/qa/content/karateframework@8zXn8R9OGWTmreBpstj03.md
- src/data/roadmaps/qa/content/kibana@DCZyXcx8H2MTPcyKOhn2_.md
- src/data/roadmaps/qa/content/lighthouse@fkUxhrP3LhtIVgIP9Dxar.md
- src/data/roadmaps/qa/content/locust@QjAJIfSQe7WjbyYdGWSP8.md
- src/data/roadmaps/qa/content/monitoring--logs@pJvijtG-a0vOq16EFu3Gr.md
- src/data/roadmaps/qa/content/new-relic@QnNUZQlQ2Jhv34daeIuW8.md
- src/data/roadmaps/qa/content/nightwatch@Ta1leBdu-Y9LryB-0U-CT.md
> [!TIP]
> ## QA Roadmap - Part 2
**Topic Links Fixes and Improvements.**
> Refractor QA Roadmap - 2nd

- src/data/roadmaps/linux/content/105-server-review/100-uptime-load.md
> Resource for Uptime Load in Linux

- src/data/roadmaps/data-analyst/data-analyst.json
I discovered a grammatical error where "Analaysis" was written instead of "Analysis"
> Update data-analyst.json (Grammatical Mistake - Analaysis)

- src/data/roadmaps/devops/content/programming-language@v5FGKQc-_7NYEsWjmTEuq.md
Possible fix for #7874
Spawn `src/data/roadmaps/devops/content/programming-language@v5FGKQc-_7NYEsWjmTEuq.md` back again.
> fix: rollback a previously deleted file.

- src/data/roadmaps/sql/content/check@Q0h9Wfnl_W9ThOkv7Q17A.md
This PR fixes #7886
I replaced the missing resource that returns a 404 with a short and comprehensive video found on YouTube.
> fix: src/data/roadmaps/sql/content/check@Q0h9Wfnl_W9ThOkv7Q17A.md (#issue-2740359828)

- .github/workflows/greetings.yml
- .github/workflows/upgrade-dependencies.yml
Added New Github Actions Workflow that greets first time contributors only.
> feat: greetings ci

- src/data/roadmaps/software-architect/content/ddd@IIelzs8XYMPnXabFKRI51.md
The process described over there will most-likely help newcomers to understand what is DDD, and that it is much more than a set of tactical design patterns. It will guide them to understand the strength of bounded contexts, help them shape them by discovering business boundaries (in language, cash-flow, processes, ...), as well as help them understand when NOT to use Aggregate, Repository, Entity, etc.
It will introduce them to a world of strong and efficient visual collaboration through EventStorming and other practical workshops.
> Guide DDD newcomers towards the Starter Modelling Process

- src/data/roadmaps/python/content/paradigms@4GU5HNi3W8yFkImVY9ZpW.md
I think this video is an excellent resource for teaching functional programming concepts for Python. It covers a lot of good concepts like pure functions, first class functions, decorators, etc..
> Add Python Functional Programming Video

- src/data/roadmaps/php/content/what-is-php@_LhLDVZjLt1DoAP1NuUES.md
> Fix what-is-php@_LhLDVZjLt1DoAP1NuUES.md

- src/data/roadmaps/docker/content/102-installation-setup/100-docker-desktop.md
Updates the Docker Desktop description to include Linux as a supported platform and further clarifies that it is GUI-based.
> Update on Docker Desktop info to clear possible confusion

- src/data/roadmaps/golang/content/104-go-web-frameworks/index.md
> Add Web Frameworks

- src/data/roadmaps/system-design/content/synchronous-io@Ihnmxo_bVgZABDwg1QGGk.md
Fixing visual bug due to a link getting into the main list and not being parsed correctly
> Update synchronous-io external article link display bug

- src/data/guides/frontend-developer-skills.md
- src/data/guides/frontend-job-description.md
- src/data/guides/frontend-languages.md
- src/data/guides/frontend-technologies.md
- src/data/guides/full-stack-developer-skills.md
- src/data/guides/full-stack-job-description.md
- src/data/guides/full-stack-vs-backend.md
- src/data/guides/full-stack-vs-software-engineer.md
fix: minor fixes in both frontend & full stack guides
> refractor: cleanup and optimize few guides.

- src/data/question-groups/devops/content/cicd-setup.md
- src/data/question-groups/devops/content/docker-compose.md
- src/data/question-groups/devops/content/health-monitor.md
- src/data/question-groups/devops/content/microservice-challenges.md
- src/data/question-groups/devops/content/popular-cicd-tools.md
- src/data/question-groups/devops/devops.md
> [!TIP]
> Improved Devops Questions Group.
> Improve Devops Questions Group.

- src/data/question-groups/backend/backend.md
- src/data/question-groups/backend/content/distributed-caching.md
- src/data/question-groups/backend/content/sql-vs-nosql.md
> [!TIP]
> Improve Backend Question Groups.
> Improve Backend Questions Group.

- src/components/UserProgress/UserProgressModalHeader.tsx
> fix: user progress modal percentage

- src/data/roadmaps/frontend/content/css@ZhJhf1M2OphYbEmduFq-9.md
Added "freeCodeCamp | Responsive Web Design Certification" to HTML and CSS. [url: "
https://www.freecodecamp.org/learn/2022/responsive-web-design/
"]
It is a free certification with step-by-step guided projects in HTML & CSS. You create a webpage portfolio as the final project.
> Update css@ZhJhf1M2OphYbEmduFq-9.md --added free course-cert link to CSS

- src/data/roadmaps/data-analyst/content/what-is-data-analytics@yCnn-NfSxIybUQ2iTuUGq.md
More resources had wrong tag "@articles". Changed it to "@course"
> Updated correct tag for more resources

- src/data/roadmaps/php/content/symfony@57VSMVePOr9qUD5x_LNdf.md
Just a small typo, nothing fancy
> Fix typo in Symfony detail description

- src/data/roadmaps/golang/content/102-go-building-clis/102-bubbletea.md
Hi, thanks for nice work. I'm using this to learn Golang also.
I added [bubbletea](https://github.com/charmbracelet/bubbletea) which is also good for build CLI / TUI applications in Golang. that mentioned already in issue #7846 too.
I checked resources are fine.
Thanks.
> Add bubbletea to Golang's CLI development 

- src/data/roadmaps/cloudflare/content/hono@-8MsWNvuqwQCbLpOx_kov.md
- src/data/roadmaps/cloudflare/content/itty-router@15jl6CSCkqnh_eFfysLDM.md
Since I have been more advanced for 2 years with Cloudflare works I thought I shared how I've learned the documentation. I will update this in the coming days.
So far the following things have been added;
- Added official documentation link to itty router
- Added official documentation link to hono js
- Added articles and videos to the hono js card.
- Added example projects for the itty router card.
- Added Use-cases for the hono js card.
this is my first time, I've tried to use the [contributing guidelines](https://github.com/kamranahmedse/developer-roadmap/blob/3dd115dce12d2a2ef229a396fd6ff9f568a2be4a/contributing.md#good-vs-not-so-good-contributions). If anything is wrong, please give me feedback.
> Cloudflare Roadmap - Update Cloudflare Hono & Itty Router

- src/data/roadmaps/ai-data-scientist/content/machine-learning@kBdt_t2SvVsY3blfubWIz.md
Links from towardsdatascience.com shows 404. so I replaced them with medium ones
> Update 404 links in towarddatascience site to medium ones

- src/data/roadmaps/python/content/methods-dunder@zAS4YiEJ6VPsyABrkIG8i.md
- src/data/roadmaps/python/content/object-oriented-programming@P_Di-XPSDITmU3xKQew8G.md
- src/data/roadmaps/python/content/ruff@6cB0pvUO1-gvCtgqozP-Q.md
> Fix small typos 2

- public/roadmap-content/python.json
+ I add a detail article about python dependency management, hope it provide full picture for learners.
> chore: update roadmap content json about python dependency management

- src/data/roadmaps/game-developer/content/cc@jsq0UXnIIC0Z_nbK2w48f.md
- src/data/roadmaps/server-side-game-developer/content/cc@E4H3hniIW6hKpH3Qr--N5.md
- Update the resource link for C, because the link points to a withdrawn ISO document. I replaced it with its Wikipedia page.
- The same resources added to the C / C++ section of Server Side Game Development roadmap.
> Update resources related to C / C++

- src/data/guides/go-vs-java.md
- src/data/guides/golang-rest-api.md
- src/data/guides/torrent-client.md
I ran `gofmt` on all go code examples. This is the result.
> Use `gofmt` compliant formatting 

- src/data/roadmaps/cloudflare/content/basic-command-line-knowledge@q9oQTt_NqhdWvJfA5XH1V.md
- src/data/roadmaps/cloudflare/content/git-basics@C08pIguX1N45Iw0kh0Fvu.md
- src/data/roadmaps/cloudflare/content/http-and-web-protocols@9iSdASlRxyod9YwZ2IUry.md
- src/data/roadmaps/cloudflare/content/javascript-fundamentals@PcYnYAAkKMbzoiCnBfjqO.md
- src/data/roadmaps/cloudflare/content/nodejs-and-npm@dSBYTGGkol3MAXyg7G7_J.md
- src/data/roadmaps/cloudflare/content/typescript-fundamentals@zR84MFLL6y0dygz9hXXPA.md
- src/data/roadmaps/cloudflare/content/understand-serverless-architecture@Isl5anwDvb1MacA-JH4ej.md
added content to all prerequisites topics and core dev skills.
> feat: add content to few topics in cloudflare roadmap.

- src/data/roadmaps/data-analyst/content/replace--substitute@dke_pySrqYZZ7K3rprnIT.md
Replace Microsoft Access "replace function" link with Microsoft Excel "replace function" link.
> Update replace MS Access link with MS Excel link for "Replace" function

- src/data/roadmaps/java/content/exception-handling@g9P3548F38tYGjevBc42w.md
The mentioned resource was not free (requires a member subscription)
> Update exception-handling for Java path

- src/components/GenerateCourse/AICourseCard.tsx
- src/components/GenerateCourse/AICourseSearch.tsx
- src/components/GenerateCourse/UserCoursesList.tsx
- src/components/Pagination/Pagination.tsx
- src/queries/ai-course.ts
> feat: ai course pagination

- src/data/roadmaps/aspnet-core/content/stylecop-rules@R7Qk5hsEIl9dspQXdaJAJ.md
Added content explaining what StyleCop is and what it brings to the table. Also added links to extra resources.
> Added content for StyleCop section

- src/components/GenerateCourse/AICourseActions.tsx
- src/components/GenerateCourse/AICourseCard.tsx
> feat: delete ai course

- src/data/roadmaps/cyber-security/content/brute-force-vs-password-spray@Q0i-plPQkb_NIvOQBVaDd.md
Fixed a typo in cybersecurity roadmap specifically in brute force vs password spraying section
> Fixed a typo in brute-force-vs-password-spray@Q0i-plPQkb_NIvOQBVaDd.md

- src/data/roadmaps/cpp/content/c-vs-c@2Ag0t3LPryTF8khHLRfy-.md
- src/data/roadmaps/cpp/content/compilers@FTMHsUiE8isD_OVZr62Xc.md
- src/data/roadmaps/cpp/content/containers@1pydf-SR0QUfVNuBEyvzc.md
- src/data/roadmaps/cpp/content/copy-on-write@O2Du5gHHxFxAI2u5uO8wu.md
- src/data/roadmaps/cpp/content/crtp@ttt-yeIi4BPWrgvW324W7.md
- src/data/roadmaps/cpp/content/diamond-inheritance@ofwdZm05AUqCIWmfgGHk8.md
- src/data/roadmaps/cpp/content/dynamic-polymorphism@7h1VivjCPDwriL7FirtFv.md
- src/data/roadmaps/cpp/content/dynamic_cast@4BdFcuQ5KNW94cu2jz-vE.md
- src/data/roadmaps/cpp/content/exit-codes@oWygnpwHq2poXQMTTSCpl.md
- src/data/roadmaps/cpp/content/full-template-specialization@6hTcmJwNnQstbWWzNCfTe.md
- src/data/roadmaps/cpp/content/headers--cpp-files@CK7yf8Bo7kfbV6x2tZTrh.md
- src/data/roadmaps/cpp/content/iostream@VeVxZ230xkesQsIDig8zQ.md
- src/data/roadmaps/cpp/content/lambdas@xjiFBVe-VGqCqWfkPVGKf.md
- src/data/roadmaps/cpp/content/logical-operators@Y9gq8WkDA_XGe68JkY2UZ.md
- src/data/roadmaps/cpp/content/multiple-inheritance@WjHpueZDK-d3oDNMVZi9w.md
- src/data/roadmaps/cpp/content/multithreading@OXQUPqxzs1-giAACwl3X1.md
- src/data/roadmaps/cpp/content/object-oriented-programming@b3-QYKNcW3LYCNOza3Olf.md
- src/data/roadmaps/cpp/content/pimpl@MEoWt8NKjPLVTeGgYf3cR.md
- src/data/roadmaps/cpp/content/running-your-first-program@SEq0D2Zg5WTsIDtd1hW9f.md
- src/data/roadmaps/cpp/content/setting-up-your-environment@Zc_TTzmM36yWsu3GvOy9x.md
- src/data/roadmaps/cpp/content/sfinae@3C5UfejDX-1Z8ZF6C53xD.md
The code like
```cpp
std::cout << "Hello!" << '\n';
```
should be replaced by
```cpp
std::cout << "Hello!\n";
```
This was part of #8251 (cf. ecbb625a093a44f204095cb7852b342df11dfe07).
@kamranahmedse  - please have a look.
> Join strings and newline char

- src/data/roadmaps/javascript/content/built-in-functions@s8wUJivWmetysJ8bt9FBC.md
The previous description primarily explained methods rather than built-in functions, which could cause confusion. This update provides a clearer explanation of built-in functions, including examples like parseInt(), setTimeout(), and Math.random(), while also acknowledging built-in methods within JavaScript objects.
This ensures that the description aligns with the section title and provides more accurate information for learners.
>  Corrected description for "Built-in Functions" section

- src/data/roadmaps/mongodb/content/108-developer-tools/100-language-drivers.md
This PR restructures the Language Drivers section and resolves the issue where the list of supported drivers was missing. 
The updated version improves readability, includes a proper list of popular MongoDB drivers, and adds relevant documentation links for further reference.
Issue: #8367
> Update 100-language-drivers.md --> 'Restructure and Fix Missing Language Drivers List'.

- src/data/roadmaps/server-side-game-developer/content/channel@SXOEMkcVYBsRza6BPmmwy.md
- src/data/roadmaps/server-side-game-developer/content/congestion-control@1GML0Jsfdb1Fn-0PNryiQ.md
- src/data/roadmaps/server-side-game-developer/content/coroutine@o0Y_hM0KXUApfsXG4PvOY.md
- src/data/roadmaps/server-side-game-developer/content/error-detection@vFM311xSa5OqNVove2f6j.md
- src/data/roadmaps/server-side-game-developer/content/flow-control@lDVD-3i64Mk7-KPJrXmFH.md
- src/data/roadmaps/server-side-game-developer/content/max-segment-size@w6ysmcsBn9jJ8xMvg7hcD.md
- src/data/roadmaps/server-side-game-developer/content/reliable-transmission@X2KHWgQZDHSVDsTRMUwSj.md
This is the second pull request to enhance the `Server-Side Game Developer` Roadmap by adding other missing content to improve clarity and usability for developers. 
The updates include detailed information on the following topics:  
- **coroutine**
- **flow-control**
- **reliable-transmission**
- **congestion-control**
- **error-detection**
- **max segment size**
These additions aim to make the roadmap more comprehensive and valuable for developers working on server-side game development.
issue: #8406
> Update other missing content in the `Server-Side Game Developer` Roadmap.

- src/data/roadmaps/full-stack/content/git@We2APJpOPTr-VNfowG0kI.md
Replace Git & GitHub Crash Course For Beginner with Git & GitHub Crash Course For Beginner 2025 made by the same guy.
closes: #8116
> Update resource git@We2APJpOPTr-VNfowG0kI.md

- src/data/roadmaps/linux/content/process-management/proc-priorities.md
Added `comm` to make it easier to read: #7608.
> Doc: Proc Priorities Under Process Management

- src/data/roadmaps/qa/content/regression-testing@XCeXiKvBblmDArfbWjDvw.md
The QA roadmap does not have any resources for Regression Testing. I have added three resources for it.
> Add resources

- src/data/roadmaps/ai-engineer/content/image-understanding@fzVq4hGoa2gdbIzoyY1Zp.md
Previous article gives 404 (https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding) New article linked in this PR (https://platform.openai.com/docs/guides/images)
> Update openai article for image understanding

- src/components/Projects/CompleteProjectConfirmation.tsx
- src/components/Projects/ProjectTabs.tsx
- src/components/Projects/StartProjectConfirmation.tsx
- src/components/Projects/StartProjectModal.tsx
- src/components/Projects/StatusStepper/ProjectStepper.tsx
- src/components/Projects/StatusStepper/ProjectTrackingActions.tsx
- src/lib/project.ts
- src/pages/projects/[projectId]/index.astro
- src/pages/projects/[projectId]/solutions.astro
- src/queries/project.ts
> feat: project without submission

- src/data/roadmaps/cyber-security/content/learn-how-malware-works-and-types@v7CD_sHqLWbm9ibXXESIK.md
- src/data/roadmaps/cyber-security/content/legal@C5bCIdPi0gGkY_r4qqoXZ.md
- src/data/roadmaps/cyber-security/content/linux@4frVcjYI1VlVU9hQgpwcT.md
- src/data/roadmaps/cyber-security/content/local-auth@vYvFuz7lAJXZ1vK_4999a.md
- src/data/roadmaps/cyber-security/content/lolbas@10qbxX8DCrfyH7tgYexxQ.md
- src/data/roadmaps/cyber-security/content/loopback@W_oloLu2Euz5zRSy7v_T8.md
- src/data/roadmaps/cyber-security/content/macos@dztwr-DSckggQbcNIi4_2.md
- src/data/roadmaps/cyber-security/content/memdump@wspNQPmqWRjKoFm6x_bVw.md
- src/data/roadmaps/cyber-security/content/memory-leak@nOND14t7ISgSH3zNpV3F8.md
- src/data/roadmaps/cyber-security/content/mesh@PYeF15e7iVB9seFrrO7W6.md
- src/data/roadmaps/cyber-security/content/mitm@ODlVT6MhV-RVUbRMG0mHi.md
- src/data/roadmaps/cyber-security/content/nac-based@6oAzYfwsHQYNVbi7c2Tly.md
- src/data/roadmaps/cyber-security/content/netflow@xXz-SwvXA2cLfdCd-hLtW.md
- src/data/roadmaps/cyber-security/content/nids@LIPtxl_oKZRcbvXT4EdNf.md
- src/data/roadmaps/cyber-security/content/nist@SOkJUTd1NUKSwYMIprv4m.md
- src/data/roadmaps/cyber-security/content/nmap@Hoou7kWyfB2wx_yFHug_H.md
- src/data/roadmaps/cyber-security/content/ntp@tf0TymdPHbplDHvuVIIh4.md
*these commits are cherry picked accordingly. Sorry for multiple pr(s).*
> cybersecurity: fix topic links and content

- src/data/roadmaps/ai-data-scientist/content/ab-testing@mJq9b50MJM9o9dLhx40iN.md
Fixes https://github.com/kamranahmedse/developer-roadmap/issues/8534
> Fixed link of Experimental Design Article of AI Data Scientist roadmap

- src/components/TopicDetail/TopicDetailAI.tsx
> fix: add a default subject

- src/lib/config.ts
> seo: update latest roadmap keywords

- src/data/roadmaps/ai-engineer/content/ollama@rTT2UnvqFO3GH6ThPLEjO.md
Hello! I noticed that there's only one article resource about Ollama other than the official website, so I wanted to provide this whiteboard video from IBM Technology explaining Ollama, the CLI, model server, etc for my visual learning friends ٩(◕‿◕｡)۶
> feat: Update Ollama base page with additional video content

- src/data/roadmaps/cyber-security/content/comptia-security@AxeDcKK3cUtEojtHQPBw7.md
Added link to Prof. Messer's playlist on the latest CompTIA Security+ exam
> Update comptia-security course resources

- src/data/roadmaps/ai-engineer/ai-engineer.md
Replaced broken link 'advantages and disadvantages of AI' present on 'AI Engineer' roadmap
> replaced broken link 'advantages and disadvantages of AI'

- src/data/roadmaps/vue/content/api-styles@OpJ2NMKCGXQezpzURE45R.md
Some of this wasn't factually accurate. I've corrected it and added more information to give people new to Vue a better primer to these different API approaches. This is the main part of Vue 3 that adds complexity to onboarding new Vue devs that Vue 2 didn't have to deal with. So it's important to speak clearly and accurately about this part of Vue.
> Update Vue api-styles.md

- src/data/roadmaps/vue/content/composition-api@a0qwdQTunxEjQ9A5wpF-q.md
Like the Options-API PR, this is updating the description to be less biased, and focus on the specific benefits of the API.
> Update Vue composition-api.md

- src/data/roadmaps/php/content/csrf-protection@J9yIXZTtwbFzH2u4dI1ep.md
- src/data/roadmaps/php/content/inheritance@c5q2e_jyMt8Pir5Od3lRi.md
- src/data/roadmaps/php/content/polymorphism@gtq5KrghF28f5G8nuDcYQ.md
> Fix broken links in PHP roadmap

- public/roadmap-content/ux-design.json
- src/data/roadmaps/ux-design/content/figma@t46s6Piyd8MoJYzdDTsjr.md
Enhanced existing content for the ux design roadmap by including a free course resource in the figma section(not by me) that is really helpful in learning the basics.
> Add content to  ux design roadmap

- src/data/roadmaps/aspnet-core/content/autofixture@K49M_7gSpfJuZaE6WaHxQ.md
Added AutoFixture content and resources under .NET testing tools, used the official AutoFixture documentation
> Add content and resources for AutoFixture in dot-net roadmap

- src/data/roadmaps/linux/content/networking/ethernet-arp-rarp.md
Added 2 helpful videos explaining ARP and Ethernet to the relevant section
> Add resources to Linux -> Networking -> Ethernet, ARP and RARP

- src/components/GenerateCourse/AICourseContent.tsx
> fix: progress percentage

- src/components/Projects/SubmitProjectModal.tsx
Modal Wrapper Provides close button.
> (fix): remove extra close button

- src/data/roadmaps/golang/content/go-advanced/generics.md
Closes https://github.com/kamranahmedse/developer-roadmap/issues/8757
> fix Generics video link

- src/data/roadmaps/nodejs/content/npm-workspaces@WvxCGVKLvTUVEHeOcUQPg.md
The blog entry moved, I fixed the link
> Fix wrong link to workspaces blog entry

- src/data/roadmaps/ai-data-scientist/ai-data-scientist.json
- src/data/roadmaps/ai-data-scientist/content/data-understanding-data-analysis-and-visualization@JaN8YhMeN3whAe2TCXvw9.md
**Issues**
- Fixes #8264 
- Fixes #8481 
**Changes**
- Replace course link for "Exploratory Data Analysis with Seaborn"
- Update title and link for "Experiment Design Article"
> Fix ai-data-scientist roadmap links

- .astro/types.d.ts
- src/components/AITutor/AITutorSidebar.tsx
- src/components/ContentGenerator/ContentGenerator.tsx
- src/components/Premium/FeatureCard.tsx
- src/components/Premium/PremiumPage.tsx
- src/components/Premium/constants.ts
- Add links to the feature cards
- Add demo button
- Rearrange features
- Improve sidebar for AI tutor
> Improve AI Tutor landing page, and Sidebar

- src/data/best-practices/backend-performance/content/enable-compression.md
- src/data/best-practices/backend-performance/content/pagination-large-data.md
- src/data/best-practices/backend-performance/content/reasonable-payload.md
- src/data/best-practices/backend-performance/content/unnecessary-computation.md
Modified the following to add external resources to optimize backend performance content.
- src/data/best-practices/backend-performance/content/enable-compression.md
- src/data/best-practices/backend-performance/content/pagination-large-data.md
- src/data/best-practices/backend-performance/content/reasonable-payload.md
- src/data/best-practices/backend-performance/content/unnecessary-computation.md
> Added external resources for optimizing backend performance.

- src/data/roadmaps/graphql/content/multiple-fields-in-mutation@AySlY8AyI6jE-cy-qKKOU.md
Seems like the current link is stale
> Fix link in multiple-fields-in-mutation@AySlY8AyI6jE-cy-qKKOU.md

- src/data/roadmaps/blockchain/content/why-it-matters@ecT4W5z8Vq9pXjnuhMdpl.md
Article by Forbes from 2020 is outdated. The new article from Hedera provides more details on how blockchain matters by discussing new advancements, such as IoT and tokenization.
> Replaced outdated 2020 article with new Hedera article on why blockchain matters

- src/data/best-practices/backend-performance/content/cache-invalidation.md
- src/data/best-practices/backend-performance/content/caching-strategies.md
- src/data/best-practices/backend-performance/content/utilize-caching.md
I have added some external resources to:
- src\data\best-practices\backend-performance\content\cache-invalidation.md
- src\data\best-practices\backend-performance\content\caching-strategies.md
- src\data\best-practices\backend-performance\content\utilize-caching.md
> Add caching resources for backend performance best practises

- src/data/roadmaps/golang/content/var-vs@pJUkMcrUvcxuR_w89-eEq.md
Added definition for var and :=.
> Added content for var vs :=

- src/data/roadmaps/docker/content/underlying-technologies@jrH1qE6EnFXL4fTyYU8gR.md
Useful, brief video that covers the underlying subjects
> add video @ docker/underlying-technologies

- src/data/roadmaps/devops/content/ansible@h9vVPOmdUSeEGVQQaSTH5.md
This a full Ansible Course I took and it really helped me to upskill. I believe the community will benefit a lot from this course.
> Update ansible@h9vVPOmdUSeEGVQQaSTH5.md with a new crash course

- src/components/TopicDetail/TopicDetail.tsx
> chore: ai tutor courses
