- CHANGELOG.md
N/A, targets the Changelog markdown file.
Simple PR to fix the 3 broken URL's leading to the pdf versions of the three roadmaps.
> removing static url error from pdf links in changelog

- readme.md
The link, `https://roadmap.sh/dba`, to the DBA guide in the GitHub README doc does not work. This update fixes the link in the README to be the same one on the website homepage.
> Fix DBA Link that 404s

- public/project/backend.json
- [x ] Code Change
- [ x] Backend Roadmap
- [x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
The button / node "CDN and how it works" wasn't working because it was inside a 'g' tag without any classes unlike the other nodes.
The problem was caused due to the object of the node inside "backend.json" had a type __group__ object instead of the actual children elements in the "children" property.
> Fixed 'dns and how it works' button/node

- content/roadmaps/100-frontend/content/119-graphql/101-relay-modern.md
The link for the official website of Relay is displayed thrice
fixes #1076
> Remove redundant link

- content/roadmaps/100-frontend/content/102-css/readme.md
- content/roadmaps/101-backend/content/101-basic-frontend/101-css.md
The backend basic frontend section (CSS) and front end (CSS) had the same broken link to the flexbox.io resource due to a typo/duplicated href within the URL. Addresses #1101. Sorry for opening a PR before creating an issue, I wasn't sure the best practice for such a minor fix.
> Repaired broken flexbox.io link in Backend Frontend Basics (CSS)

- content/roadmaps/100-frontend/content/101-html/100-learn-the-basics.md
- content/roadmaps/100-frontend/content/101-html/readme.md
- content/roadmaps/101-backend/content/101-basic-frontend/100-html.md
In all official standards, for example, starting with [RFC 1866](https://datatracker.ietf.org/doc/html/rfc1866), `HTML` stands like `HyperText Markup Language`. Not like `Hyper Text Markup Language`. `HyperText` - this is one word. But `T` in uppercase can to serve for a better understanding the stands of abbreviation, and it should be left.
Also, we can see this in [Wiki page about HTML](https://en.wikipedia.org/wiki/HTML).
> HTML abbreviation – fixed typo.

- content/roadmaps.json
- content/roadmaps/107-golang/meta.json
- content/roadmaps/108-java/meta.json
I have not discussed this in issues yet, but it's just a simple typo fix in Go and Java roadmap meta descriptions.  
They still had the React developer meta descriptions.
> Fixed typo in Java and Go meta descriptions

- content/roadmaps/100-frontend/content/117-progressive-web-apps/readme.md
- [] Code Change
- [] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
[Issue #1271] Fixed a typo that was causing missing "read" label on a resource link in frontend developer roadmap, pwa node.
> Fixed issue #1271 - missing read label

- content/roadmaps/100-frontend/content/100-internet/101-what-is-http.md
I noticed a single forwardslash broke the link for the "Journey to HTTP/2" article. Same as commit 9a212dc but for the front-end roadmap.
> Fixed link to "Journey to HTTP/2" article

- contributing/readme.md
- Changed "represents" to "represent" because the former is used with singular nouns, while the latter is used with plural nouns (e.g., roadmaps)
- Added commas to "i.e." and "e.g."
- Changed ! to an interrobang (?!)
- Added determiners (the) to "value" and "curator"
> Corrected Grammar Errors

- content/roadmaps/102-devops/content/105-infrastructure-as-code/100-service-mesh/readme.md
I'm proposing putting in a "latest news" links to The New Stack, where Roadmap and TNS categories overlap. The link here leads to an auto-updated TNS page with the latest news tagged with "service mesh."
> TNS Latest News

- readme.md
We should inciude the word "the" before "website".
```diff
- Roadmaps are being made interactive and have been moved to website.
+ Roadmaps are being made interactive and have been moved to the website.
```
> Tiny little grammer correction early in the README

- next.config.js
Adding a default locale to the html generated by next.js, this PR will boost the lighthouse metrics, look below for further information in the screenshot.
> feat: Add english as a defautl html lang

- content/roadmaps/100-frontend/content/110-build-tools/102-linters-formatters/100-prettier.md
There are some typos in Frontend (Build Tools [Linters Formatters] Section) so I fixed this. @kamranahmedse
> Frontend Build-Tools Linters-Formatters Typos-Fixed

- content/roadmaps/100-frontend/content/110-build-tools/101-module-bundlers/102-rollup.md
- content/roadmaps/100-frontend/content/110-build-tools/101-module-bundlers/104-vite.md
- content/roadmaps/100-frontend/content/110-build-tools/101-module-bundlers/readme.md
There are some typos in Frontend (Build Tools [Module Bundlers] Section) so I fixed this. @kamranahmedse
> Frontend Build-Tools Module-Bundlers Typos-Fixed

- content/roadmaps/102-devops/content/101-os-concepts/106-posix.md
- content/roadmaps/102-devops/content/101-os-concepts/110-threads-concurrency.md
There are some typos in DevOps (OS Concepts Section) so I fixed this. @kamranahmedse
> Devops OS Concepts Typos Fixed

- content/roadmaps/106-javascript/content/115-javascript-modules/100-commonjs.md
- content/roadmaps/106-javascript/content/115-javascript-modules/101-esm.md
Add in content with examples to the javascript roadmap in 115-javascript modules section for both 100-commonjs and 101-esm
> Javascript Roadmap Add module content

- content/roadmaps/114-software-architect/content/112-architect-frameworks/101-uml.md
This is hardly a change but I wrote the original UML Description and just noticed it was missing a word.
> Fix Typo in UML Description

- content/roadmaps/108-python/content/100-python-basics/102-conditionals.md
I believe that including match-case control flow to the conditionals node would be highly valuable for new learners without being cumbersome. Match-case is highly expressive and readable, and may be preferred over an if-elif-else statement in some situations. Match-case can do things that if-elif-else cannot, it can also make it easier to reason about and read conditonal logic for a program. For that reason I've added a single quality how-to article on the subject and amended the description to include it.
From the Python docs:
```python
match point:
case (0, 0):
print("Origin")
case (0, y):
print(f"Y={y}")
case (x, 0):
print(f"X={x}")
case (x, y):
print(f"X={x}, Y={y}")
case _:
raise ValueError("Not a point")
```
From the article:
```python
def file_handler_v1(command):
match …
```
> Include Python 3.10 match-case in conditionals

- content/roadmaps/107-android/landscape.md
I have added the content to Android Roadmap. This content is part of the issue raised by @DevCapu having the link below.
https://github.com/kamranahmedse/developer-roadmap/issues/1717
Jetpack compose is continuously improving and making android development easier with less code and better results. The UI improvement using the material design is also a concept that cannot be missed. I have added the content for Gradle as well on what it is and how to get started.
The course added by me is one of the best courses to get started with Android using Kotlin curated by google developers, it covers all the fundamentals and also gives badges to learners on completing a track, of course, the badges are displayed on the google developers profile of the learner.
@kamranahmedse Please review this PR …
> Added content to Android Roadmap (107-android)

- content/roadmaps/106-javascript/content/117-javascript-chrome-dev-tools/readme.md
`F12` open up Console tab in `Chrome`, `Mozilla`, `Brave` by default. However in `Microsoft Edge` it open up `Elements` panel.
> Adds shortcut for opening dev tools

- public/project/frontend.json
this PR solves suggestion [#2644](https://github.com/kamranahmedse/developer-roadmap/issues/2644)
previus
now
> fix typo to wrong direction on 'testing your apps'

- content/roadmaps/107-nodejs/content/110-nodejs-databases/100-relational/104-native-drivers.md
Just added an initial list with the main npm packages used to connect to the most common SQL databases without an ORM.
> Add content to Node.js > relational databases > native drivers

- content/pages/pdfs.md
The current link to the Go roadmap returns a 404. Changed the link in the document so it links to a live page.
> Fix link to Go roadmap

- content/roadmaps/110-java/content/103-java-web-frameworks/103-spark.md
- Removed `Play Framework Website` from Spark node. 
- Last three links were for Apache Spark which is a used for big-data
Spark Node fixed
Kindly review this PR.
> Java Roadmap Spark: Fixed Spark framework node

- content/roadmaps/100-frontend/content/118-server-side-rendering/100-react-js/readme.md
Fixed React Roadmap URL on Readme file that was pointing to the same Front-end Roadmap
> Fix React Roadmap URL on Readme file

- content/roadmaps/107-nodejs/content/102-nodejs-npm/100-npx.md
The npx node js package manager link was broken, that page didn't exist on the node js docs, added a new link to a good article for introduction to npx on medium.
> Fixed the issue of npx link broken.

- content/roadmaps/109-golang/content/101-go-advanced/102-types-and-type-assertions.md
Remove invalid resource from Golang 102-types-and-type-assertions.md The provided resource is a video about protocol buffers in Go, not types or type assertion
> Remove invalid resource Golang 102

- content/roadmaps/106-javascript/content/105-javascript-equality-comparisons/101-value-comparison-operators.md
Displays it in code format so that it is appears the same as the other operators.
Currently on the website, it appears like this, looking different than the other operators displayed.
This PR proposes to fix this anomaly.
> Fixes the `===` operator format

- content/roadmaps/107-nodejs/content/104-nodejs-async-programming/100-event-loop.md
Link updated for Event Loop resource redirecting to the official documentation in NodeJS roadmap.
Updated URL: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#what-is-the-event-loop
> Link updated for Event Loop resource

- src/roadmaps/frontend/faqs.astro
> fix: typo in the word development

- src/roadmaps/system-design/content/105-availability-patterns/101-replication.md
This is a very simple nitpick of a typo in the word "availability"
> Fix typo in "avaiability"

- src/roadmaps/frontend/content/123-bonus-content.md
I checked the existing issues and PRs and did not find a duplicate.
I fixed two typos in `src/roadmaps/frontend/content/123-bonus-content.md`:
- delete verb "are" where there already is the verb "have"
- delete duplicate of "but"
> Fix typos in frontend/123-bonus-content.md

- src/data/roadmaps/blockchain/content/103-smart-contracts/100-programming-languages/100-solidity.md
* Changed the typo 'blochain' to 'blockchain'
* Changed the typo 'compilling' to 'compiling'
> fix(blockchain-content): fix typo in blockchain solidity content

- src/data/roadmaps/blockchain/content/105-blockchain-security/101-tools/index.md
* Changed the incorrect spelling 'faily' to 'fairly'
* Changed the incorrect spelling 'propery' to 'properly'
> fix(blockchain-content): Fix typo in blockchain security tools content

- src/data/roadmaps/javascript/content/106-javascript-loops-iterations/103-for-statement.md
Removed unnecessary heading "code tag" that made heading hard to read.
> Fix: remove <code> tag from "The For Loop" heading

- src/data/roadmaps/backend/content/118-containerization/100-docker.md
- src/data/roadmaps/devops/content/105-infrastructure-as-code/100-docker.md
This is a [complete Docker course](https://boot.dev/learn/learn-docker) with text+video explanations. All the content is free and does not require a login.
To avoid logging in just use the "Browse the exercises" link below the "Demo a course" button.
Hope this is helpful, I noticed there aren't as many Docker resources as some of the other topics.
> Add the complete Docker course by Boot.dev to back-end and devops roadmaps

- src/components/UpcomingForm.astro
- src/data/roadmaps/react/content/102-components/101-functional-components.md
- src/data/roadmaps/react/content/102-components/102-jsx.md
Fix:
1. Roadmap's Upcoming button overlaps with the `Related Roadmaps` and `All Roadmaps →` buttons.
Docs(React):
1. Added **Your first component** and **Passing props to a component resources** from new react documentation in the Functional Component topic.
2. Added **Writing markup with JSX** in the JSX topic.
> fix: upcoming button overlap

- src/data/roadmaps/typescript/content/101-typescript-types/114-never.md
Replace a deprecated link with the [new](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-never-type) link for `never` type documentation
> Typescript roadmap: Replace deprecated link in 114-never.md

- src/data/roadmaps/react/content/104-hooks/101-writing-your-own-hooks.md
I think there is no need to use one more link for the exact same example. The link that I have removed, redirects the user to the old react documentation which is already listed in this md file as "Reusing Logic with Custom Hooks".
> Removed a link

- src/data/roadmaps/react/content/102-components/100-class-components.md
The  [Components and Props] uses an old link to the Documentation of React.
> update link to new React Documentation

- src/data/roadmaps/frontend/content/101-html/index.md
Fix(#3896) the broken link of [Web Development Basics](https://internetingishard.netlify.app/html-and-css/index.html) in the `frontend` roadmap.
> fix: broken link

- src/data/roadmaps/java/content/103-java-web-frameworks/101-spring-boot.md
I notice we have a Spring Boot roadmap that is not linked from Spring Boot item from Java roadmap.
> Adding link to Spring Boot roadmap from Java roadmap

- src/hooks/use-keydown.ts
Firefox uses the `CMD+K` shortcut for its search feat.
> CMD+K Firefox bug

- src/data/roadmaps/code-review/content/102-documentation.md
Not sure if that was actually on purpose, but that was still a typo 👀
> Fix typo in code review 102-documentation.md

- contributing.md
This resolves issue #4110.
As, the issue states, the link under the contributing.md docs was broken. It was linking to
```
https://github.com/kamranahmedse/developer-roadmap/tree/master/public/jsons
```
instead of
```
https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps
```
> Issue #4110 Broken Link Fix

- src/data/roadmaps/devops/devops.json
Updated from 'ext_link:roadmap.sh/python' to 'ext_link:roadmap.sh/backend' and 'ext_link:roadmap.sh/best-practices/aws'.
A couple of links in the 'DevOps Roadmap' within the 'Related Roadmaps' section had incorrect links for the 'Backend Roadmap' and 'AWS Best Practices'.
> Update ext_links in devops.json

- src/data/roadmaps/react/content/102-components/102-jsx.md
- src/data/roadmaps/react/content/103-rendering/100-component-life-cycle.md
- src/data/roadmaps/react/content/103-rendering/104-events.md
- src/data/roadmaps/react/content/103-rendering/105-high-order-components.md
- src/data/roadmaps/react/content/114-error-boundaries.md
Fixes #3982
- Updated link to **Error Boundary** from React documentation. [Error Boundaries in React](https://reactjs.org/docs/error-boundaries.html) -> [Error Boundaries in React](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)
- Actualized article about **JSX** and links to React documentation. Removed old [Introduction to JSX](https://reactjs.org/docs/introducing-jsx.html) and added [JavaScript in JSX with Curly Braces](https://react.dev/learn/javascript-in-jsx-with-curly-braces) in addition to [Writing markup with JSX]
- Updated description of **React Component Lifecycle** and changed the link from deprecated [The Component Lifecycle](https://reactjs.org/docs/react-component.html#the-component-lifecycle) to [Class …
> [React developer] Actualize links to React documentation

- src/data/roadmaps/javascript/content/108-javascript-expressions-and-operators/104-logical-operators.md
Removed dublicate link in JS roadmap
> Fix: removed dublicate link in 108-javascript-expressions-and-operators

- src/data/roadmaps/cpp/content/106-structuring-codebase/100-scope/100-namespaces.md
> fix(typo): fixed typo in cpp namespaces

- src/data/roadmaps/system-design/content/108-content-delivery-networks/101-pull-cdns.md
Hello team,
I've made some changes to fix a small issue in the codebase. This PR addresses the problem where 'CDNss' was incorrectly used instead of the correct form 'CDNs'. The unnecessary 's' at the end has been removed.
> Correct 'CDNss' to 'CDNs'

- src/data/roadmaps/typescript/content/106-functions/index.md
The syntax for Function Expression was incorrect. It was an example of a function declared using Function Declaration.
> Fixed: Function Expression Syntax

- src/data/roadmaps/react/content/102-components/101-functional-components.md
- Whilst following the React roadmap, the first link under "Functional Components" that points to `https://react.dev/reference/react/component`, should instead point to `https://react.dev/reference/react/components`, otherwise the user will be met with a "Not Found" page.
> fix: update link of "Functional Components and Props"

- src/data/roadmaps/sql/content/106-join-queries/index.md
removed the sentence:
"JOIN Queries
Absolutely, here’s a brief summary about SQL JOIN Queries:"
It's the same information as the sentence below and it doesn't give the impression it's answering anything.
> Removed duplicate sentence in SQL roadmap

- src/data/roadmaps/qa/content/102-qa-manual-testing/103-reporting.md
The current link is outdated
https://www.ministryoftesting.com/dojo/series/the-testing-planet-2019/lessons/the-art-of-the-bug-report
This is the new updated link.
https://www.ministryoftesting.com/articles/11b82aee?s_id=15465627
> QA Manual Testing 103-reporting: Incorrect link

- src/data/roadmaps/react/content/106-state-management/101-zustand.md
I found more obvious such resources list, with the documentation as  the starting resource and then the link for the repo as the next one
> fix: added link + rewritten link text react 106-state-management

- src/data/roadmaps/react/content/103-rendering/104-events.md
removed duplicate link in react roadmap section 103-rendering/104-events
> fix: removed duplicate link in react 103-rendering/104-events

- src/data/roadmaps/react/content/103-rendering/103-refs.md
removed duplicated link in react roadmap
> fix: removed duplicate link in react roadmap 103-rendering 103-refs

- src/data/roadmaps/python/content/100-python-basics/101-variables-and-datatypes.md
This PR fixes a link in the python roadmap variables and operators part.
Fixes: #4389
> fix: Python roadmap video link fixed

- src/data/roadmaps/cpp/content/111-templates/103-finae.md
When you try to use these function templates, there can be ambiguity issues. If you call foo with an arithmetic type, both template overloads will be considered valid, and the compiler won't know which one to choose.
To solve this problem, you need to use SFINAE with more complex conditions inside a single function definition.
> SFINAE fix (C++)

- src/data/roadmaps/backend/content/107-nosql-databases/100-document-databases.md
I have added the link of the new mongodb roadmap to the backend roadmap.
At the time of learning about non-relational databases I have always wanted to know where to start and the guide that mongo has is very basic, and the roadmap that is here is more dedicated so it is good to have it at hand.
> Add mongodb roadmap in backend content

- src/data/roadmaps/typescript/content/100-typescript/102-install-configure/100-tsconfig-json.md
This PR fixes - exclude outside from inside compilerOptions  
[https://roadmap.sh/typescript](https://roadmap.sh/typescript)
You have the example of tsconfig.json in one of the first sections (tsconfog.json).  
``` {
"compilerOptions": {
"target": "es5",
"module": "commonjs",
"strict": true,
"outDir": "./dist",
"rootDir": "./src",
},
"exclude": ["node_modules"],
"include": ["src"]
} 
```
Now "exclude" is outside of "compilerOptions"
Bug Fixes (non-breaking change which fixes an issue)
- Go to [https://roadmap.sh/typescript](https://roadmap.sh/typescript)
- Click on `tsconfig.json` in introduction's section 'Installation and configuration'
- See a side popup open
- See Popup heading 'tsconfig.json'
- See json changed section
> fix: exclude from inside compilerOptions to outside 

- src/data/roadmaps/aspnet-core/content/101-general-development-skills/103-http-https.md
Current URL directs to a non existant page.
> Update URL for "Enabling HTTPS on Your Servers" on ASP.NET roadmap

- src/data/roadmaps/ai-data-scientist/ai-data-scientist.json
This PR fixes - the incorrect route link to the "Deep Learning Book"
[https://roadmap.sh/ai-data-scientist](https://roadmap.sh/ai-data-scientist)
Bug Fixes (non-breaking change which fixes an issue)
- Go to [https://roadmap.sh/ai-data-scientist](https://roadmap.sh/ai-data-scientist)
- Scroll Down and go to 'Deep Learning' Section
- See there have 'Deep Learning Book' 
- Click on 'Deep Learning Book' button / text
- See Now you are redirecting on right page [https://www.deeplearningbook.org/](https://www.deeplearningbook.org/)
https://github.com/kamranahmedse/developer-roadmap/assets/76577184/b9ecc264-8430-4214-aeaa-202f3f890f2f
> [fix]: Change incorrect redirect url in 'Deep Learning Book'

- src/data/roadmaps/system-design/system-design.json
Fix typo, add missing "a" in "balancing" word.
> Update system-design.json fix typo

- src/data/roadmaps/typescript/content/112-advanced-types/103-template-literal-types.md
There was a mistake in how literal types should be defined
([docs](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#handbook-content))
[Playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcghgW2gXigAwLICcB06oDUUAzsFgJYB2A5gNwBQ9ANhMFJYhAIwBcsnUVJlxQAygnLAAFmlpQoAegVQA9gGtmrdpwBMfeEkHpsxPOMky5i5RCxYVWIA)
[Playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcghgW2gXigAwLICcB0UAkA3gM7BYCWAdgOYC+aA3AFBMA2EwUliEAjAFyweUVJlxQAygnLAAFoyhQA9EqgB7ANZsOXHgCZB8JCPTZieKTPkNFKqBCxY1WIA)
> fix(typescript): fix template lineral type definition

- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/102-evm-based/polygon.md
- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/103-l2-blockchains/index.md
- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/109-blockchains/103-l2-blockchains/polygon-zkevm.md
Updated the [blockchain developer roadmap](https://roadmap.sh/blockchain) to
- Correct whitepaper and intro links in the Polygon section
- Add CDK open source resource for developing L2s to L2s info section
- Create a new Polygon zkEVM page within the L2s section
> correct Polygon resource links and add Polygon zkEVM and CDK information

- src/data/roadmaps/backend/content/103-learn-a-language/100-go.md
- src/data/roadmaps/blockchain/content/109-dapps/107-supporting-languages/102-go.md
- src/data/roadmaps/computer-science/content/101-pick-a-language/104-go.md
- src/data/roadmaps/devops/content/100-language/103-go.md
- src/data/roadmaps/software-architect/content/104-programming-languages/103-go.md
This adds the ["Learn Go" interactive course](https://boot.dev/learn/learn-golang) from Boot.dev to the various Go resource pages.
Like all courses on Boot.dev, all the content is free to read and watch without the need to sign up. Use the "browse the exercises" link to access the content without signing in.
There are over 150  individual lessons and challenges in this course!
> Add 'learn go' course from Boot.dev to Golang resources

- src/data/roadmaps/typescript/content/105-type-guards/101-instanceof-operator.md
Revised spelling of the keyword: 'instanceOf' -> 'instanceof'
> fix(typo): fix typo in 101-instanceof-operator.md

- src/data/roadmaps/javascript/content/102-javascript-datatypes/101-object/102-builtin-objects.md
roadmap-javascript-built-in-object-redundant-link-removed
fixes: #4758
> roadmap-javascript-built-in-object

- src/data/roadmaps/flutter/content/102-widgets/102-styled-widgets/100-material-widgets.md
'RaisedButton' is deprecated and shouldn't be used. It is replaced by ElevatedButton
> Flutter : update 100-material-widgets.md

- src/data/roadmaps/angular/content/101-rxjs-basics/102-marble-diagrams.md
Removes broken link: [Angular Marble Testing: A Brief Introduction](https://www.altamira.ai/blog/angular-marble-testing-a-brief-introduction/).
Fixes typo:
```diff
-[IUnderstanding Marble Diagrams for Reactive Streams](https://medium.com/@jshvarts/read-marble-diagrams-like-a-pro-3d72934d3ef5)
+[Understanding Marble Diagrams for Reactive Streams](https://medium.com/@jshvarts/read-marble-diagrams-like-a-pro-3d72934d3ef5)
```
> Angular RxJS Marble Diagrams broken link and typo

- src/data/roadmaps/frontend/content/114-css-frameworks/114-js-first/102-material-ui.md
- src/data/roadmaps/react/content/107-styling/104-material-ui.md
This is a continuation of https://github.com/kamranahmedse/developer-roadmap/pull/1093.
The introduction guide of @adriantwarog is awesome, but it covers Material UI v4. I have updated the YouTube link to a more recent introduction tutorial.
> Update Material UI guide to v5

- src/data/roadmaps/blockchain/content/100-blockchain-basics/102-why-blockchain-matters.md
- src/data/roadmaps/blockchain/content/100-blockchain-basics/index.md
- src/data/roadmaps/blockchain/content/103-smart-contracts/index.md
Fixes #4934 
Change link from [fromhttps://www.blockchain.education/blockchain101/blockchain](https://www.blockchain.education/blockchain101/blockchain) to [https://chain.link/education-hub/blockchain](https://chain.link/education-hub/blockchain)
> fix: introduction to blockchain links

- src/data/best-practices/frontend-performance/content/recommended-guides.md
This PR fixes the missing closing parenthesis in the Markdown link
> fix: markdown missing closing parenthesis for link

- src/data/best-practices/frontend-performance/content/recommended-guides.md
This PR replaces this broken link [https://www.loxodrome.io/post/web-worker-performance](https://www.loxodrome.io/post/web-worker-performance) with another resource with similar material [https://www.jameslmilner.com/posts/web-worker-performance](https://www.jameslmilner.com/posts/web-worker-performance)
> fix: replace broken link with a valid one in frontend performance

- src/data/roadmaps/typescript/content/101-typescript-types/108-enum.md
Fix a typo with a third person verb badly conjugated. I added an "s" at the end of "It allow".
> Fix typo: fix badly conjugated verb in typescript roadmap 108-enum.md 

- src/data/roadmaps/backend/content/103-learn-a-language/102-java.md
This PR fixes issue https://github.com/kamranahmedse/developer-roadmap/issues/5044 by changing the broken link under "Complete Java Course" to the right url from internet archive.
> fix: replace a broken link in the backend roadmap

- src/data/best-practices/frontend-performance/content/recommended-guides.md
This PR replace this [broken link](https://www.charistheo.io/blog/2021/09/dom-reflow-and-layout-thrashing/) with [https://www.harrytheo.com/blog/2021/09/dom-reflow-and-layout-thrashing/](https://www.harrytheo.com/blog/2021/09/dom-reflow-and-layout-thrashing/)
This is the same article; only Charistheo changed the name to Harrytheo
> fix: broken link in frontend performance recommended guides

- src/data/roadmaps/blockchain/content/101-blockchain-general-knowledge/106-cryptography.md
This PR removes the non-English Youtube video from the blockchain roadmap, cryptography.
> fix: remove the non-English youtube video from blockchain roadmap

- src/data/roadmaps/python/content/101-data-structures-and-algorithms/103-binary-search-trees.md
This PR fixes issue #5043 
change this [link](https://www.section.io/engineering-education/implementing-binary-search-tree-using-python/) to [archive version](https://web.archive.org/web/20230601181553/https://www.section.io/engineering-education/implementing-binary-search-tree-using-python/) as the site is unavailable and redirected to host provider.
also added another similar resource: [https://blog.boot.dev/computer-science/binary-search-tree-in-python/](https://blog.boot.dev/computer-science/binary-search-tree-in-python/)
> fix: broken link in python and also add another similar resource

- src/data/roadmaps/devops/content/100-language/102-javascript.md
- src/data/roadmaps/full-stack/content/113-nodejs.md
- src/data/roadmaps/nodejs/content/100-nodejs-introduction/100-what-is-nodejs.md
- src/data/roadmaps/nodejs/content/100-nodejs-introduction/101-why-nodejs.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/100-event-loop.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/101-event-emitter.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/104-callbacks.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/107-set-immediate.md
- src/data/roadmaps/nodejs/content/104-nodejs-async-programming/108-process-next-tick.md
- src/data/roadmaps/nodejs/content/105-nodejs-working-with-files/101-path-module.md
- src/data/roadmaps/nodejs/content/107-nodejs-apis/100-http-module.md
Hi, the Node.js official documentation was redirected from .dev to .org, resulting in numerous 404 errors. In this pull request, I have replaced all .dev links with their corresponding .org links.
> fix all nodejs doc redirection from .dev to .org

- src/data/roadmaps/typescript/content/101-typescript-types/115-type-assertions/101-as-type.md
The length of this is 18 but it says 20
'let someValue: any = "Hello, TypeScript!";
let strLength: number = (someValue as string).length;
console.log(strLength); // Outputs: 20'
> Fixing typo in typescript as type

- src/components/NavigationDropdown.tsx
Fixes #5354 
Now focus works as expected. Focus doesn't disappear, and goes to menu items if the menu is open. Otherwise it goes to next focusable element.
> fix: focus disappears in navigation

- src/data/roadmaps/system-design/content/116-performance-antipatterns/102-chatty-io.md
The content's title should be "Chatty I/O" instead of "Chat I/O"
> Fix typo for the content typo of 102-chatty-io.md

- src/data/roadmaps/javascript/content/100-javascript-introduction/101-history-of-javascript.md
The content of the linked article on The History of JavaScript is 90% word by word, except some voiceovers & jokes, the same as the video by Fireship on YouTube. I replaced the url to his article on dev.to which also contains the video if anyone prefers video to text. Needless to say, the video was released a few years prior to the currently linked article.
> History of Javascript - Replace plagiarized source with original

- src/data/roadmaps/aws/content/102-vpc/100-cidr-blocks.md
I don't remember seeing learning references on *roadmap* so far, but I believe it could help learners finding good, organized learning material more quickly.
> Add learning reference to CIDR

- src/data/roadmaps/typescript/content/100-typescript/102-install-configure/index.md
Hello !
As per my understading, the "--save-dev" option install the typescript module locally to the project.
The "tsc" command would work if we were using the "-g" option.
On my side, it's the "npx tsc" command that worked as mentionned into this documentation linked into the note : https://www.typescriptlang.org/download/
Hope I well understood...
> Suggested fix for the build command.

- src/data/roadmaps/python/content/102-python-advanced-topics/107-generator-expressions.md
1. There were some similar-sounding variants of Generator Expressions in the documentation:
* Generator comprehensions 
* Generator compressions
This PR changes all such references to [**Generator Expressions**](https://peps.python.org/pep-0289/).
2. Simplified some semi-superfluous language that previously read as "... a useful tool for creating **generators** that **generate** ..."
> [TYPO] Eliminate variants of Python Generator Expressions

- src/data/roadmaps/cpp/content/104-data-types/100-static-typing.md
In the current version, it was mentioned that assigning a double type variable's value to int type variable leads to a compile time error, which is false. This will lead to internal `type conversion` .
The flow of type conversion is as follows 
`char`->`int`->`float`->`double` .
Moving right to left lead to data loss while moving left to right have no data loss .
> Added detailed explanation and example of static typing in C++

- src/data/roadmaps/system-design/content/118-cloud-design-patterns/103-reliability-patterns/101-high-availability/deployment-stamps.md
The description for deployment-stamps in the high-availability section is actually the bulkhead pattern instead of the deployment-stamps pattern. 
The new changes above are from the deployment stamps pattern in the availability section.
> Correct content for deployment-stamps.md

- src/data/roadmaps/kubernetes/content/109-autoscaling/100-horizontal-pod-autoscaler.md
The Youtube video linked for Horizontal Autoscaling was not English which goes against our contribution guidelines.
Content before:
- [Horizontal Pod Autoscaling - Documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
- [Kubernetes Horizontal Pod Autoscaling - Kubernetes Tutorials](https://www.youtube.com/watch?v=hm3jnETOoFo)
Content after:
- [Horizontal Pod Autoscaling - Documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
Todo: Find/Create a good Horizontal Autoscaling video.
> None English video removed from Horizontal Autoscaling node

- src/data/best-practices/frontend-performance/content/compress-your-images.md
A previously useful linke (image.guide) is now linking to a casino website.
I have removed this link.
> Removed casino link from Image Optimization Content

- src/data/roadmaps/software-design-architecture/content/104-design-patterns/101-posa-patterns.md
The correct abbreviation for POSA is Pattern-Oriented Software Architecture not Patterns of Scalable and Adaptable Software Architecture.
Thanks
> Correct the POSA abbreviation

- src/data/roadmaps/react/content/110-frameworks/101-next-js.md
Updated to latest video of NextJS from freecodecamp in React roadmap.
> Update next.js youtube video link to latest

- src/data/roadmaps/prompt-engineering/content/100-basic-llm/100-what-are-llms.md
The definition of LLM was changed from **Language Learning Models** to **Large Language Models**.
> Correct LLM abbreviation

- src/data/roadmaps/angular/content/100-typescript-basics/101-why-use-typescript.md
I've updated the 101-why-use-typescript.md file for readability, making adjustments to the text structure. 
There was also an error in a sentence: "JavaScript include.Static typing"...
> Improve readability of 'Why us typescript' section

- src/data/roadmaps/rust/content/100-introduction/101-why-rust.md
Unnecessary tabs makes markdown render them as "code" instead of links
(Thank you so much for this website btw)
> Fixed link display of 101-why-rust.md

- src/data/roadmaps/docker/content/100-introduction/103-docker-and-oci.md
The OCI-specification has three core specifications while on the description written only two are mentioned. 
I added the *Distribution Specification (distribution-spec)*.
According to the website, the distro-spec defines a standardized API protocol for distributing container images and other content. It is primarly designed to ensure interoperability and consistency across different container registries and tools, regardless of their specific implementation.
I attach below links to the website of OCI and the github repo
- [On the github repo of the OCI](https://github.com/opencontainers/distribution-spec) 
- [Website of the OCI](https://opencontainers.org/about/overview/)
> Add third OCI specification

- src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md
A minor change to inform new users that this IDE is not free unlike other IDEs.
> Add license disclaimer to CLion IDE

- src/data/roadmaps/rust/content/100-introduction/102-memory-safety.md
Add missing content on zero cost abstractions in Rust 
This commit adds the missing section on zero cost abstractions in Rust that was planned for the blog post. It covers:
- Explanation of zero cost abstractions and how Rust achieves this: 
This helps complete the blog post and provides readers with a deeper understanding of this key aspect of Rust's design.
> expand rust zero cost abstractions content

- src/data/roadmaps/linux/content/114-shell-programming/103-literals.md
Fixed a typo in the definition of boolean literals in shell scripts that could be misleading
> Fix Typo in Shell Scripting Literal Description

- src/data/roadmaps/cpp/content/105-pointers-and-references/smart-pointers/100-weak-ptr.md
I think we should mention that there is actually another counter for `weak_ptr`s. Modified the document to make it a bit more accurate.
> [C++] Weak pointer reference count clarification 

- src/data/roadmaps/cpp/content/112-idioms/105-copy-swap.md
The original implementation attempted to use `swap` as a member function within the `String` class, intending to benefit from Argument-Dependent Lookup (ADL). However, this approach is incorrect for achieving the desired ADL benefits. This PR addresses the issue by transforming the `swap` function into a non-member friend function, ensuring proper participation in ADL. The modified code enhances the correctness and effectiveness of the `String` class. [Reference](https://stackoverflow.com/questions/3279543/what-is-the-copy-and-swap-idiom)
> [C++] Fixed swap ADL participation

- src/data/roadmaps/sql/content/107-sub-queries/index.md
The original text can mislead the reader. A column subquery shouldn't use the "=" operator, but the "in" operator.
> Updating description and query code

- src/data/roadmaps/blockchain/content/103-smart-contracts/index.md
This PR removes duplicate link in smart contract blockchain roadmap:
```
- [Smart Contracts Introduction](https://chain.link/education/smart-contracts)
- [What Is a Smart Contract?]   (https://chain.link/education/smart-contracts)
```
also I changed the title to match it with chainlink
> fix: remove duplicate link in smart-contract

- src/data/roadmaps/docker/docker.json
Fix : typo for route(controlName) in devops suggestion block  of docker roadmap
> Fix : typo in suggestion links of docker.json

- src/data/roadmaps/full-stack/content/106-external-packages.md
Fixed typo. There was two instances of "use" in the fullstack roadmap under "Checkpoint - External Packages".
> fix: typo in fullstack chekcpoint

- src/data/roadmaps/nodejs/content/107-nodejs-apis/101-express-js.md
This PR fixes the broken link of Tutorials Point page 
Fixes # #5259
> fix: broken link in "Express Full Guide"(#5259)

- src/data/roadmaps/sql/content/104-aggregate-queries/102-having.md
Description of having clause filter is incorrect. The current query filters for Customers with a total amount strictly greater than $3000.
> Update 102-having, matching query discrption to query. 

- src/data/roadmaps/rust/content/101-language-basics/101-ownership/index.md
- src/data/roadmaps/rust/rust.json
Fixing typo: `onwnership` to `ownership`.
Not sure if `rust.json` is generated or not but I spotted these two places so I gave them an update.
> fix typo in rust ownership section

- src/components/CommandMenu/CommandMenu.tsx
Fix a minor bug on ui. 
In the homepage, when user click search, search modal appeared but in the right conner has double scroll bar.
> fix: double scroll bar when searching

- src/data/roadmaps/backend/content/108-more-about-databases/103-n-plus-one-problem.md
**Problem:**
The links in the 103-n-plus-one-problem.md file are broken. Here is what is generated: [link1](https://roadmap.sh/%22https://planetscale.com/blog/what-is-n-1-query-problem-and-how-to-solve-it%22), [link2](https://roadmap.sh/%22https://dev.to/jackynote/solving-the-notorious-n1-problem-optimizing-database-queries-for-java-backend-developers-2o0p%22)
You can also see that the links aren't available on GitHub if you go [here](https://github.com/kamranahmedse/developer-roadmap/blob/38cb3d2df6804b25eedc956090406104d1f08f38/src/data/roadmaps/backend/content/108-more-about-databases/103-n-plus-one-problem.md)
**Solution:**
Looks like double quotes are excessive, last changes were made [here](https://github.com/kamranahmedse/developer-roadmap/pull/4952). This PR fixes it. …
> Fix links in 103-n-plus-one-problem.md

- src/data/roadmaps/rust/content/101-language-basics/102-constructs/102-traits.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/106-vector.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/107-string.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/108-hashmap.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/109-hashset.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/110-linked-list.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/111-binary-heap.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/112-stack.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/113-queue.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/114-btree-map.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/115-btree-set.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/116-rc.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/117-arc.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/118-mutex.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/119-rwlock.md
- src/data/roadmaps/rust/content/101-language-basics/103-data-structures/120-channels.md
Several data structure pages were missing content, I have added the official documentation for each structure.
> add documentation links to data-structure pages

- src/data/roadmaps/devops/content/118-artifcats/index.md
Just a small spelling mistake fix on the DevOps Roadmap:
Artifcats ->Artifacts
> Update artifacts spelling mistake

- src/data/roadmaps/angular/content/100-typescript-basics/101-why-use-typescript.md
In the doc, there was a typo, where, a 'C' was missing in the word 'compile'.
> fixing typo Angular 101-why-use-typescript.md

- src/components/Roadmaps/RoadmapsPage.tsx
- src/data/roadmaps/flutter/flutter.md
- src/data/roadmaps/react-native/react-native.md
- Should be able to see `Flutter` and `React Native` under **skill-based roadmaps**
- Updated Flutter and ReactNative from role to skill based skills in RoadmapsPage.tsx, flutter.md and react-native.md files
- If you go to `home page` of roadmap and `/roadmaps` -> `All Roadmaps`
- You could see both of them under `SKILL BASED ROADMAPS`
**Home screen**
**All roadmaps screen**
> Move Flutter and React Native to Skill-based roadmap

- src/data/best-practices/frontend-performance/content/avoid-404-files.md
- src/data/best-practices/frontend-performance/content/avoid-base64-images.md
- src/data/best-practices/frontend-performance/content/keep-ttfb-less-1-3s.md
- src/data/best-practices/frontend-performance/content/use-http-cache-headers.md
- src/data/best-practices/frontend-performance/content/use-non-blocking-javascript.md
All links from varvy.com are dead and redirect to a gambling website.
Where removing the link left no content, I have replaced it with mdn docs on the topic.
> remove all varvy links

- src/data/roadmaps/cpp/content/109-language-concepts/101-type-casting/101-const-cast.md
Additional printing information is used to tell the user that after conversion and modification through const_cast, although the memory address has not changed and the non_const_value_ptr has changed, the original_value has not changed.
output
```
Original value: 10
Modified value: 42, original_value: 10
```
> const_cast not modify original_value

- src/data/roadmaps/datastructures-and-algorithms/content/103-basic-data-structures/100-array.md
All the youtube links had `!` before the URLs
> Remove '!' from youtube links

- src/data/roadmaps/react-native/content/102-environment-setup/100-expo/index.md
- src/data/roadmaps/react-native/content/102-environment-setup/index.md
The Expo CLI Quickstart links to the React Native CLI quickstart. This PR fixes that.
> Correct link for Expo CLI Quickstart

- src/data/best-practices/frontend-performance/content/minify-css.md
cssnano website now has been changed: https://cssnano.github.io/cssnano/. The before link: https://cssnano.co/ is Invalid
> docs(frontend-performance): fix 'cssnano' website link

- src/data/roadmaps/docker/content/100-introduction/103-docker-and-oci.md
Found a duplicate 'defines' for the Distribution Specification (distribution-spec) section so I've just removed that now 👍🏽
> Fixed typo in Docker roadmap

- src/components/Navigation/Navigation.astro
Previously we highlighted "teams" on desktop view only and missed highlighting it on mobile view.
> Highlight teams on mobile view

- readme.md
Added the recently created iOS roadmap and backend questions that were missing in the readme.md.
> Add links to readme.md (ios-roadmap, backend-questions)

- src/data/roadmaps/java/content/100-java-fundamentals/107-loops.md
Changed the spelling from "Synatx" to "Syntax" to improve readability and maintain consistency across the topic.
> fix: correct spelling from "Synatx" to "Syntax"

- src/data/roadmaps/docker/content/108-running-containers/index.md
Replaced instances of `docker ps` with `docker container ls`
Resolves #5783
> Fix: Standardize using "docker container ls" command when referencing listing containers

- src/data/roadmaps/react/content/102-components/100-class-components.md
- src/data/roadmaps/react/content/102-components/101-functional-components.md
- src/data/roadmaps/react/content/102-components/index.md
We are missing video resources for some topics, which are sometimes more helpful. I've added some for the Components topic.
> Added Video Resources for Component's in React Roadmap

- src/data/roadmaps/software-design-architecture/content/102-object-oriented-programming/index.md
One of the links for the introduction to object oriented programming no longer leads to the site it used to but to an unrelated one, I found a link I think would be suitable for this.
> Update resource link for OOP section

- src/data/roadmaps/computer-science/content/119-security/101-hashing-encryption-encoding.md
I found that 'Encryption' was misspelled as 'Ecncryption' and corrected it.👍
> Fix typo 101-hashing-encryption-encoding.md

- src/data/question-groups/backend/backend.md
Answer for _"What is containerization, and how does it benefit backend development?"_ points to `statelessness-http.md`. On the [page](https://roadmap.sh/questions/backend) it looks like this:
Use existing `containerization.md` instead of `statelessness-http.md`
> Fix answer for backend question about containerization

- src/data/question-groups/backend/backend.md
Answer for _"Describe the concept of eventual consistency and its implications in backend systems"_ points to `api-dependencies.md`. On the [page](https://roadmap.sh/questions/backend) it looks like this:
Use existing `eventual-consistency.md` instead of `api-dependencies.md`
> Fix answer for backend question about eventual consistency

- src/pages/about.astro
Added a missing whitespace to the About page
> Add missing space to about page

- src/data/roadmaps/ios/ios.json
The iOS roadmap link for React Native was updated to the correct URL. This change ensures that users are directed to the appropriate resource for learning React Native on the iOS roadmap.
Authored-by: kai <trongtoan1609ht@gmail.com>
> feat: Update iOS roadmap link to React Native

- src/data/roadmaps/cpp/content/100-introduction/100-what-is-cpp.md
- src/data/roadmaps/cpp/content/100-introduction/index.md
- src/data/roadmaps/cpp/content/101-setting-up/101-code-editors.md
- src/data/roadmaps/cpp/content/102-basic-operations/102-loops.md
- src/data/roadmaps/cpp/content/102-basic-operations/103-bitwise.md
- src/data/roadmaps/cpp/content/103-functions/100-lambda.md
- src/data/roadmaps/cpp/content/103-functions/index.md
- src/data/roadmaps/cpp/content/104-data-types/100-static-typing.md
- src/data/roadmaps/cpp/content/105-pointers-and-references/smart-pointers/100-weak-ptr.md
- src/data/roadmaps/cpp/content/109-language-concepts/101-type-casting/index.md
- src/data/roadmaps/cpp/content/libraries/102-poco.md
All additional links at the end of the articles in C++ roadmap have been wrapped with 'Learn more from the following resources:' line as in contribution docs stated
> C++ roadmap additional links wrapped as in contribution doc stated

- src/data/roadmaps/computer-science/content/101-pick-a-language/100-c-plus-plus.md
- src/data/roadmaps/computer-science/content/101-pick-a-language/105-c-sharp.md
- src/data/roadmaps/computer-science/content/102-data-structures/100-array.md
- src/data/roadmaps/computer-science/content/102-data-structures/index.md
I made some changes to the Computer Science Roadmap. In the C# section, I edited the feed link because it was redirecting to the C feed. Additionally, I added some useful resources to the data structures and array sections.
> Fix and add links in Computer Science roadmap

- src/data/roadmaps/angular/content/101-rxjs-basics/104-operators/103-combination.md
- Fixing broken rxjs link roadmap Angular.
> Fixing broken rxjs link

- src/data/roadmaps/java/content/101-java-advanced-topics/106-how-jvm-works.md
removed duplicate link
added JVM languages and GraalVM as a popular alternative
> Java roadmap: jvm clarifications

- src/data/roadmaps/react/content/103-rendering/105-high-order-components.md
This commit introduces new educational content to the React-Roadmap project. Specifically, it includes the addition of three instructional videos that focus on the concept of Higher-Order Components (HOCs) in React. These videos are intended to enhance the roadmap's value by providing users with visual and practical examples of HOCs.
> Added 3 videos to React-Roadmap, For HOC

- src/data/roadmaps/devops/devops-beginner.json
Fix typo in final paragraph of beginner roadmap for devops.
> Typo - DevOps Roadmap Beginner: typo in final paragraph

- src/data/roadmaps/product-manager/content/ab-testing@Ws7IFrHQNoBjLE2Td2xIZ.md
- src/data/roadmaps/product-manager/content/advanced-analysis@9y_I41kJhkmyBJjiTw8Xd.md
- src/data/roadmaps/product-manager/content/amplitude@Z5oorppEJ0ydvwMXSlk1J.md
- src/data/roadmaps/product-manager/content/case-studies@JhhjMPTNb646aQKlS_cji.md
- src/data/roadmaps/product-manager/content/decline@yOve7g_05UMpXHcGpdZcW.md
- src/data/roadmaps/product-manager/content/discord@e6gO1twjter9xWm14g9S9.md
- src/data/roadmaps/product-manager/content/heap@xas-t2sAKmJNfb0-Zcpwy.md
- src/data/roadmaps/product-manager/content/job-stories@B9fgJmzVViaq7dvSuEglb.md
- src/data/roadmaps/product-manager/content/kanban-basics@kJ2HQFEsnc5yISU8d9Lla.md
- src/data/roadmaps/product-manager/content/linear@PIIGfDN6t8H6tXZuKuE04.md
- src/data/roadmaps/product-manager/content/positioning@YPqdrZguH0ArEFSe-VwKS.md
- src/data/roadmaps/product-manager/content/predictive-analytics@YsDt5I0prvYeaFfn4_lpx.md
- src/data/roadmaps/product-manager/content/predictive-analytics@h5N51_YgjaTHhPUHxkqQR.md
- src/data/roadmaps/product-manager/content/risk-register@WBnLicFo9p2zm57pyXciI.md
- src/data/roadmaps/product-manager/content/roadmapping-tools@XG-QBb--HXL-1r-jInYDN.md
- src/data/roadmaps/product-manager/content/slack@UdOJDzkDP_R3E5f_IltYh.md
- src/data/roadmaps/product-manager/content/trello@SD98_s1ET_j2eIIKmcKRc.md
Having "for product managers" in the title was causing the youtube and google search buttons to repeat "for product managers in the search" such as: `slack - a communication tool for product managers for product manager`
> Removed 'for product managers' from topic titles

- src/data/roadmaps/game-developer/content/104-programming-languages/103-rust.md
There was a markdown typo which is:
[Learn Rust full tutorial](https://youtu.be/BpPEoZW5IiY?si=lyBbBPLXQ0HWdJNr
...
> Fixed markdown typo

- src/data/roadmaps/angular/content/101-rxjs-basics/104-operators/102-transformation.md
- remove deprecated flatMap operator (Renamed to mergeMap. Will be removed in v8)
- add exhaustMap
- add video for Higher-Order RxJs Mapping Operators
- sort operators by complexity
- change the type of some resources to the **official** category
> feat(roadmap/angular): update RxJS transformation section

- src/data/roadmaps/golang/content/101-go-advanced/110-scheduler.md
"processors" instead of "prcoessors"
> fix typo golang/advanced

- src/data/roadmaps/spring-boot/content/109-spring-mvc/103-components.md
Update of reference links to articles. One of them was no longer working (http://makble.com/spring-mvc-components)
> Update of dead links

- src/components/CommandMenu/CommandMenu.tsx
fixes #6193 
the problem was that multiple groups had same .md filename resulting in same id and hence key in fragment. Hence, I made it a composite key.
> Fix persistant search result

- src/data/roadmaps/react/content/usereducer@v48Mv0wQqjXbvy8x6gDjQ.md
- src/data/roadmaps/react/content/usreducer@v48Mv0wQqjXbvy8x6gDjQ.md
- src/data/roadmaps/react/react.json
- ### File name from `usreducer@v48Mv0wQqjXbvy8x6gDjQ` to `usereducer@v48Mv0wQqjXbvy8x6gDjQ`
- ### Title inside it from `usReducer` to `useReducer`
- ### Inside `react.json`: "label": `usReducer` to `useReducer`
> useReducer typo error fixed in the new react roadmap

- src/data/roadmaps/devops/devops.json
In the version of Roadmap as of writing, the DevOps roadmap has the "Personal Recommendation" heading as the stroke line's blue (\#2b78e4), while on the legend's descriptor says "Pick this or Purple". This PR takes the purple in the Frontend and Backend roadmaps (\#874efe) and replaces all the blue legends in the DevOps roadmap with that colour.
Note that the changes haven't been tested yet, I don't have access to the Roadmap generator.
> Update DevOps recommendation colour to purple

- src/data/roadmaps/javascript/content/string@1RcwBHU3jzx0YxxUGZic4.md
The content in String type on JavaScript roadmap isn't correct. It shows Primitive type instead. This is the new content.
> fix: Wrong JavaScript type content

- src/data/roadmaps/ios/content/swift-basics@fboebSmquyJyozsMRJDtK.md
I've added a quick link to the standard Swift Tour. It'll be a perfect pointer to place under this section.
Do merge if you found this useful and relevant. 
Thanks and you're welcome!
> Add content under Swift Basics section on the iOS roadmap

- src/components/DownloadRoadmapButton.tsx
- src/components/EditorRoadmap/EditorRoadmap.tsx
- src/components/FeaturedItems/MarkFavorite.tsx
- src/components/FrameRenderer/FrameRenderer.astro
- src/components/Projects/EmptyProjects.tsx
- src/components/ResourceProgressStats.astro
- src/components/RoadmapHeader.astro
- src/components/RoadmapHint.astro
- src/components/RoadmapTitleQuestion.tsx
- src/components/ShareRoadmapButton.tsx
- src/components/TabLink.tsx
- src/data/roadmaps/system-design/system-design.md
- src/lib/resource-progress.ts
- src/pages/[roadmapId]/index.astro
- src/pages/[roadmapId]/projects.astro
- src/styles/global.css
**Before**
**After**
---
**Before**
**After**
> feat: redesign roadmap page header and add upcoming projects functionality

- src/data/roadmaps/angular/content/language-service@ql7SyxrRmjpiXJ9hQeWPq.md
The installation prompt does occur if the project was created with the Angular CLI, which the vast majority of projects should have been created with.
> docs(angular): add language service content

- src/data/guides/how-to-become-devops-engineer.md
- src/data/guides/journey-to-http2.md
- src/pages/authors/[authorId].astro
Fixed a couple of small http vs https issues that @Edlan01 raised & corrected the incorrect canonical link issue for author pages (see issue below)
The link that users navigate too via a guide is correct at `/authors/*` but the canonical link is incorrect at `/author/*`
> Minor touch ups to guide content and fixed canonical authors link issue

- src/data/guides/frontend-languages.md
As the title says, center the logo.
> Centered the html logo on frontend language guide

- src/data/roadmaps/software-architect/software-architect.json
Hi :wave: 
Thank you very much for this great content.
The goal of this PR is just to fix a small typo, replacing 'eachother' by 'each other'.
https://www.grammarbook.com/blog/definitions/eachother-or-each-other/
> Fix typo in software architecture definition

- src/data/best-practices/code-review/content/change-functioning.md
I found a typo in `change-functioning.md` for the code-review roadmap.
> docs(code-review): fix typo "Veryfing" to "Verifying"

- src/data/roadmaps/api-design/content/mocking-apis@bEVCT5QGY3uw0kIfAELKh.md
Added missing `@` to correct the formatting of article links.
> Fix: Add missing @ in article link

- src/data/roadmaps/nodejs/content/jest@5xrbKv2stKPJRv7Vzf9nM.md
Corrects the typo where 'article' was mistakenly used instead of 'official' when referencing the Jest website.
> Fix: Replace "article" with "official" for Jest Website

- src/data/roadmaps/nodejs/content/mongoose@NDf-o-WECK02mVnZ8IFxy.md
Corrects the typo where 'article' was mistakenly used instead of 'official'.
> Fix: Replace "article" with "official" for Mongoose Website

- src/data/roadmaps/nodejs/content/drizzle@JXQF9H4_N0rM7ZDKcCZNn.md
Corrects the typo where "n" was missing in "opensource".
> Fix: Change "opesource" to "opensource"

- src/data/roadmaps/python/content/exceptions@fNTb9y3zs1HPYclAmu_Wv.md
- src/data/roadmaps/python/content/type-casting@R9DQNc0AyAQ2HLpP4HOk6.md
Roadmap edited: Python
Topics edited: Typecasting, Exceptions
Path used: .../developer-roadmap/src/data/roadmaps/python/content
Description:
I moved misplaced articles that had to do with exceptions from the Typecasting topic to the Exceptions topic.
> Moved misplaced articles from Typecasting to Exceptions

- src/components/UserPublicProfile/UserPublicProfileHeader.tsx
This pull request addresses issue #6503, where the profile avatar in the wide card and profile activity page was incorrectly scaled, resulting in a compressed appearance instead of proper zooming.
Problem Details:
Issue URL: https://roadmap.sh/card/wide/65545e1968ca60261330fe9a?variant=dark
Affected Browsers: Chrome (Brave browser)
Bug Description: The profile avatar in the wide card was being compressed rather than zooming in as expected, leading to a distorted visual presentation.
Fix Implemented:
Adjusted the CSS properties for the profile avatar within the wide card and profile activity page to ensure it scales correctly, matching the expected behavior seen in the standard profile picture view.
Testing:
Verified the fix on Chrome and Brave browsers to ensure consistent avatar scaling …
> Fix Incorrect Scaling of Profile Avatar in Wide Card and Profile Activity Page (#6503)

- src/data/roadmaps/aws/content/101-ec2/102-storage-volume.md
the link to Elastic Block Store documentation has a hard coded language that causes it to open to the Portuguese version
removing this will default to the users preferred language
> remove link loc from 102-storage-volume.md

- src/data/roadmaps/mlops/mlops.json
bug-fix: according to the following issue -> Incorrect DevOps navigation in MLOps roadmap #6807
- changed link : https://github.com/utilForever -> https://roadmap.sh/devops in 
[mlops.json](https://github.com/kamranahmedse/developer-roadmap/blob/master/public/roadmap-content/mlops.json)
> bug-fix: according to the following issue -> Incorrect DevOps navigation

- src/data/roadmaps/angular/angular.json
- src/data/roadmaps/angular/content/template-ref-vars@Wc2ybRw43uamEtno0FpDv.md
Unneeded duplication of `Template Ref Vars` file.  Removed the one without content.
> fix(angular): remove duplicate template ref vars files

- public/roadmap-content/backend.json
Removes the title “Official JavaScript Documentation” from javascript.com. It is not official documentation (heck it’s not even _documentation_); it’s basically an advertisement for a for-profit company who is uninvolved with TC39 and just ponied up for the domain\*. Not to say that it doesn’t have good resources; I think it’s helpful. But it’s not “official” by any means and it’s not correct to call it as such.
\* I should know—I was working at the company that bought it, when they bought it. It was always intended to be a marketing tool. It was bought while I worked at CodeSchool, which then got bought by PluralSight, and it just got shuffled over during the acquisition.
> Remove “official” from JavaScript.com

- src/data/roadmaps/angular/content/transformation@kdMJHljMzGA3oRlh8Zvos.md
The links don't render correctly in the right place with the current markdown.  I changed to use the standard format.
> docs(angular): update transformation content

- src/data/roadmaps/kubernetes/content/103-running-applications/102-deployments.md
For the Kubernetes roadmap, the "Deployments" node under "Running Applications" was missing content. This PR adds a short snippet.
> docs(kubernetes): add content for k8s deployments

- src/data/roadmaps/backend/content/orms@Z7jp_Juj5PffSxV7UZcBb.md
this PR addresses this issue https://github.com/kamranahmedse/developer-roadmap/issues/6979, in where we have 2 stackoverflow links that are the same, this removes the question link
> Remove redundant link in backend roadmap

- src/data/roadmaps/postgresql-dba/content/introduction@lDIy56RyC1XM7IfORsSLD.md
I brief historical view of Postgresql that might introduce new developers to Berkeley Labs to look up the projects from there.
> Add postgresql history page from the official docs

- src/data/roadmaps/ux-design/content/nudge-theory@6ffY5wO-XhkiDJJ5YcI0x.md
The video "Nudge Theory Explained with Examples" isn't available anymore, so I removed it from the topic.
> Remove unavailable nudge theory video

- src/data/roadmaps/postgresql-dba/content/mvcc@-_ADJsTVGAgXq7_-8bdIO.md
addresses this issue in the image below in where we don't have a title for the wiki link
> Fix missing article title in PostgreSQL dba roadmap

- src/data/roadmaps/rust/content/101-language-basics/100-syntax/103-functions.md
This PR fixes a typo on the functions and method page of Rust Roadmap, causing the title getting rendered as body when it should be a header
> docs(rust): fix typo on functions content page

- src/data/roadmaps/postgresql-dba/content/set-operations@kOwhnSZBwIhIbIsoAXQ50.md
In the Set Operations in PostgreSQL Step, 
There are three set operations: 
1. UNION, 
2. INTERSECT, and 
3. EXCEPT. 
The EXCEPT operation's article link is missing at the bottom. This is a PR for adding the article link.
Please take a look at the image below.
> Added the missed article link for the PostgreSQL DBA Roadmap.

- src/data/roadmaps/datastructures-and-algorithms/content/100-language/107-ruby.md
Corrects the typo where 'article' was mistakenly used instead of 'official'.
> Fix: Replace "article" with "official" for Ruby Website

- src/data/roadmaps/devops/content/networking-tools@OaqKLZe-XnngcDhDzCtRt.md
You can't ping a URL -- that will just confuse a learner
```bash
$ ping https://github.com
ping: cannot resolve https://github.com: Unknown host
```
> devops networking fix ping typo

- src/data/roadmaps/vue/content/v-model@cxu2Wbt306SxM4JKQQqnL.md
The <input> <textarea> and <select> elements are attempted to be rendered by the browser so they aren't visible as text
> Add formatting so the HTML elements don't get rendered

- src/data/roadmaps/rust/content/101-language-basics/100-syntax/102-control-flow.md
I have found that `loop` and `if let` are not present with other structures in **Control Flow Constructs**, so I added them and a link to [**Concise Control Flow with `if let`**](https://rust-book.cs.brown.edu/ch06-03-if-let.html) in Rust Book
> Add `loop` and `if let` structures to "Control Flow Constructs" in Rust roadmap.

- src/data/roadmaps/flutter/content/100-dart-basics/index.md
Invalid URL: https://flutterbyexample.com/lesson/about-dart
PS: not sure what happened to the initial website but looks like it was transformed into something else.
> Delete invalid URL

- src/data/guides/backend-frameworks.md
- src/data/roadmaps/backend/faqs.astro
- src/pages/backend/frameworks.astro
Guide has been completed and FAQs updated to reference the guide.
@Edlan01 same again on this one, the HTML table for the frameworks didn't work so I screenshot, compressed and added, let me know if there's any issues with that.
> Add backend frameworks guide

- src/data/roadmaps/cyber-security/content/ssl-and-tls-basics@dJ0NUsODFhk52W2zZxoPh.md
- src/data/roadmaps/cyber-security/content/ssl-vs-tls@6ILPXeUDDmmYRiA_gNTSr.md
The "SSL vs TLS" and "SSL and TLS Basics" topics in the Cybersecurity roadmap both had content that was specific to SSO, not SSL. Probably a mistake because they differ only by one letter.
From #7136
> Update SSL/TLS pages with correct topic content

- src/data/roadmaps/devops/content/operating-system@qe84v529VbCyydl0BKFk2.md
Roadmap URL
[Devops Roadmap](https://roadmap.sh/devops)
Replace the https://www.javatpoint.com/os-tutorial to this https://www.javatpoint.com/operating-system.
Should Close the issue #7305.
> Replace a Broken Link in Devops Roadmap

- src/data/roadmaps/react/content/component-lifecycle@8OBlgDRUg-CTgDXY-QHyO.md
The previous references for component lifecycles were outdated as they focused on the class component paradigm. This PR updates the documentation to include a more relevant reference that explains the lifecycle methods in the context of functional components, aligning with modern React practices. https://github.com/kamranahmedse/developer-roadmap/issues/6771
> add new references to learn component lifecycles

- src/data/roadmaps/software-design-architecture/content/100-clean-code-principles/113-command-query-separation.md
The previous article referred to a broader, architectural pattern of CQRS, which are not the same
> Corrects the CQS article

- src/data/roadmaps/rust/content/104-concurrency-parallelism/101-atomic-operations.md
- src/data/roadmaps/rust/content/104-concurrency-parallelism/102-threads.md
Added links to the [Rust Atomics and Locks by Mara Bos](https://marabos.nl/atomics/) freely online available book. It is a fantastic comprehensible resource about low-level concurrency, written by a core Rust contributor.
Not sure what `@type@` of the link it is - `opensource`, `article`, `course`?
> Add links to the free "Rust Atomics and Locks" ebook

- public/roadmap-content/full-stack.json
- src/data/best-practices/api-security/api-security.json
- src/data/best-practices/api-security/content/jwt-algorithm.md
- src/data/best-practices/api-security/content/jwt-payload.md
- src/data/best-practices/api-security/content/payload-size.md
- src/data/guides/backend-project-ideas.md
- src/data/projects/expense-tracker-api.md
- src/data/projects/fitness-workout-tracker.md
- src/data/projects/image-processing-service.md
- src/data/projects/todo-list-api.md
- src/data/roadmaps/full-stack/content/jwt-auth@vHojhJYjiN0IwruEqi1Dv.md
Since the elongated term for the abbreviation JWT is Json Web Token, adding another word 'token' after it is redundant. This PR fixes this issue in the concerned places.
> Remove superfluous 'token' after writing  JWT.

- src/data/projects/age-calculator.md
- src/data/projects/custom-dropdown.md
- src/data/projects/flash-cards.md
1. Age Calculator
2. Flash Cards
> feat: add frontend projects

- src/data/roadmaps/git-github/content/rebase@99FVJ3Zs8n6lr8L95mG6g.md
A resource URL on the [git-github roadmap ](https://roadmap.sh/git-github) has changed.
> Update broken link

- src/data/roadmaps/typescript/content/constructor-overloading@oxzcYXxy2I7GI7nbvFYVa.md
Very minor typo in the Typescript "Constructor Overloading" section. For the paragraph beginning in "Note that, similar to function overloading . . ."
> Fixed typo, was consructor now constructor.

- src/data/roadmaps/aws/content/101-ec2/index.md
- src/data/roadmaps/aws/content/102-vpc/index.md
First commit is adding a link to aws official video that give us a resume of what is ec2 and his vantages. Its a short video so i think its good to people to get a _fast_ knowledge of uses of ec2 and _why_ use this.
Second commit is adding a link to freecodecamp video that covers practically everything of vpc service.
> Adding 2 videos links to Aws Roadmap - EC2 and VPC topics

- src/data/roadmaps/typescript/content/ambient-modules@k_5y77k8ZZ9_O2WpWXWTY.md
The old link is improperly formatted--as such, it simply redirects the user to https://www.typescriptlang.org/docs/handbook/modules/introduction.html, rather than the more specific https://www.typescriptlang.org/docs/handbook/modules/reference.html#ambient-modules
OLD LINK (for ease of reference):
https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules
> Fix link to point to "Ambient Modules" anchor in TS Modules Reference

- src/data/roadmaps/linux/content/104-text-processing/109-pipe.md
Updated the grep command in the example to match files specifically ending in ".txt". The original command `ls | grep .txt` would match any filename containing ".txt" anywhere in its name, which could lead to unintended matches. The revised command uses `grep '\.txt$'` to filter for files ending with ".txt" precisely.
> Fix: Improve grep command to filter files ending with .txt

- src/components/Toast.tsx
I checked if the interface is used anywhere else in the codebase.
I removed it and checked that the website is running as before.
Issue: #7697
> Update Toast.tsx to remove unsued interface

- src/data/roadmaps/git-github/content/gitignore@oz2oRAhaEQb0Fm3aRJQG8.md
Hey, I have fixed the gitignore documentation link error for the gitignore.
updated the line: [@official@gitignore Documentation](https://git-scm.com/docs/gitignore)
Thanks.
> fixes the gitignore link error in git-github roadmap

- src/data/roadmaps/react/react.json
Simple fix to change blue tick to purple tick to ensure consistency with other roadmaps. The choice of hexcode is provide by @fellalli in this [issue](https://github.com/kamranahmedse/developer-roadmap/issues/7688).
> fix: Update color ticks hexcode from #2d72d2 to #874efe

- src/data/roadmaps/golang/content/101-go-advanced/107-buffer.md
- src/data/roadmaps/golang/content/109-go-microservices/105-protocol-buffers.md
In Step by step guide to becoming a Go developer in 2024,
I noticed that there was a protobuf video in buffer section, so i changed it 👍
> Move Protobuf Video from Buffers Section to Protocol Buffers Section

- src/data/projects/expense-tracker.md
If we are referencing by id and not index then --id 1 would remove the first element making the summary 10 and not 20
Solution: delete the second element instead to make the summary add up correctly.
> fix(expense tracker): a small logical error in desctiption

- src/data/roadmaps/react/react.json
This pull request fixes the legend section color coding to match that of the roadmap sections of the website (blue changed to purple).
Link to the issue: https://github.com/kamranahmedse/developer-roadmap/issues/7723
> Fix color mismatch between legend and roadmap sections

- public/roadmap-content/backend.json
- src/data/roadmaps/aspnet-core/content/100-basics-of-csharp/100-csharp.md
- src/data/roadmaps/aspnet-core/content/100-basics-of-csharp/index.md
- src/data/roadmaps/backend/content/c@rImbMHLLfJwjf3l25vBkc.md
- src/data/roadmaps/datastructures-and-algorithms/content/100-language/103-csharp.md
**Fix incorrect link for C# in  in a few roadmaps**
---
This PR addresses [#7756](https://github.com/dudi-w/developer-roadmap/issues/7756), which highlights an incorrect link in the **ASP.NET Core roadmap**.  
When clicking on **"Explore top posts about C#"**, the link currently points to:  
`https://app.daily.dev/tags/c#?ref=roadmapsh`, which incorrectly redirects to learning resources about the **C programming language** instead of **C#**.
The link has been updated to the correct URL:  
`https://app.daily.dev/tags/csharp?ref=roadmapsh`  
- Updated the `Explore top posts about C#` link in the roadmap to point to the correct URL.  
- Verified that the updated link correctly redirects to the **csharp tag** page on daily.dev.
Please review and let me know if further adjustments are needed. …
> Update C# link to correct URL

- src/data/roadmaps/aspnet-core/content/107-databases/102-relational/101-postgresql.md
I contribute  fix  simple issue is developer-roadmap project by suggesting an improvement to the ASP.NET Core roadmap to change url, 
under Databases → Relational → PostgreSQL,
I updating the PostgreSQL link to point directly to https://www.guru99.com/introduction-postgresql.html.
> [fix]:change update url in In Databases -> Relational -> PostgreSQL

- src/data/roadmaps/java/content/107-testing-java-apps/106-rest-assured.md
I’ve added a beginner-friendly article, [A Guide to REST-assured](https://www.baeldung.com), from Baeldung to the REST Assured section. If there’s anything that doesn’t meet the format, please feel free to comment. Thanks😊.
Fixed #7736
> Add beginner-friendly article to REST Assured Section in Java Roadmap

- src/data/roadmaps/linux/content/106-process-management/104-proc-priorities.md
Old: renice +5
New: renice -5
From my research, after reading the topic in the Linux roadmap, it didnt make sense that increasing the priority of a process was made by +5, the topic said that a negative number makes the priority higher, so do many articles on the internet.
> Fixes typo in 104-proc-priorities.md

- src/data/roadmaps/server-side-game-developer/server-side-game-developer.json
This PR fixes the link on [Server Side Game Developer](https://roadmap.sh/server-side-game-developer) for [Client-side game Development](https://roadmap.sh/game-developer), which is at the end of roadmap, under the section that points to next relevant roadmaps.
Previously, it was pointing to [Backend Developer](https://roadmap.sh/backend).
> [Server Side Game Developer] Fix: Update correct link for client side game development

- readme.md
Clicking used to redirect to [the logo](https://github.com/kamranahmedse/developer-roadmap/blob/master/public/images/brand.png), now to [roadmap.sh](https://roadmap.sh/).
> Logo redirects to roadmap.sh in readme.md

- src/pages/get-started.astro
On the page `/get-started`.
| Before  | After |
| ------------- | ------------- |
| <img width="491" alt="image" src="https://github.com/user-attachments/assets/636c67c7-29fa-4e86-8286-3a57ce5ec0dc" /> | <img width="491" alt="image" src="https://github.com/user-attachments/assets/10e945f8-0458-4534-922b-264444bdd122" /> |
> Fix: typo in getting started page Engineering Manager card title

- src/data/roadmaps/react-native/content/115-using-native-modules/index.md
`https://reactnative.dev/docs/native-modules-intro` doesn't exist anymore, so this PR updates the link to the new link.
> Fix: update broken link

- src/data/roadmaps/python/content/sphinx@maYNuTKYyZndxk1z29-UY.md
What is the URL where the issue is happening
https://roadmap.sh/python
Fixed Typo in roadmaps/python/content/sphinx 
-line 7
Changed "Shpinx" to "Sphinx"
> Python roadmap: Fixed Typo in Sphinx

- src/data/roadmaps/react-native/content/115-using-native-modules/100-for-ios.md
- src/data/roadmaps/react-native/content/115-using-native-modules/101-for-android.md
In the React Native roadmap, the penultimate section, "Using Native Modules", contained two deprecated links that redirected to "Page not found" on the site. I updated the links to their correct destinations. Closes #7956
> Update deprecated link in React Native roadmap

- src/data/roadmaps/computer-science/content/asymptotic-notation@UpBrpmrUwYUB9eesNxCq5.md
- src/data/roadmaps/computer-science/content/big-o@c-NrTtJuNihbHzyPEOKTW.md
- src/data/roadmaps/computer-science/content/big-omega@X33735aeAVSlJ6yv9GS-h.md
- src/data/roadmaps/computer-science/content/big-theta@ThLpVZQIJ4diY5m0dik8m.md
It seems that the current descriptions of the Big O and Big Omega notations reflect a common misconception that they correspond to the worst and best cases of an algorithm. Based on what I've learned from my research, every algorithm can have its best case, worst case, and average case runtimes, and each of these runtimes can be represented by a function. The growth rate of such a function can be constrained by upper and lower bounds, and these bounds are what the Big O and Big Omega notations represent.
This PR rewrites the descriptions of the different asymptotic notations based on the above understanding, while adding a new article that provides a thorough explanation of these concepts. Please feel free to share your views on the changes.
> Fix incorrect descriptions of asymptotic notations

- src/data/roadmaps/golang/content/101-go-advanced/100-go-modules.md
There is an unavailable resource in [Golang roadmap](https://roadmap.sh/golang), mentioned in #8049 .
Closes #8049 by removing the unavailable resource from the markdown file.
I decided against replacing with another resource because there were plenty other resources already provided for this topic (Go module).
> Remove unavailable video resource (Closes #8049)

- src/data/roadmaps/frontend/content/content-security-policy@rmcm0CZbtNVC9LZ14-H6h.md
Hi.
Deleted the same redirect link which closes #8037.
Seems `web.dev` is the newer link for `developers.google.com/web` .
> fix: dedupe the same redirect link(#8037)

- src/data/projects/weather-api-wrapper-service.md
In the current version, when clicking on:
read more about it **here**, the link sends to a page with a 404 response.
Changes have been made to resolve this error.
> fix: updated link - Redis URL Docs

- src/data/roadmaps/system-design/content/sql-tuning@fY8zgbB13wxZ1CFtMSdZZ.md
There is an unavailable resource in the System Design roadmap on the topic of SQL Tuning. (See the issue #8078)
This PR closes #8078 by replacing the unavailable resource with [Oracle's excellent article](https://docs.oracle.com/en/database/oracle/oracle-database/23/tgsql/introduction-to-sql-tuning.html#GUID-B653E5F3-F078-4BBC-9516-B892960046A2) from their course on SQL Tuning.
This PR also adds an additional sentence that briefly describes SQL Tuning.
> fix: replace unavailable resource and add more description (closes #8078)

- src/data/roadmaps/linux/content/108-service-management/index.md
There was no resource available for Linux service management in the [Linux roadmap](https://roadmap.sh/linux).
Adds hands-on resource for Linux service management for the betterment of the roadmap.
LabEx provides an excellent guide which explores Linux service management through systemd and systemctl.
> Add resource for linux service management

- src/data/roadmaps/flutter/content/100-dart-basics/101-variables.md
The statement was not true, as technically, global variables are also able to be declared
> Flutter- Update 101-variables.md

- src/data/roadmaps/git-github/content/github-wikis@lONqOqD-4slxa9B5i9ADX.md
- src/data/roadmaps/git-github/content/workflow-context@BnPiTu1Jw2kIW560a2A5T.md
- src/data/roadmaps/git-github/content/workflow-runners@6QwlY3dEvjfAOPALcWKXQ.md
- src/data/roadmaps/git-github/content/workflow-triggers@55uHPFNwYPVZx8Cy3c985.md
A few [GitHub docs](https://docs.github.com/en) are tagged as `article` when they should be `official` as I understand it from [contribution.md](https://github.com/kamranahmedse/developer-roadmap/blob/bcf4126b3a4b3622acc8cfc80b1b1095cf2d11f2/contributing.md), mentioned in #8111.
Closes #8111 by fixing the types, specifically changing them from `article` to `official`.
> Fix inappropriate resource types on Git-GitHub Roadmap (Closes #8111)

- src/data/roadmaps/data-analyst/content/finding-outliers@-rQ8h_6NFxEOhxXgo7LHo.md
A resource link on Data Analyst roadmap is invalid due to broken URL, mentioned in #8123.
This PR closes #8123 by fixing the broken resource link (removing the unnecessary "`[`" at the beginning on the link).
> Fix resource link on Data Analyst roadmap (Closes #8123)

- src/data/roadmaps/game-developer/content/epa@vWLKYK2KUzV1fO-vQunzW.md
##
The existing text defines EPA (in the context of game development collision resolution) as "Environmental Protection Agency" or "Event-driven Process chain Architecture" which is incorrect.
EPA (Expanding Polytope Algorithm) is used for finding the penetration vector between two convex shapes in order to resolve that collision. I've updated the text and added popular resources to reflect so.
Please let me know of any suggestions!
> Fix EPA definition

- src/data/roadmaps/redis/content/atomicity-in-redis@jrgaoDnt_RxTu79hk4hCD.md
- src/data/roadmaps/redis/content/rpop@brUGqWZ287EWtvl9uUbNt.md
1. Fixed a link pointing to a wrong address
2. Fixed typo causing links to display improperly
> Fixed some typos on redis rodemap

- src/data/roadmaps/linux/content/103-working-with-files/103-soft-hard-links.md
There is no resource listed for [Linux roadmap](https://roadmap.sh/linux) on soft and hard links at the moment.
This PR adds [an excellent resource from LabEx on soft and hard links](https://labex.io/tutorials/linux-how-to-understand-the-difference-between-hard-and-symbolic-links-in-linux-409929) to the list of resources. 
LabEx has been used as resource on the roadmap a few times now, so this PR adds a level of consistency to the roadmap as well.
> Add article resource to Linux roadmap on soft and hard links

- src/data/roadmaps/php/content/null-safe-operator@1NXSk8VZDr89jQTTkOL7x.md
There is [an unavailable resource link which currently returns `404`](https://www.php.net/manual/en/language.oop5.nullsafe.php) on [PHP roadmap](https://roadmap.sh/php), as mentioned in #8149 
This PR closes #8149 by removing the unavailable link and adding two official resources for the topic `Nullsafe Operator`:
- [PHP The Basics - Manual](https://www.php.net/manual/en/language.oop5.basic.php): there is a section for `Nullsafe Operator`. I assume the the official doc was moved here.
- [PHP RFC: Nullsafe operator](https://wiki.php.net/rfc/nullsafe_operator): PHP RFCs (Request for Comments) proposal for `Nullsafe Operator`, which explains the reasoning, design decisions, and implementation details.
> Replace unavailable resource link on PHP roadmap (Closes #8149)

- src/data/roadmaps/cpp/content/112-idioms/106-copy-write.md
[`std::shared_ptr<T>::unique`](https://en.cppreference.com/w/cpp/memory/shared_ptr/unique) was removed in `c++20`. This PR updates the provided code example to use [`std::shared_ptr<T>::use_count`](https://en.cppreference.com/w/cpp/memory/shared_ptr/use_count).
Side remark: the original example still compiles fine in g++ and clang++, but fails in the newest MSVC.
> Make the code example `c++20` compliant

- src/data/roadmaps/game-developer/content/godot@7OffO2mBmfBKqPBTZ9ngI.md
The **visual scripting** is no longer available in the latest version of Godot Engine. Therefore, it is removed from the description.
> Update description of Godot game engine in game dev roadmap

- src/data/roadmaps/game-developer/content/joints@m2_wUW2VHMCXHnn5B91qr.md
Update Broken Link in Joints Section
The Game Character Rigging Fundamentals link led to unavailable page.  
Changes:  
- Replaced the broken link with accessible resource on game character rigging.  
- Added a new link pointing to the official Unity documentation for accurate information.  
Related Issue: #8232
> Fix: Update Broken Link in Joints Section 

- src/data/roadmaps/backend/content/architectural-patterns@tHiUpG9LN35E5RaHddMv5.md
This article is 404ing so I've replaced with the links new location on Medium
> Swap out a 404ing link from Backend Architectural patterns with its new location

- src/data/roadmaps/docker/docker.json
There was a typo in docker roadmap,
(ghcr, ecr, gcr, act, etc) in this act was out of context and **acr** was correct 
as **acr = Azure Container Registry** which matches the context
> typo in docker roadmap : (act to acr)

- src/data/roadmaps/cpp/content/100-introduction/101-why-cpp.md
- src/data/roadmaps/cpp/content/105-pointers-and-references/smart-pointers/100-weak-ptr.md
- src/data/roadmaps/cpp/content/110-stl/index.md
- src/data/roadmaps/cpp/content/112-idioms/106-copy-write.md
- src/data/roadmaps/cpp/content/113-standards/101-cpp17.md
- src/data/roadmaps/cpp/content/libraries/101-open-cv.md
- src/data/roadmaps/cpp/content/libraries/108-opencl.md
This PR essentially adds the missing space after the keywords like `if` and `for`. This makes the C++ code examples more consistent.
It turned out that all the examples are properly formatted around `while` and `switch`.
> Use consistent formatting

- src/data/roadmaps/git-github/content/unstaged-changes@uxqJzQFRcALqatNRIWR0w.md
The topic (unstaged changes) content in Git and GitHub roadmap incorrectly described the behavior of `git diff` and the purpose of the `--unified` option. This commit fixes the definition to accurately reflect how `git diff` works and the role of `--unified`.
Changes:
- Clarify that `git diff` compares the working directory against the staging area for unstaged changes, not directly against the latest commit.
- Explain that `--unified` controls the number of context lines shown in the diff output, rather than being a mode for comparing unstaged changes.
- Add examples to illustrate the correct usage of `git diff` and `--unified`.
This update ensures users have a clear and accurate understanding of how to review changes and customize diff output.
> fix inaccuracy in Git and GitHub roadmap topic content

- src/data/roadmaps/aws/content/116-lambda/100-creating-invoking.md
- src/data/roadmaps/aws/content/116-lambda/101-layers.md
First commit is adding a link to an updated video from Tiny Technical Tutorials which overview the lambda and show how to create an practical example.
Second commit is adding a link to a Vincent Stevenson video explaining and creating an layer to a python script.
I think both videos are great to see a practical example and understand the basic of each topic.
> Adding 2 videos links to Aws Roadmap - Lambda-Creating and Lambda-Layers subtopics

- src/data/roadmaps/mongodb/content/108-developer-tools/101-mongodb-connectors/100-kafka.md
Replaced the broken link to Confluent Hub's MongoDB Kafka Connector with a valid and updated source.
Issue: #8271
> Fix Broken Link

- src/data/roadmaps/java/content/exception-handling@g9P3548F38tYGjevBc42w.md
- The previous URL for the article "Exception Handling in Java" in the Java Developer Roadmap was not working. 
- Replaced it with a working URL.
> Update broken URL

- src/data/roadmaps/php/content/object-relational-mapping-orm@SeqGIfcLuveZ2z5ZSXcOd.md
Replace broken resource URL with a better FreeCodeCamp article  
The previous resource URL was not found, so I replaced it with a more relevant article from FreeCodeCamp:   https://www.freecodecamp.org/news/what-is-an-orm-the-meaning-of-object-relational-mapping-database-tools
> Replace broken resource URL with a better FreeCodeCamp article

- src/data/roadmaps/angular/content/typed-forms@XC_K1Wahl2ySqOXoym4YU.md
The @let link was included inside the typed-forms part of angular, where typef-forms docs of angular was missing
> Fixed a bad link about typed forms in Angular Roadmap

- src/data/roadmaps/aspnet-core/content/manual-mapping@oMMBzRrHkUymxAR4oqr75.md
content for manual mapping in aspnet core section
> Added content for Manual mapping in aspnet core

- src/data/roadmaps/api-design/content/cookies@UFuX8wcxZQ7dvaQF_2Yp8.md
The Cookies step is under the HTTP group and I'm expecting to find high-level articles there about different aspects of HTTP and not about JS API. Hence the link is replaced with a more relevant article from the same source.
> [API Design Roadmap] Replacing HTTP cookies article about  JS API with more relevant one

- src/data/roadmaps/cpp/content/running-your-first-program@SEq0D2Zg5WTsIDtd1hW9f.md
Same as:
- #8252
@kamranahmedse please have a look.
> `std` is not an abbreviation for STL

- src/data/roadmaps/server-side-game-developer/content/epoll@qaWv4gxnnj3uX8lEm9KQ4.md
- src/data/roadmaps/server-side-game-developer/content/io_uring@YH7u1FKh85wz78J0stuzS.md
- src/data/roadmaps/server-side-game-developer/content/iocp@7pgdOZomhGilBTwfJLMbm.md
- src/data/roadmaps/server-side-game-developer/content/kqueue@caK32NMMrn-3BGAXZoPPr.md
- src/data/roadmaps/server-side-game-developer/content/registered-io@94hJX1iGifDzIuaU3zU5j.md
- src/data/roadmaps/server-side-game-developer/content/select@5-5toy2CblZPCV9d5QPEo.md
- src/data/roadmaps/server-side-game-developer/content/semaphore@DYvzGc_r0SlOArPPc1gNI.md
- src/data/roadmaps/server-side-game-developer/content/wsa-poll@D9Yeyn8phDhB1ohMWccgr.md
This pull request enhances the `Server-Side Game Developer` Roadmap by adding missing content to improve clarity and usability for developers. The updates include detailed information on the following topics:  
- **semaphore**
- **epoll**
- **wsa-poll**
- **select**
- **iocp**
- **io_uring**
- **registered-io**
- **kqueue**
These additions aim to make the roadmap more comprehensive and valuable for developers working on server-side game development.
issue: #8406
> Update missing content in the `Server-Side Game Developer` Roadmap.

- src/data/roadmaps/ai-engineer/content/capabilities--context-length@vvpYkmycH0_W030E-L12f.md
the [previous link](https://platform.openai.com/docs/guides/text-generation/managing-context-for-text-generation) directed to a 404 page. the new link corrects this
> update official link for managing context (ai engineer roadmap)

- src/data/roadmaps/postgresql-dba/content/rows@Rd3RLpyLMGQZzrxQrxDGo.md
A reference to the outdated PostgreSQL 7.1 documentation was removed, which incorrectly states that every row has an OID. This no longer reflects PostgreSQL behavior since version 8.1.
> Remove outdated PostgreSQL 7.1 documentation link

- src/data/roadmaps/flutter/content/dev-tools/flutter-outline.md
**Fix the incorrect link to the Flutter documentation.**   The current link points to the documentation for the `OutlineButton` widget, but it should link to the documentation about the Flutter widget tree, since the topic is about the hierarchy of widgets, NOT the `OutlineButton`.
> Update flutter-outline.md (Fix incorrect link)

- src/data/roadmaps/cpp/content/virtual-methods@hNBErGNiegLsUJn_vgcOR.md
- Added a concise overview of virtual function in C++
> Virtual functions in C++ (added content)

- src/data/roadmaps/postgresql-dba/content/databases@DU-D3-j9h6i9Nj5ci8hlX.md
- Removed outdated link to PostgreSQL 7.1 documentation.
- Updated remaining link from version 8.1 to current to ensure long-term accuracy and relevance.
- This change ensures that users are directed to the latest stable PostgreSQL documentation.
> Update PostgreSQL docs link to current version

- src/data/roadmaps/ai-engineer/content/supabase@9kT7EEQsbeD2WDdN9ADx7.md
current reference is https://supabase.com/docs/guides/ai/vector-columns
previous reference was https://supabase.com/vector which is now a 404
> update official supabase vector reference

- src/data/roadmaps/system-design/system-design.json
This PR replaces the `System Design` track from the suggested learning paths at the end of the System Design roadmap with `Software Architect`. This change prevents looping back to the same roadmap and provides a more relevant learning direction.
Issue: #8428
> Replace `System Design` Track with `Software Architect` in Suggested Learning Paths

- src/data/roadmaps/typescript/content/as-any@afTNr36VqeXoJpHxm2IoS.md
Link to `any` type documentation is named as `Array`:
This PR sets the proper name for the link
> TS roadmap: fix typo in link to `any` official doc

- src/data/roadmaps/react/content/cli-tools@tU4Umtnfu01t9gLlnlK6b.md
Create React App is [deprecated](https://react.dev/blog/2025/02/14/sunsetting-create-react-app). so updated the link with the official modern solution.
> fix: update create-react-app to the latest link

- src/data/roadmaps/graphql/content/mutations/what-are-mutations.md
The "Get started with Mutations" link in the GraphQL roadmap points to the GraphQL Queries documentation.
Fixes - Added the correct link in the .md file
> Add correct link for GraphQL Mutations 

- src/data/roadmaps/vue/content/options-api@PPUU3Rb73aCpT4zcyvlJE.md
The previous description made it sound like "idk, it's old, and you shouldn't use it".
Options API isn't "the bad one". If it wasn't good, it wouldn't be in the framework. It offers specific benefits that Composition API does not. I've updated the description to better outline this.
> Update Vue options-api.md

- src/data/roadmaps/mongodb/content/query-operators/array-operators/elem-match.md
Corrects a logically incorrect MongoDB query example in `elem-match.md`.
The original example tries to match two different `subject` and `score` values inside a single `$elemMatch` clause. However, since object keys must be unique, only the last `subject` and `score` values are actually considered. This makes the query behave differently than intended.
**_Since we want to find all the students who have scored 80 or above in Math and 70 or above in English, the query can even match the documents with no "Math" subject at all in "grades" field._**
> _Documents like this will be selected (which you don't want) 👉 **"grades" : [ { subject: "Science", score: 80 }, { subject: "English", score: 75, } ]**_ 
Replaced the query with one that uses `$and` and two separate `$elemMatch` clauses:
- One …
> Fix logical mistake in $elemMatch example in elem-match.md

- src/data/roadmaps/android/android.json
- src/data/roadmaps/android/content/recyclerview@xIvplWfe-uDr9iHjPT1Mx.md
- src/data/roadmaps/android/content/recycleview@xIvplWfe-uDr9iHjPT1Mx.md
- Renamed the content file from `recycleview@x1vpIWfe-uDr9iHjPTlMx.md` to `recyclerview@x1vpIWfe-uDr9iHjPTlMx.md`
- Updated the roadmap graph node label from `"RecycleView"` to `"RecyclerView"` in `android.json`
- Fixed grammar and word clarity in the content markdown
Official Android documentation for RecyclerView:
https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView
> fix: correct spelling of "RecyclerView" in Android roadmap

- src/data/roadmaps/linux/content/navigation-basics/directory-hierarchy.md
This PR adds a brief explanation of the `/opt` directory to the Linux roadmap's "directory-hierarchy.md" content file.
- Describes `/opt` as the place for third-party applications.
- Keeps style consistent with the rest of the section.
This small addition improves clarity and completeness of the Linux filesystem overview.
> Fix: Add missing /opt explanation to Linux directory hierarchy

- scripts/generate-og-images.mjs
This small PR fixes a bug where `const` was used for a `template` variable that may be reassigned after unescaping HTML. The fix replaces `const` with `let` to allow mutation of template when special characters are present in guide metadata. This resolves runtime errors and ensures proper rendering of OG images for guides with special characters in titles or descriptions. It also fixes a small typo along the way.
> Allow mutation of guide template for HTML unescaping

- src/data/roadmaps/software-design-architecture/content/abstract-classes@RMkEE7c0jdVFqZ4fmjL6Y.md
The original [link](https://computinglearner.com/abstract-class-in-object-oriented-programming/) re-directed to some online store that looks rather [spammy](https://microtunnellink.com/). This PR changes the link to an [article](https://www.theserverside.com/definition/abstract-class) from The Server Side that describes abstract classes without relying on any specific language.
> Update abstract class link

- src/data/roadmaps/android/migration-mapping.json
Follow up to PR: https://github.com/kamranahmedse/developer-roadmap/pull/8706
This patch fixes an oversight in the original PR where the migration mapping key for RecyclerView was not updated. While the node label and markdown file were corrected, the outdated slug (recycle-view) in the mapping logic caused the node to not update.
This change updates the mapping to use the correct slug: `recycler-view`.
> fix(android): correct migration mapping for recyclerview

- src/data/roadmaps/cpp/content/references@uUzRKa9wGzdUwwmAg3FWr.md
Just fixed a small mix-up in the explanation, the example code is correct.
> fix: correct c++ reference declaration text

- src/components/Projects/LeavingRoadmapWarningModal.tsx
- src/components/Schedule/ScheduleEventModal.tsx
This pull request removes redundant close buttons from two modal components in the project. These changes simplify the UI and reduce duplication, as the modals already have other mechanisms to close.
Changes to modal components:
* [`src/components/Projects/LeavingRoadmapWarningModal.tsx`](diffhunk://#diff-8a956104438536221771306c164e975d35e5c411e09316fc551837c578f89185L56-L62): Removed the close button (`<button>` element) from the modal, which was positioned at the top-right corner.
* [`src/components/Schedule/ScheduleEventModal.tsx`](diffhunk://#diff-1d01aa64c14f241e3c416ba940aa663f86f7a5112b7b76ef0f72a0e2ab30ce59L200-L205): Removed the close button (`<button>` element) from the modal, which was positioned at the top-right corner.
| Before | After |
|--------|-------|
| …
> Remove redundant close button from `LeavingRoadmapWarningModal`

- src/data/roadmaps/aspnet-core/content/c@fxANnSiTb2VzA9u-YeBL1.md
Fixes images missing due to double slash at the end.
> fix: update c# site to resolve missing images

- src/data/roadmaps/spring-boot/spring-boot.json
Updated the label of the navigation button at the bottom of the Spring Boot Roadmap page. The button previously read "Frontend Roadmap", which was misleading, as it actually links to the Java Roadmap page.
This change aligns the label with the correct destination URL, which is intentional and consistent with the content referenced in spring-boot.pdf, where it clearly mentions the Java Roadmap. No URL changes were made, as the link is correctly pointing to the Java roadmap.
> fix(label) Issue #8959 : Corrected navigation button label from 'Frontend Roadmap' to 'Java Roadmap'

- src/data/roadmaps/rust/content/option-and-result-enumerations@wQHkBydWsiGEOZMdKmz40.md
Andrew Gallant, the author of ripgrep, wrote a pair of articles that break down error handling very well, starting from the basics to more advanced scenarios of using Options and Results effectively. These articles have helped me and continue to serve as a reference point in my rust journey.
> Add two articles that are very informative to the Options and Results page

- src/lib/guide-renderer.tsx
**This pull request makes the following changes:**
*Fixes issue #8940  
- Updates the Table of Contents slugs for "Intermediate Level" and "Advanced Level"  
so they match the existing heading IDs (`id="intermediate"` and `id="advanced"`).  
This ensures that the links correctly scroll to the intended sections.
Note: "Beginner Level" already works both with `beginner` and `beginner-level`, 
because of the way `slugify("Beginners")` is handled.
> Fixes issue #8940
